### ISSUE TITLE
Allow user to pick kernel type

### ISSUE THREAD

**Issue by szollin** [clearlinux/clr-installer#134]
**Is your feature request related to a problem? Please describe.**
kernel-native is default with installation

**Describe the solution you'd like**
It would be good to allow the user to pick the kernel type they want installed instead of doing it after installation. An example is allowing kernel-lts to be installed at boot.

**Describe alternatives you've considered**
The alternative is to install with kernel-native and change the kernel type after first boot.

**Additional context**
Not all users will want kernel-native as their default kernel. An example is that kernel-lts is more stable so allowing installation with it would provide a more stable system during install.

**Comment by mdhorn** [comment]
@szollin I think this is covered in the Advanced screen. If there is an addition kernel choice needed, please re-open this Issue or generate a new one with the required kernel bundle.

**Comment by szollin** [comment]
This works for me. I was just trying to make sure that we were in a good spot since switching after install isn't the best process.
