### ISSUE TITLE
"Enable telemetry" and "Automatic OS Updates" text doesn't fit on button 

### ISSUE THREAD

**Issue by kkovatch** [clearlinux/clr-installer#136]
**Describe the bug**

The text label on the "enable telemetry" button in the set up flow doesn't fit the button. Ditto on the "Enable Automatic OS Updates" button...

**To Reproduce**

In the setup experience, open the telemetry option and view thee "enable telemetry" text on the the button...

**Expected behavior**

Fit the text correctly so it's readable.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS Version: [swupd info]
 - Installer Version [clr-installer -v] 1.0.0
 - Platform: [hardware infomation]

**Additional context**

**Comment by mdhorn** [comment]
@kkovatch This bug was due to the TUI version of the Clear Linux OS Installer targetted to run in a text-based 80x24 screen size only.

Submitted a Pull Request to ensure we resize this button type when the terminal size is changed.
