### ISSUE TITLE
Support dual OS

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#14]
<a href="https://github.com/dorileo"><img src="https://avatars.githubusercontent.com/dorileo" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dorileo](https://github.com/dorileo)**
_Tuesday Apr 10, 2018 at 20:02 GMT_

----

Request to be able to install Clear Linux on a media where an existing OS already resides.

**Comment by mdhorn** [comment]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdhorn](https://github.com/mdhorn)**
_Friday Jul 20, 2018 at 23:55 GMT_

----


The technical scope of what is possible due to Clear Linux booting requirements need to be reviewed prior to committing to this request.

**Comment by mdhorn** [comment]
The primary goal is to meet similar requirements to what was possible in ister_gui.
- Install Clear Linux OS onto a target media with an existing OS present
-- Only update the GUID Partition Table (GPT) with newly added partition(s)
-- Only create file systems on new partition(s)

Open Items:
- Enable reuse of existing partitions (swap, /home, /srv, ...)

**Comment by mvincerx** [comment]
We're eager to implement this change in the docs too. This would greatly improve multi-boot scenarios, especially with Windows. I have an open PR on this: https://github.com/clearlinux/clear-linux-documentation/pull/382

**Comment by mdhorn** [comment]
The partitioning changes are now supported in the User Interface.
Not sure if anything else can be done for this topic in the installer unless Clear Linux* OS improves or considers supporting other boot loaders.
