### ISSUE TITLE
Installer and monitor resolution

### ISSUE THREAD

**Issue by seanvk** [clearlinux/clr-installer#143]
**Describe the bug**
clr-installer at HEAD when brought up on an LG external display is not scaling
**To Reproduce**
1. Connect an Ultra-HD display.
2. Boot a system attached to it with the latest installer image.
3. See resulting image:

https://drive.google.com/open?id=1Fxr_g1Q0YFccvh-vWuYUYnBqhqcDANMg

**Expected behavior**
I would expect an installer that visually scales with the monitor.

**Screenshots**
See Google drive link above

**Environment (please complete the following information):**
 - Clear Linux Installer Version: [HEAD as of 2018-11-09]
 - Installer Version [clr-installer -v] 1.0.0
 - Platform: Core i7 8700 with Intel Graphics

**Additional context**

**Comment by seanvk** [comment]
For comparison, existing installer on the same system is reasonable:

https://drive.google.com/open?id=1AZlcwM2W_hgTlVWcDtmlOVZX8xeEk2lU

**Comment by dorileo** [comment]
we need to enable modedb

**Comment by dorileo** [comment]
@seanvk did you make the image yourself? or are you running it from your dev system?

**Comment by seanvk** [comment]
@dorileo I made the image myself

**Comment by dorileo** [comment]
fixed with #165

**Comment by jairglez** [comment]
Please re-open. This issue is reproducible on **Clear Linux OS installer (1.1.8)** on image clear-28380-installer.img.

**Tested on:**

- NUC6i5SYH with external monitor (resolution: 1920*1200-60 Hz).
- XPS 13 with HD laptop monitor (resolution: 3840*2160-60 Hz).

**Comment by mdhorn** [comment]
@jairglez When did this start occurring again?
Maybe there was a kernel change disabling the nomodeset?

**Comment by mdhorn** [comment]
As we've had the graphical installer for a mid-May, this no longer should be a critical need.
