### ISSUE TITLE
Configure Media Disables "Confirm" after adding partitions

### ISSUE THREAD

**Issue by seanvk** [clearlinux/clr-installer#145]
**Describe the bug**
When attempting to Configure Media, I deleted the partitions and added replacement partitions.  However, I was unable to "Confirm" the Configure Media page as the button was disabled.
My only recourse was to cancel, thus losing my customer partitioning.

**To Reproduce**
1. Boot system with latest clr-installer
2. Select Configure Media
3. Manually delete partitions
4. Manually add partitions
5. Attempt to confirm partitioning

**Expected behavior**
Confirm is selected and I return to the main menu with Media clearly selected.
**Screenshots**

https://drive.google.com/open?id=1lq07Myz09oDuzmgrlslsJ-2IZ_ICEyAy

**Environment (please complete the following information):**
 - Clear Linux Installer Version: [HEAD as of 11-9-2018]
 - Installer Version [clr-installer -v] 1.0.0
 - Platform: [hardware infomation] Core i7 8700

**Additional context**

**Comment by mdhorn** [comment]
@seanvk The 'Confirm' button is only enabled when you meet the minimum partition requirement for the installation process:
- "/boot" partition of type VFAT, OR enable the Legacy BIOS flag
- "/" partition

In the case you have documented here, you have a "/boot" partition, but not of the correct filesystem type.

**Comment by seanvk** [comment]
@mdhorn The assumption here is that /boot has to be VFAT.  That is not required for normal UEFI supporting distributions.  When I use Arch, Fedora, Debian, etc.  I can have a /boot that is ext4 and VFAT for the EFI partition which is mounted below /boot.  This is an artificial constraint.

**Comment by mdhorn** [comment]
@seanvk We didn't create the constraint to please the Installer, I was told this is a requirement for clr-boot-manager.

**Comment by seanvk** [comment]
@mdhorn I don't believe that is the case.  See @bryteise response to the alternative mount location for ESP.  There's nothing with clr-boot/systemd-boot that would prevent me from having:
/boot . ext4
/boot/efi  VFAT ESP

**Comment by mdhorn** [comment]
Have you verified this work with our clr-boot-manager?
I was told it will not, by @bryteise

**Comment by mdhorn** [comment]
Closing in favor of existing enhancement request issues #150 and #147
