### ISSUE TITLE
Installer artificially limits a VFAT partition size to 512MB

### ISSUE THREAD

**Issue by seanvk** [clearlinux/clr-installer#147]
**Describe the bug**
When using Configure Media -> Partition Setup it artificially limits VFAT partition sizes to 512MB

**To Reproduce**
1. Boot with latest clr-installer
2. Configure Media -> Partition Setup
3. Enter a VFAT size larger than 512MB
4. See image from my google drive

https://drive.google.com/open?id=1r6RVaE71HB0rqUL8urDzVfCfgp9QDRwa

**Expected behavior**

 VFAT could support anywhere up to 4TB depending on partition sector sizes.

**Screenshots**
See above drive image.  I purposefully set the size to 513M to show the error.

**Environment (please complete the following information):**
 - Clear Linux OS Installer: [swupd info] HEAD as of 11-9-2018
 - Installer Version [clr-installer -v] 1.0.0
 - Platform: [hardware infomation] Core i7 8700

**Additional context**

**Comment by mdhorn** [comment]
@seanvk The error message about size is stating that you are attempting to set the size of the partition larger than the free space available. We aren't limiting the size of a VFAT.

**Comment by seanvk** [comment]
@mdhorn But there was ample space or so I thought.  I will do it again.  But I am almost positive in a clean partition I was creating them in order EFI Partition then Boot partition, etc so there was free space.

**Comment by mdhorn** [comment]
We will be re-evaluating implementation after we have evidence this works with the clr-boot-manager.

**Comment by bryteise** [comment]
So the minimum size for compatibility reasons is likely 256MB based on [this](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions#diskpartitionrules) with the maximum being forced by fat32 compatibility as well.

**Comment by mdhorn** [comment]
Leaving as VFAT which is a Clear Linux requirement
