### ISSUE TITLE
Installer does not support having EFI as subfolder of boot

### ISSUE THREAD

**Issue by seanvk** [clearlinux/clr-installer#150]
**Describe the bug**
I can't do a custom partitioning in which the efi partition exists as a subfolder of /boot.  I can do that with every other distro.  I make /boot ext4 and the efi partition mount point of /boot/efi

**Comment by seanvk** [comment]
To keep the kernel updated, it is simpler and typically recommended to mount the ESP to /boot. If the ESP is not mounted to /boot, the kernel and initramfs files must be copied onto that ESP.  It sounds like to me that clr-boot / systemd-boot installer and updater assumes the latter.  But there is nothing to prevent you from using the first approach with systemd-boot.

**Comment by bryteise** [comment]
clr-boot-manager will attempt to mount the ESP on /boot as configured in Clear Linux today.

**Comment by seanvk** [comment]
That's good.  So @mdhorn I just need the installer to allow me to set a different mount point for ESP

**Comment by mdhorn** [comment]
@seanvk What I understood was that /boot is the only choice; did I miss something?
@bryteise @nesiusra

**Comment by mdhorn** [comment]
We will be re-evaluating implementation after we have evidence this works with the clr-boot-manager.

**Comment by seanvk** [comment]
I understand @bryteise I'm just too use to working with Arch and configuring with bootctl where ESP is mounted.  From IRC it seems like all of this is driven by having a single partition for both ESP and Boot hence the VFAT topic.  I'm fine with closing this as I just wanted to confirm that it was a policy form the OS perspective rather than a limitation.

**Comment by miguelinux** [comment]
This is an **invalid request**.

Others distros use `/boot` to storage kernel files.
Clear Linux uses `/usr/lib/kernel`.

When others EFI distros updates the kernel, they updates `/boot` and copy kernel files to `/boot/efi`.
CL updates the kernel in `/usr/lib/kernel` and copy kernel files to `/boot`

`/boot/efi` on others distros and `/boot`on CL is simply ESP, (just a partition)

`bootctl` is configure to use `/boot/` as ESP (as default), but you can change the path with a parameter, as you said before. 

@seanvk 
What is your use case for /boot/efi?

**Comment by mrkz** [comment]
@seanvk @miguelinux so perhaps we can close this but may be worth to have this into an F.A.Q. kind of thing if this is regularly used in other distros, so the WHY can't be done it's well documented?

**Comment by knuckolls** [comment]
@miguelinux it's probably a bit my fault as much as it is the documentation but I just spent a great amount of time finding where Clear Linux allows me to edit the cmdline params of my kernel. If that comment is in the official documentation somewhere, I never ended up finding it. Worth highlighting in the official docs somewhere.

Hope this helps.
