### ISSUE TITLE
Show defaults for language/keyboard

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#17]
<a href="https://github.com/matthewrsj"><img src="https://avatars.githubusercontent.com/matthewrsj" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matthewrsj](https://github.com/matthewrsj)**
_Thursday May 03, 2018 at 17:42 GMT_

----

Show what the default is in these screens so I don't feel like I have to scroll through the huge list to select something that is probably already configured.

**Comment by mdhorn** [comment]
<a href="https://github.com/dorileo"><img src="https://avatars.githubusercontent.com/dorileo" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dorileo](https://github.com/dorileo)**
_Monday May 07, 2018 at 19:38 GMT_

----

Actually it's being displayed. The selected item is the default one. The symbol [-] in the main menu indicates it was either auto detected or is using the default value.

**Comment by mdhorn** [comment]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdhorn](https://github.com/mdhorn)**
_Thursday May 24, 2018 at 21:43 GMT_

----

Show selection choice on the main menu screen

**Comment by dorileo** [comment]
We're changing the main menu (code under review now #37), I suppose the changes to show the currently set values will do the job. I'm closing this one, please reopen if needed.
