### ISSUE TITLE
Verify clr-installer runs as root on startup

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clr-installer#171]
**Describe the bug**
The installer should verify if root (or privileged account) launched the clr-installer binary prior to any setup (probably at startup?), otherwise, a normal user will launch the installer and set up all options, failing a the very end because of insufficient permission, this is a bit frustrating given the time it takes to set up all data for the new install

**To Reproduce**
1. Open a Terminal
2. Execute `/usr/bin/clr-installer` as non-root
3. Set up all required bits for installation
4. When click on `Install` the clr-installer will exit with no message for the user (no way to know if it failed or what actually happened).
5. Look at the log to check the failure:
```
# cat /home/clrlinux/clr-installer.log
2018/11/27 09:46:09 [INF] clr-installer: 1.0.0-71-g002fbc5, built on 2018-11-27_15:25:04_UTC
2018/11/27 09:46:09 [INF] NOTICE: Enabling Telemetry preferred by default on internal networks
2018/11/27 11:15:22 [INF] Testing connectivity
2018/11/27 11:23:36 [ERR] 

Error Trace:
utils.VerifyRootUser()
     .gopath/src/github.com/clearlinux/utils.go:95
controller.Install()
     .gopath/src/github.com/clearlinux/controller.go:71
 clr-installer MUST run as 'root' user to install! (user=1001)
```

**Expected behavior**
The failure message should appear at the startup of the clr-installer, avoiding a user to perform all the setup as non-root user and failing at the very end.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS Version: clear-26500-live-desktop-beta.img
 - Installer Version: clear-26500-live-desktop-beta.img
 - Platform: NUC

**Comment by mdhorn** [comment]
Fixed by #173 and in release 1.1.0
