### ISSUE TITLE
Redraw installer on resize of terminal

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clr-installer#172]
**Is your feature request related to a problem? Please describe.**
Please make clr-installer to redraw on window resize to benefit from bigger windows as the menus are extensive, it's a bit annoying to not take advantage of a bigger screen than the fixed size of the current set up for the installer.

![screenshot from 2018-11-27 11-47-18](https://user-images.githubusercontent.com/978752/49101022-d1ff6200-f23a-11e8-9c91-14435cfe26d3.png)

![screenshot from 2018-11-27 11-47-34](https://user-images.githubusercontent.com/978752/49101026-d461bc00-f23a-11e8-824d-b1fd485cd0f6.png)

**Comment by mdhorn** [comment]
Sorry, we aren't planning to support this.
Using the Text User Interface in a Graphical environment was not planned.

There will be a true Graphic User Interface released next quarter.
