### ISSUE TITLE
wrong efivars handling after install

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clr-installer#174]
**Describe the bug**

After the installation process using `clr-installer`, I reboot and I get directly into EFI shell, instead of the new Clear Linux* installation. Not sure how or why this happens (perhaps efivars overpopulation?).

The Clear Linux* OS is successfully installed, but I cannot boot into it when I power the device ON.

![photo_2018-11-28_12-53-32](https://user-images.githubusercontent.com/978752/49177298-7b655700-f312-11e8-93e6-34c327b856af.jpg)

I have to manually boot from the efi shell as follows:
```
Shell> fs0:
Shell fs0: > cd EFI/org.clearlinux/
Shell fs0: > bootloaderx64.efi
```

**To Reproduce**
1. Install Clear Linux* OS using `clr-installer`
2. Reboot
3. Efi shell promt is booted instead of new CLR installation

**Environment (please complete the following information):**
These are the EFIvars as shown by `efibootmgr` command (both previous/after to running the `/usr/bin/clr-boot-manager udpate` command which fixes the boot into OS issue).

```
root@clr-877b8c8ca8664baeb8ee3f5c7b82f08a ~ # efibootmgr
BootCurrent: 000E
Timeout: 1 seconds
BootOrder: 000E,0007,0014,0006,000D,0002,000B,000A,0003,0008,0004,0005,0001,0013,000C,0009,000F,0000
Boot0000* Windows Boot Manager
Boot0001* Windows Boot Manager
Boot0002* Linux bootloader
Boot0003* Linux bootloader
Boot0004* Linux bootloader
Boot0005* Linux bootloader
Boot0006* LAN : IBA CL Slot 00FE v0104
Boot0007* SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : Boot Drive
Boot0008* Linux bootloader
Boot0009* Linux bootloader
Boot000A* Linux bootloader
Boot000B* Linux bootloader
Boot000C* Fedora
Boot000D* Linux bootloader
Boot000E* UEFI : Built-in EFI Shell
Boot000F* Linux bootloader
Boot0013* Linux bootloader
Boot0014* UEFI : SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : OS Bootloader
root@clr-877b8c8ca8664baeb8ee3f5c7b82f08a ~ # clr-boot-manager update
root@clr-877b8c8ca8664baeb8ee3f5c7b82f08a ~ # efibootmgr
BootCurrent: 000E
Timeout: 1 seconds
BootOrder: 0010,000E,0007,0014,0006,000D,0002,000B,000A,0003,0008,0004,0005,0001,0013,000C,0009,000F,0000
Boot0000* Windows Boot Manager
Boot0001* Windows Boot Manager
Boot0002* Linux bootloader
Boot0003* Linux bootloader
Boot0004* Linux bootloader
Boot0005* Linux bootloader
Boot0006* LAN : IBA CL Slot 00FE v0104
Boot0007* SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : Boot Drive
Boot0008* Linux bootloader
Boot0009* Linux bootloader
Boot000A* Linux bootloader
Boot000B* Linux bootloader
Boot000C* Fedora
Boot000D* Linux bootloader
Boot000E* UEFI : Built-in EFI Shell
Boot000F* Linux bootloader
Boot0010* Linux bootloader
Boot0013* Linux bootloader
Boot0014* UEFI : SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : OS Bootloader
```

**Comment by dorileo** [comment]
@mrkz do you mean after running ```/usr/bin/clr-boot-manager udpate``` fixed your issue?

**Comment by dorileo** [comment]
ok, I'm guessing running a cbm update before umounting the volumes would avoid these kind of issues - I've not seen this with any of my tests but it's harmless.

**Comment by mdhorn** [comment]
@mrkz Does the log have "Installing boot loader" in it?
We do run `clr-boot-manager update` after installing bundles.

**Comment by mrkz** [comment]
> ok, I'm guessing running a cbm update before umounting the volumes would avoid these kind of issues - I've not seen this with any of my tests but it's harmless.

If you fire a branch on top of @mdhorn disk encryption PR, I can test quickly and check how it goes.

>@mrkz Does the log have "Installing boot loader" in it?
We do run clr-boot-manager update after installing bundles.

I apologize, it didn't think of looking at the log ;-(, I've wiped out the install by now as I'm trying to check if ister behaves the same about efivars manipulation.

**Comment by dorileo** [comment]
@mdhorn yep, we indeed do run cbm update.

**Comment by mrkz** [comment]
FWIW, I managed to get the same issue on a CLR install using ister too, so not really an issue with the installer.

@ikeyd @bryteise @josuedhg any idea if this error could be from [cmb](https://github.com/clearlinux/clr-boot-manager) any why this would fail at install phase but succeed when run from the installed CLR OS (running `/usr/bin/clr-boot-manager update`)?

**Comment by dorileo** [comment]
The only special thing with it is that we run cbm with ```--path``` argument.

**Comment by mrkz** [comment]
so after removing several efi entries, I'm still having this issue after an install is completed,

This is the list I have as of now:
```
# efibootmgr
BootCurrent: 000E
Timeout: 1 seconds
BootOrder: 000E,0007,0013,0006,0012
Boot0006* LAN : IBA CL Slot 00FE v0104
Boot0007* SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : Boot Drive
Boot000E* UEFI : Built-in EFI Shell
Boot0012* Linux bootloader
Boot0013* UEFI : SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : OS Bootloader
```
Later on, I run `/usr/bin/clr-boot-manager update` and I got the following list:
```
# /usr/bin/clr-boot/manager update
# efibootmgr
BootCurrent: 000E
Timeout: 1 seconds
BootOrder: 0000,000E,0007,0013,0006,0012
Boot0000* Linux bootloader
Boot0006* LAN : IBA CL Slot 00FE v0104
Boot0007* SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : Boot Drive
Boot000E* UEFI : Built-in EFI Shell
Boot0012* Linux bootloader
Boot0013* UEFI : SATA : PORT 0 : INTEL SSDSCKKW480H6 : PART 0 : OS Bootloader
```
After this, I can reboot sucessfully into CLR OS

**Comment by bryteise** [comment]
@mrkz Hrm weird, I would guess that if you didn't run cbm but instead used efibootmgr to set next boot to 0012 things would boot normally? Maybe there is an issue when cbm is setting the default as part of the install.

**Comment by mdhorn** [comment]
Believe this was fixed in the last release of clr boot manager.

**Comment by hushino** [comment]
Same issue

**Comment by mdhorn** [comment]
> Same issue

@hushino Please do not comment on a closed issue. Especially one close for such a long time. 
If you are having a similar problem, and there is not an open issue, you can open a new issue. If you feel it is relevant, you can reference a previously closed issue.

If/when you create a new Issue, please provided the requested information so there more context to help understand your problem.
