### ISSUE TITLE
Customize kernel cmdline

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#18]
<a href="https://github.com/asifhg"><img src="https://avatars.githubusercontent.com/asifhg" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [asifhg](https://github.com/asifhg)**
_Monday May 07, 2018 at 18:38 GMT_

----

Allow the user to completely edit the default kernel cmdline, instead of only appending to it.

**Comment by mdhorn** [comment]
<a href="https://github.com/dorileo"><img src="https://avatars.githubusercontent.com/dorileo" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dorileo](https://github.com/dorileo)**
_Monday May 07, 2018 at 19:41 GMT_

----

We don't currently have a kernel cmdline configuration yet - I'm sure ister has it but the new installer hasn't received this configuration yet.

I'll make sure to allow editing instead of appending whenever we have it.

**Comment by mdhorn** [comment]
<a href="https://github.com/dorileo"><img src="https://avatars.githubusercontent.com/dorileo" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dorileo](https://github.com/dorileo)**
_Tuesday Jun 19, 2018 at 18:06 GMT_

----

I've implemented in the PR #150 the feature to append kernel arguments, we could evolve from there to edit - I haven't saw the detail to implement such change yet.

**Comment by mdhorn** [comment]
Making inquiries if there are specific use cases in mind that can not be accommodated by just adding to the existing command line.

**Comment by bryteise** [comment]
@mdhorn So editing the commandline is a bit of a pain still but you can remove things from it once I make a new release with https://github.com/clearlinux/clr-boot-manager/pull/124 in it.

**Comment by mdhorn** [comment]
@bryteise Very helpful to know. Thank you!

**Comment by mdhorn** [comment]
@asifhg The ability to add to or remove the kernel command line during the installation was implemented in version 1.0.0.
