### ISSUE TITLE
Allow installer to create partitions with no mount-point

### ISSUE THREAD

**Issue by mrkz** [clearlinux/clr-installer#180]
**Is your feature request related to a problem? Please describe.**

Picture this:

As a user I want to be able to dual-boot 2(or more) distros on a brand new disk, being Clear Linux* OS one of them.

I want the following disk partitions scheme for the install:

| partition | distro | mount point | encrypted |
|------------|---------|----------------|---------------|
|sda1 | CLR | `/boot` | NO |
|sda2 | * | `swap` | YES |
|sda3 | CLR | `/` | YES |
|sda4 | DBN | `/` | NO |
|sda5 | * | `/home` | YES |

If I were to use the CLR installer, `sda4` would not be able to be created without forcing me to use it as a mount point for the CLR installation which wouldn't be used at all by clr.

**Describe the solution you'd like**
Allow `clr-installer` to create partitions without having to match them into a mount point for the current installation.

**Describe alternatives you've considered**
Using `cgdisk /dev/sda` to manually create the desired disk partitions scheme previous to run the installer, making the installer to just use the partitions previously created. While this would work, this seems a bit odd to do given the fact that the installer has the ability to create partitions.

**Comment by mrkz** [comment]
I've tried using `cgdisk` and I leave sda4 with no mount point in the installer, but after I click install the following crash happens:
```
#  /usr/bin/clr-installer -l 4
panic: No makePartCommand() implementation for: 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203


goroutine 37 [running]:
github.com/clearlinux/clr-installer/tui.(*Tui).Run(0xc000157080, 0xc00008cc00, 0xc0001c4020, 0x16, 0x100, 0xc0000b0ce0, 0x17, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:162 +0x670
main.main.func4(0xc0000cf320, 0xc00008cc00, 0xc0001c4020, 0x16, 0xc0002bc995, 0xc0000a3b40, 0xc0001a4070)
	/builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:243 +0x168
created by main.main
	/builddir/build/BUILD/clr-installer-1.1.0/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:237 +0x93d

# cat ~/clr-installer.log
2018/12/03 14:55:32 [DBG] Log Level set to LogLevelDebug (4)
2018/12/03 14:55:32 [INF] clr-installer: 1.1.0, built on 2018-11-30_18:09:00_UTC
2018/12/03 14:55:32 [DBG] Loading config file: /var/lib/clr-installer/clr-installer.yaml
2018/12/03 14:55:32 [DBG] PrivateIP: Found IP: 10.54.69.24, Private IP?: true
2018/12/03 14:55:32 [INF] NOTICE: Enabling Telemetry preferred by default on internal networks
2018/12/03 14:55:32 [DBG] localectl list-keymaps --no-pager
2018/12/03 14:55:32 [DBG] timedatectl list-timezones
2018/12/03 14:55:32 [DBG] locale -a
2018/12/03 14:55:32 [DBG] Unable to use language locale 'agr_PE.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'ayc_PE.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'ber_DZ.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'ber_MA.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'bhb_IN.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'hne_IN.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'miq_NI.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'mjw_IN.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'nhn_MX.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'shs_CA.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'the_NP.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'unm_US.UTF-8'
2018/12/03 14:55:32 [DBG] Unable to use language locale 'yuw_PG.UTF-8'
2018/12/03 14:55:32 [DBG] lsblk --exclude 1,2,11 -J -b -O
2018/12/03 14:55:32 [DBG] partprobe /dev/sda
2018/12/03 14:55:32 [DBG] partprobe /dev/sdb
2018/12/03 14:55:32 [DBG] Warning: Not all of the space available to /dev/sdb appears to be used, you can fix the GPT to use all of the space (an extra 13533184 blocks) or continue with the current setting? 
2018/12/03 14:55:32 [DBG] ip route show
2018/12/03 14:55:32 [DBG] ip route show default
2018/12/03 14:55:32 [DBG] ip route show
2018/12/03 14:55:32 [DBG] ip route show default
2018/12/03 14:55:48 [DBG] ip route show
2018/12/03 14:55:48 [DBG] ip route show default
2018/12/03 14:55:48 [DBG] ip route show
2018/12/03 14:55:48 [DBG] ip route show default
2018/12/03 14:56:57 [DBG] ip route show
2018/12/03 14:56:57 [DBG] ip route show default
2018/12/03 14:56:57 [DBG] ip route show
2018/12/03 14:56:57 [DBG] ip route show default
2018/12/03 14:57:15 [DBG] ip route show
2018/12/03 14:57:15 [DBG] ip route show default
2018/12/03 14:57:15 [DBG] ip route show
2018/12/03 14:57:15 [DBG] ip route show default
2018/12/03 14:57:32 [DBG] ip route show
2018/12/03 14:57:32 [DBG] ip route show default
2018/12/03 14:57:32 [DBG] ip route show
2018/12/03 14:57:32 [DBG] ip route show default
2018/12/03 14:57:40 [DBG] ip route show
2018/12/03 14:57:40 [DBG] ip route show default
2018/12/03 14:57:40 [DBG] ip route show
2018/12/03 14:57:40 [DBG] ip route show default
2018/12/03 14:57:47 [INF] Testing connectivity
2018/12/03 14:57:47 [DBG] timeout --kill-after=10s 10s curl --no-sessionid -o /dev/null -s -f https://cdn.download.clearlinux.org/update/
2018/12/03 14:58:56 [INF] Running pre-install hooks
2018/12/03 14:58:56 [DBG] Created Local Telemetry server configuration file "/etc/telemetrics/telemetrics.conf"
2018/12/03 14:58:56 [DBG] telemctl restart
2018/12/03 14:58:57 [INF] Querying Clear Linux version
2018/12/03 14:58:57 [DBG] Clear Linux version: 26630
2018/12/03 14:58:57 [INF] Writing partition table to: sda
2018/12/03 14:58:57 [DBG] parted -s /dev/sda mklabel gpt
2018/12/03 14:58:57 [ERR] 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203
 No makePartCommand() implementation for: 
2018/12/03 14:58:57 [DBG] telem-record-gen --severity 3 --class org.clearlinux/clr-installer/tuipanic --event-id 48d72afc4f3e4823975ab3f52d77e574 --payload version=1.1.0
No makePartCommand() implementation for: 

Error Trace:
storage.(*BlockDevice).WritePartitionTable()
     storage/ops.go:207
controller.Install()
     controller/controller.go:203
```
I noticed that sda contains no longer the partitions I have setup using `cgdisk`

**Comment by mdhorn** [comment]
@mrkz In general, I'd prefer to stick to bug fixes on the TUI and limit the number of enhancements to focus on the GUI. That does not imply there will not be any new features on the TUI, but features like the disk partitioning are something I'd prefer to focus on in the GUI instead.

**Comment by mrkz** [comment]
@mdhorn I agree on focusing on the GUI, however, the [next comment](https://github.com/clearlinux/clr-installer/issues/180#issuecomment-443869075) on this enhancement issue seems to be a bug as I tried the workaround described about using `cgdisk` for partitioning the disk, but when making use of those partitions, the installer crashes, shall I create a separate bug report for this?

**Comment by mdhorn** [comment]
We need to add some better validation to the partitions; this is true for both the configuration YAML files and the TUI. For example, we don't complain if you have the same point mount point twice, but it will cause a crash.

In general, we do not support maintaining an existing disk configuration. If you select a disk for the installation target, all information on that media target will be lost. This is true for both the command line and the TUI.

I'd have to dig into this particular crash, but if you partition disk first with cgdisk, and then assign the partition in the TUI, all of the partition will have new file systems created wiping out any existing content.

**Comment by mrkz** [comment]
@mdhorn thanks for the context, I went ahead and created the issue #182 , screenshot, output and logs available there.

**Comment by mdhorn** [comment]
@mrkz @dorileo 
# Current Implementation
Currently, clr-installer will always rewrite the partition table and recreate all file systems regardless if it was pre-partitioned with another tool or partitioned within the TUI -- All Data will always be lost as it is currently implemented. This is why there is a secondary warning message which states this.

# Proposed Changes
- If the media is pre-partitioned, and the user makes no changes to the partition table, we skip the creation of the partition table.
  - This implies that if a partition is added, delete, auto-partition is used, or a partition is resized all data on the media will be lost.
  - If you want to ensure no data loss on the target media, only seeing the mount points (or labels?) are allowed to be altered in clr-installer.
- If the partition type is not changed, it will not be formatted by default
  - New "Format" option will be added that can be checked (similar to "Encrypt") which will force formatting
  - Enabling encryption on a partition implying formatting and data will be lost

**Comment by dorileo** [comment]
@mdhorn your proposal sounds good and in terms of back end changes I see it's more than half way to full supporting partition management. It also supports sort of "advanced use case".

**Comment by miguelinux** [comment]
I have the same issue here :(,

If you have a defined partition table **clr-installer** drop it.

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
