### ISSUE TITLE
Return to previous menu selection when exiting a submenu

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clr-installer#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
At the top level menu of the TUI for either required or advanced, when I go into a submenu to make changes, have me return to the previous menu item when I exit the submenu.  Right now it goes to the top menu item, at least on the advanced menu.

**Describe alternatives you've considered**

**Additional context**

**Comment by mdhorn** [comment]
For the Text-based installer, this should have been fixed a while ago.
Just testing it, and when you leave the sub-menu to returned to Advanced, the item you were just visiting will be visible on the screen.

For required option, the list always scrolls to any uncompleted item so it is focused on the visible screen.

Pretty sure we have this covered now, but re-open if you disagree.
