### ISSUE TITLE
Booting installer image as VM runs clr-installer on wrong tty

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#192]
**Describe the bug**
Booting the clear-XXXXX-installer.img.xz image using qemu provides a login prompt on ttyS0, but the clr-installer is launched as a service on tty1.

**To Reproduce**
1. Download the clear-XXXXX-installer.img.xz image
`https://download.clearlinux.org/image/clear-27030-installer.img.xz
`
2. uncompress
`unxz clear-27150-installer.img.xz`

3. Download qemu start script
`https://download.clearlinux.org/image/start_qemu.sh`

4. Launch in qemu
`start_qemu.sh clear-27150-installer.img`

5. Login at the prompt

6. ps auxww | grep -i clr-installer
See it running on tty1

**Expected behavior**
The clr-installer service needs to be updated to run on the default console when booting.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 27150
 - Installer Version 1.1.2 
 - Platform: virtual environment, or a system where the serial console is the default

**Comment by bryteise** [comment]
While running on the default console is fine, it would be nice if it could run on both the stty and tty as changing the kernel commandline is a bit annoying. Maybe just another service file to run the second clr-installer instance?

**Comment by gvancuts** [comment]
As I understand it, it's not even running on the default console, it's hard-coded to `tty1` in the service file - see https://github.com/clearlinux/clr-installer/blob/73d802d692f03985d0118fcbf3dc5cb16c28b156/etc/systemd/clr-installer.service#L13

I'm not even sure in this case that changing the `console` statement in the kernel command-line would make any difference.

Has anyone ever successfully run the installer over a serial port? I tried for quite some time with the previous installer we had but could never get it to work. I stopped trying at some point since I knew this new one was coming soon.

**Comment by mdhorn** [comment]
Correct, as noted in the original description for the Issue it only runs on tty1 as listed in the systemd service file.

A few people have started to look at this, but for the next several weeks, this is not on the priority list for the installer team.

This is open source, so we are open to anyone who has a background in systemd and wants to submit a PR with a fix.

**Comment by gvancuts** [comment]
For what it's worth, I've not been able to make it run even when hard-coding `TTYPath=ttyS0` (the serial port of my system. I have played with various other parameters that are related (such as `TTYReset` and `TTYVHangup`) but I've never seen the installer come up over the serial port. Do we have any evidence that it can work? I'm actually wondering whether the real problem isn't that it does not even run correctly over a serial line. If true, fixing the service file won't help much.

I did try to turn on additional debugging (using `-l 4`) but that did not give any real clue as to what's happening. I do see that it's probing the storage devices and then doing some stuff with the network but that's where it stops (and my `minicom` screen only shows some of the kernel messages).

**Comment by mdhorn** [comment]
@gvancuts I'd start with can you get getty running on the ttyS0? If you can log in on that serial port, test running the installer from directly -- should work.

**Comment by gvancuts** [comment]
I can see it when I start it from there. It's hard to navigate but it's there! OK so now we need to understand why it's not doing it from the systemd service file... I'll poke at that some more.

**Comment by mdhorn** [comment]
We have depreciated running the installer on-boot as of the 2.0.0 release in favor of live ISO images where the user can then launch the installer on demand.
For the text-based installer in the liver-server ISO the /etc/issue provides guidance about configuring the network first and how to launch the installer.
This should be visible on all tty which run getty.
