### ISSUE TITLE
privacy issue

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/clr-installer#199]
I noticed telemetry data clr-installer/success with payload containing:
<pre>
...
bundles: [bootloader, clr-installer, desktop-autostart, editors, network-basic, openssh-server,
  os-core, os-core-update, sysadmin-basic]
telemetry: false
...
</pre>

So clearly the user installed the CLR OS without telemetry (note the telemetry bundle is missing). The installer created the telemetry payload at install time anyway, even though the telemetry was not enabled (telemetry.go):

<pre>
CopyTelemetryRecords copies the local spooled telemetry records
// to the target system. If records could not be sent or telemetry
// was disable, place the unpublished records on the target system
</pre>

Sometimes later on the telemetry was enabled by the user and the payload was eventually sent to the backend. However, reporting any data gathered during the time when telemetry was not enabled could be viewed as a privacy violation issue.

**Comment by mdhorn** [comment]
This was a result of the telemetry package changing it's default behavior from requiring opt-in after installing the package, to automatically opting-in when it is installed. 
We have since made changes to the installed to no longer rely on the operation philosophy of the telemetry package.
