### ISSUE TITLE
Clean-out efivars with user consent

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/clr-installer#201]
This is a suggested solution for issue #174. It has been observed that certain efivars can prevent ClearLinux to boot correctly after being installed using clr-installer. E.g. The system would boot into the EFI shell instead of the new ClearLinux installation. Manually cleaning out the efivars seems to solve this issue.

**Suggested solution:**
During installation, prompt the user for consent to clean-out the efivars. If the user agrees, clean out the efivars before running `clr-boot-manager update`. It is important to get the user's consent especially if the system has multiple OSs' installed.

**Comment by mdhorn** [comment]
Clear efivars seems like a larger response to an unclear problem.
I think first we need to ensure that clr-boot-manager update is creating an EFI entry for ClearLinux and making it the first in the boot order -- if that is not happening, debug why or have a retry.
But clearing efivars seems like a last resort effort, and only something that can be tried in Interactive installations.

**Comment by reaganlo** [comment]
As discussed, this does not seem to be a desired solution for issue #174. Hence closing it.
