### ISSUE TITLE
Use LTS Kernel when installing in VirtualBox

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#203]
When installing Clear Linux OS in VirtualBox, the installer should recognize this installation environment and automatically select the LTS kernel for the install.

**Comment by mdhorn** [comment]
@fenrus75 Should we also be defaulting to the LTS kernel for Parallels and VMware environment too?

The current PR is only changing the default kernel from Native to LTS for interactive installs.

**Comment by fenrus75** [comment]
nope; the virtual box is special in that we only support their drivers in
the LTS kernel package .... parallels/vmware are not like that
