### ISSUE TITLE
Allow interactive install without swap partition

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#205]
Some user may wish to use swap files instead of a swap partition. The current installer requires a swap partition.

**Comment by mdhorn** [comment]
The scope of this change will be to always create a minimum size swap file and not create a swap partition when installing with the interactive installer.

This will require coordinating many online documentation changes.

**Comment by mvincerx** [comment]
Yeah. We should meet to discuss this change, depending on how soon you plan to release it.

**Comment by mdhorn** [comment]
> The scope of this change will be to always create a minimum size swap file and not create a swap partition when installing with the interactive installer.
> 
> This will require coordinating many online documentation changes.

One implication of switching to this method of a swap file is the need to add the swap file to /etc/fstab. This means if the administrator later preforms a "stateless reset", the system would reboot without any swap as the /etc/fstab would be removed.
This is not a problem with a swap partition as we set the appropriate GUID and systemd finds the swap partition on boot.

Should be low risk, but @bryteise @fenrus75 are we okay with this?

**Comment by ahkok** [comment]
Make a swap unit instead, and drop it in /etc/systemd/system, and symlink it appropriately so it gets mounted by sysinit.target.wants.

https://www.freedesktop.org/software/systemd/man/systemd.swap.html

We could, and this is likely very interesting for upstream (acceptable) create a swap generator that creates virtual swap mount units for swap files in a certain location. This would remove the statelessness problem from the equation.

**Comment by mdhorn** [comment]
Fixed in installer release [2.5.0](https://github.com/clearlinux/clr-installer/releases/tag/2.5.0) found in Clear Linux OS release 32980 or greater.
