### ISSUE TITLE
Add a fast install option for the mass installer

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-installer#215]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
When users supply the fast install option, relocate the swupd state directory to be inside the loopback device, and then just after install finishes, remove the state directory.  This avoids a copy of swupd's state directory across a block device boundary and improves install times, at the expense of the user needing to double their disk space requirements.

**Describe alternatives you've considered**
N/A, this feature is present with ister.py with the --fast-install option

**Additional context**
Gives users the same performance of creating a chroot themselves with swupd verify --install

**Comment by dorileo** [comment]
By default clr-installer will place the swupd state inside the target system unless instructed with ```--swupd-state```. I think what we really need here is some sort of ```--swupd-clean``` meaning cleanup swupd state-dir after finishing.
