### ISSUE TITLE
Consider to have a color blindness mode for all visual interfaces.

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/clr-installer#217]
Some users are finding very difficult to use clr-installer due the lack of a color blindness mode.

**Comment by mdhorn** [comment]
Can you quantify this?  As it will impact the amount of effort and possible timeline.

**Comment by mbelluzzo** [comment]
I can be quantified. Not sure that by me :-)

**Comment by mbelluzzo** [comment]
Farther I can go to "quantify": About 8% of men and 0.5% of women suffer from color-vision deficiency.

**Comment by mdhorn** [comment]
@mattcurfman This is already being tracked.

**Comment by mattcurf** [comment]
Thanks @mdhorn.  I basically can't use the installer at all in its current form; have to ask people to come to my desk to see which button has focus or squint super close to screen :( recommend using a non-color cue to indicate focus, like '[' ']' brackets around item of focus.

**Comment by mdhorn** [comment]
Fixed in release [2.4.0](https://github.com/clearlinux/clr-installer/releases/tag/2.4.0)

**Comment by mdhorn** [comment]
Released in Clear Linux OS 32380
