### ISSUE TITLE
Feedback on the TUI installer

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clr-installer#218]
**Is your feature request related to a problem? Please describe.**
The TUI installer has an unintuitive navigation and feedback, in my opinion. As an experienced user, I was unable to install CL without having to look up documentation on how the installer works.

**Describe the solution you'd like**
Each screen should be very clear on the available options, their meaning, and which are dependencies. If something is a blocker, it should be made clear why and what the user needs to do.

**Describe alternatives you've considered**
Using an older CL version that is not based on the clr-installer however this is not a sustainable solution with clr-installer being included in the newest builds.  

**Additional context**

Below is  feedback on how improvements could be made.

1.  Add a note saying that the "Install" button is unavailable until required sections are completed. Add an indicator to which sections are pending user-input/unfulfilled.

2. On the "Select Timezone" screen, add the timezone offsets from UTC ( https://en.wikipedia.org/wiki/List_of_UTC_time_offsets ). I tend to first glance a timezone screen for my particular offset to get my eyes in the right area before looking at the names in depth.  

3. On the "Configure Media" screen, make it clear that the user needs to press Space/Enter to choose a device and then select autoparitioning or manually partition. Right now the screen is extremely unintuitive and I got lost even as an experienced user.
   - If I change the filesystem from ext4 to btrfs, it does not let me continue/Confirm and also gives me no feedback as to why. If I select Autopartiton, then change to btrfs it works. 
   - It would be nice to show a summary of changes that will be written to disk on this screen, not just the home screen.
   - After Autopartition has been selected, you can no longer "add partition" until you Revert. It is unclear why. 

4. On the "Add Partition" screen, the Size field should specify the available formats otherwise I'm typing in a number and don't know what units. Or when I hit +/= to autosize it calculates and autofills a small unit which is not intuitive. 

5. On "Proxy" screen, there should be a note specifying what formats are supported and how to add a username:password if necessary for the proxy. For example, I was unsure if I needed `http://` or not.

6. On the "User Manager" screen, make it clear that the user needs to press Space/Enter to select an option such as "Administrative"
   - Add a note above what "Administrative" actually does. 

7. Having to scroll through all the screen options to get to the main options at the bottom (Cancel, Confirm, etc) is unintiutive, especially on screens with many options such as Bundle Selection screen . I would like the ability to shortcut out of wherever my cursor is to these button somehow. For example, hitting Esc on my keyboard. 

8. During the installation progress, add a note saying the Reboot button will become available after the installation is complete. It looks like it is waiting for me to hit the "Reboot" button when I really need to wait for the installer to finish.

**Comment by mdhorn** [comment]
Thanks for the feedback.
These types of changes are more likely to be a part of the Graphical version of the installer to be released in the future. The text-based user interface has limited screen space which makes it difficult to implement "notes".

**Comment by puneetse** [comment]
> These types of changes are more likely to be a part of the Graphical version of the installer to be released in the future. The text-based user interface has limited screen space which makes it difficult to implement "notes".

Fair enough, however considering the tough time I had I would ask not deferring all of these for the GUI installer.

**Comment by mdhorn** [comment]
@puneetse  I believe we've addressed a lot of these issues, both in the older test-based installer but even more so in the new graphical installer.  
https://clearlinux.org/downloads

I've created a new issue for the [Timezone Offset]( https://github.com/clearlinux/clr-installer/issues/408) which we know was not implemented yet.

If you do discover more issues for which there is not already a GitHub Issue, please try to submit them separately or functionally grouped to the same screen for better tracking.

thank you.
