### ISSUE TITLE
Create new Installer Bundle

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#22]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mdhorn](https://github.com/mdhorn)**
_Thursday May 24, 2018 at 21:26 GMT_

----

Create and release a new bundle for the new clr-installer

Ensure this bundle includes the necessary packages for languages and keyboard layouts.

**Comment by dorileo** [comment]
I'm wondering if we really need to create a new bundle or if we could simply keep using the current installer bundle. @bryteise what do you think?

**Comment by mdhorn** [comment]
Bundle name: clr-installer
This bundle will co-exist in parallel with os-installer until we are ready to publish external images generated by the new clr-installer.
Done and available for use in new releases.
