### ISSUE TITLE
User Manager options should be under Required, not Advanced

### ISSUE THREAD

**Issue by danboid** [clearlinux/clr-installer#223]
After several false starts, the causes of which I shall cover in a separate bug report, I was able to install Clear Linux from the latest/current live desktop install image, installer v1.1.5. I had provided all of the info requested by the installer in the 'Required' column so I presumed it was going to ask me to create a user and set a password on the first boot. Surely it wouldn't let me install the OS without setting up any users? But it does!

Yes, It is currently possible to install Clear Linux and be told installation was successful only to reboot into an OS you are unable to log into so there needs to be a check added to the installer for a user having been created before the installation can begin and the user management section should be moved to the required column.

**Comment by mdhorn** [comment]
@danboid This is a reasonable request for the Desktop version.
For a text-only/console environment, which previously was the primary use case, there was generally on users added.
The root user is always defined, but we do not allow root to login to the graphical environment by default. It is possible to switch to a console login and set the root password, and then create an account post-install if adding a user account is missed initially.

But yes, this would be a good ad to require a user account in the desktop environment.
There are many changes for the desktop installation environment in the works; we will add this one.

**Comment by danboid** [comment]
Thanks Mark!

**Comment by mvincerx** [comment]
@mdhorn, I completely agree with moving User Manager to `Required options`. 

A while back, I revised the live-desktop-install-beta, adding `[Recommended options](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install#recommended-options)`  to encourage users to assign an admin user with which they can log into the GUI, after installation. In short, I think the fact that I had to create this section, for clarity, makes a strong case for moving User Manager to `Required options.`

I'd also like some guidance on whether the docs should address switching to root and resetting the password. (For a short time, the docs reflected that use case, but it's no longer valid.) I'm curious whether you think this ought to be addressed, given the fact that our docs must address both beginning and advanced users. (An advanced user would likely gloss over this if it were added.)

**Comment by mdhorn** [comment]
@danboid @mvincerx  In theory, if no user account is created, the "gnome-initial-setup" should run at startup and prompt the user to create an account.
But I still think, for the Desktop case only, we should request that a user account is created for the desktop install.

@mvincerx No documentation changes yet. We will want to update the docs once we require a user in the desktop environment. We will need to figure out how to share documentation steps between desktop (GUI) and non-desktop (TUI) environments.

**Comment by mdhorn** [comment]
@danboid I did just confirm that on a laptop which [passes the clear linux compatibility check](https://download.clearlinux.org/current/clear-linux-check-config.sh) when no user is defined, gnome-initial-setup launch on boot and walk me through adding a user.

An older laptop which is only 95% compliant (not AES support) launch the desktop, but the "gnome-initial-setup" crashed due to lack of AES support.

But we should still require a user be defined when installing in a desktop environment.

**Comment by mvincerx** [comment]
@mdhorn, Sounds good. Please keep me posted. OK, we'll figure out a solution to differentiate. 
Right now (for others who may not be familiar), the body content is the same in the [bare metal installatio](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install) and the [live desktop beta installation](https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-beta). And, my Recommended options asks users to create a user with admin rights (so as to avoid the `gnome-initial-setup`).

**Comment by mdhorn** [comment]
Adding a user has been in the graphical installer as of its initial release (2.0.0).

We are tracking adding the user management interface for the GUI  as #394
