### ISSUE TITLE
Add --swupd-cert command line option

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-installer#228]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a --swupd-cert command line option for clr-installer that passes through a value to --certpath of swupd.  This allows the user to define an alternative certificate to use for validating manifests.

**Describe alternatives you've considered**
No alternatives exist

**Additional context**
This is needed when a user wants to create an image from their own mix.  Blocks #59.

**Comment by mdhorn** [comment]
Began to implement this change, but failed during validation due to a swupd-client bug
https://github.com/clearlinux/swupd-client/issues/924
