### ISSUE TITLE
Add clear-linux-check-config.sh to test HW compatibility with CL

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/clr-installer#232]
**Is your feature request related to a problem? Please describe.**
Some CPUs do not support specific instruction sets, for example an IVB CPU that does not support AES, even though this CPU falls under the umbrella of supported CPUs.  CL will install but applications will fail that need AES functionality.  See https://github.com/clearlinux/distribution/issues/471 for a specific example.

**Describe the solution you'd like**
Add this check to the installer as an option to run the HW check prior to doing an install

**Describe alternatives you've considered**
Add the shell script that checks HW compatibility to the desktop as an item that can be run by the user before running the TUI installer.

**Additional context**

**Comment by ahkok** [comment]
I'd rather have the installer actually test whether the CPU is compatible by checking for the required instruction sets, and fail if it isn't. Not having AES will lead to very subtle and difficult to debug problems, as you have seen.

**Comment by mdhorn** [comment]
The system check was added to both the ISO as a pre-boot check as well as integrated as a pre-check in both user interfaces.
Additionally, one change run the pre-check manually by using the `--system-check` flag.

Note: The AES requirement was removed from Clear Linux in Late 2019 and removed from the installer with PR #500
