### ISSUE TITLE
Copy installer's /etc and some others to destination system

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/clr-installer#233]
**Is your feature request related to a problem? Please describe.**
If you configure WiFi or some wired network configuration in the installer, after rebooting you need to configure again.

**Describe the solution you'd like**
Please copy the installer system's configuration from /etc and elsewhere where applicable to the destination system post-installation. That should persist any configuration made by the user.

If the user created any users in the system, /home should also be copied.

**Describe alternatives you've considered**
Configuring things twice. That's bad for UX.

**Comment by mdhorn** [comment]
All network settings are now copied as of the 2.0.5 release.
