### ISSUE TITLE
Please add support for offline installation

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/clr-installer#234]
**Is your feature request related to a problem? Please describe.**
Sometimes, one doesn't have network access on the machine Clear is being installed on. Being able to perform an offline installation, even if partial, would be very welcome.

**Describe the solution you'd like**
Add a way to install Clear onto the new machine without requiring Internet access. Suggestion: simply copy the installer system's /usr to the destination, then use swupd to remove the installer bundle and add the rest.

An added bonus for the graphical installer is that it would skip the need to download the entire desktop again. Only the deltas from the installer's set up to the current Clear would be necessary (plus of course any bundles the user chose to add during installation).

See also #233, which would argue for copying the whole installer to the new partitions.

**Describe alternatives you've considered**
Having network access.

**Additional context**

**Comment by ajipw** [comment]
Yes, please provide an offline installation, my internet connection is slow. I think downloading an ISO of 2.17GB is useless because it has to be downloaded again when installing (with the same size)

**Comment by BruceCherniak** [comment]
Offline Installation is **CRITICAL**, not just *nice to have* !!!

I envision an entire corporate market behind firewalls/proxies that make the current install difficult/impossible.  Our current wired network is locked down with 802.1x, preventing initial install.  Once installed there are methods to add the device to the network, but in its current state Clear Linux is completely unusable because it will not install without an open network.

I repeat, **in its current state, Clear Linux is completely unusable**

The live ISO *should* contain everything necessary for the base install.  After the initial install and network configuration, then it can check for updates.  Easy.  Every major linux distro provides this ability.

Why make this so *unnecessarily* difficult?!

**Comment by mdhorn** [comment]
Thanks for your feedback.

We have a backlog of items to work on, and currently, the offline install is not at the top of our list.

This is an open source project, and we are happy to allocate time to reviewing pull request submissions.

**Comment by BruceCherniak** [comment]
Hi Mark, thanks for your quick response.  I'm happy to lend a hand.  But, the first thing I notice about building the installer is the CLR-INSTALLER dependency (``swupd bundle-add clr-installer``).  Chicken, meet egg.  :-)

**Comment by Luraktinus** [comment]
I really need an offline install too, would be cool to be able to download bundles/packs and import them too, i have customers without internet and i would like to provide them with software and updates by giving them a USB drive

**Comment by jwakre** [comment]
> I really need an offline install too, would be cool to be able to download bundles/packs and import them too, i have customers without internet and i would like to provide them with software and updates by giving them a USB drive/DVD

I am currently working on adding support for an offline installer, but an internet connection will be required for swupd to get future updates. An issue could be filed at https://github.com/clearlinux/swupd-client to request offline update support.

> 
> see Debian for example...

**Comment by otaviobp** [comment]
> I really need an offline install too, would be cool to be able to download bundles/packs and import them too, i have customers without internet and i would like to provide them with software and updates by giving them a USB drive/DVD

We have a tool that addresses the problem you described. If you want to support multiple clients with a selection of the Clear Linux bundles you can create a mix using the mixer tool (https://github.com/clearlinux/mixer-tools/). Take a look at the manual: https://docs.01.org/clearlinux/latest/guides/clear/mixer.html

The example uses a web server to provide updates, but you can copy everything to a storage device and use file:// as the update url.

**Comment by jwakre** [comment]
As of version 31230 the live desktop and server installer images have support for offline installs. Installer images can be downloaded at https://clearlinux.org/downloads

**Comment by BruceCherniak** [comment]
Thank you!  This will be a big help!
Bruce

**Comment by GabeAl** [comment]
Any updates on this? Still doesn't work without lengthy and hacky workarounds, and is actually NOT supported by either the graphical installer OR the non-graphical installer on the latest release (43320)
