### ISSUE TITLE
Partition Ordering

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#237]
**Describe the bug**
The partition table is created incorrectly if the partitions are not in sorted order.

**To Reproduce**
1. Take the released scripts/installer.yaml file and change the order of the partition; move p3 to the first child position
2. Attempt to build image
3. Image build fails due to lack of disk space.  The root partition was placed in the wrong location and is the size of the swap.

**Expected behavior**
The image is built correctly with the request partition table.

**Environment (please complete the following information):**
 - Clear Linux OS Version: Installed version: 27800
 - Installer Version 1.1.5

**Comment by mdhorn** [comment]
The code is making the assumption that the partitions are in order of the partition table.
Need to either sort them to ensure this or modify the code to remove the dependency.
`func (bd *BlockDevice) WritePartitionTable(legacyBios bool) error {`

**Comment by mdhorn** [comment]
@reaganlo We are seeing this bug show up when using the JSON -> YAML converter functionality; 50% of the time converting the same JSON file results in a YAML file with the partitions not in ascending order.

**Comment by reaganlo** [comment]
@mdhorn Yes Mark. That is correct. This was discovered during the json to yaml feature implementation. At that point we decided that the correct fix would be to make the installer smart to read the yaml tags and understand the type of partition during installation and not go by the sequence in which they appear in the config file.

Is there a different action item now?

**Comment by mdhorn** [comment]
@reaganlo This is just bubbling up in importance due to the increased usage of the clr-installer using JSON from ister.

**Comment by reaganlo** [comment]
Fixed and merged to master.

**Comment by mdhorn** [comment]
Fixed in release 2.1.1  which should land in Clear Linux* OS release > 30610
