### ISSUE TITLE
Enable use of all media as install targets on desktop

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#238]
**Is your feature request related to a problem? Please describe.**
Currently, when booting into the Clear Linux OS Desktop, automounting of media is enabled. The Installer will not allow the use of mounted media.

**Describe the solution you'd like**
Disable the automounting setting for all media in installer desktop images.

**Describe alternatives you've considered**
Having the user manually unmount media and select rescan media before selecting target install media.

**Comment by IgorDouven** [comment]
This made me think that perhaps the problem reported in #231 had to do with the fact that the ssd contained an arch installation. So I removed that -- using `sgdisk -Z /dev/nvme0n1` -- hoping that then the installer would find the ssd. No luck, however. Any suggestion about what else I could try is greatly appreciated. I'd really like to install Clear on my main machine.

**Comment by mdhorn** [comment]
> This made me think that perhaps the problem reported in #231 had to do with the fact that the ssd contained an arch installation. So I removed that -- using `sgdisk -Z /dev/nvme0n1` -- hoping that then the installer would find the ssd. No luck, however. Any suggestion about what else I could try is greatly appreciated. I'd really like to install Clear on my main machine.

I think your issue is more likely related to this:
https://github.com/clearlinux/distribution/issues/392#

If the OS does not see the drive, the Installer won't be able to use it.

**Comment by mdhorn** [comment]
Disabling of auto-mounting of media was added to the graphical installer 2.0.0 in the new live-desktop ISO.
