### ISSUE TITLE
Run clr-installer on serial console in Clear Linux installation images

### ISSUE THREAD

**Issue by bryteise** [clearlinux/clr-installer#239]
**Is your feature request related to a problem? Please describe.**
Clear Linux installation image doesn't start the tui on the serial console.

**Describe the solution you'd like**
Installer should run on serial and console tty if devices are available.

**Describe alternatives you've considered**
Manually start clr-installer on stty console

**Additional context**
Other distributions provide installer on stty.

**Comment by mdhorn** [comment]
@bryteise We are already tracking this as #192

If you check, it is running, just on tty1 as the service file specifies.

**Comment by bryteise** [comment]
Ah yes, I'll post comments there.
