### ISSUE TITLE
TUI: Advanced options/Bundle Selection should show selected bundles

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clr-installer#242]
Problem:
As of clear-27150-installer.img, in `Advanced options/Bundle Selection`, the TUI installer does not show the specific bundles the user selects after the user selects them. This is inconsistent with other submenus that do show configuration values after the user selects them (e.g., Proxy, User Manager, etc.) prior to installation.

Proposed solution:
In `Advanced options/Bundle Selection`, the submenu should show which bundles were selected for installation after the user has selected and confirmed them in the Bundle Selection submenu.

**Comment by mdhorn** [comment]
@mvincerx We only allocate a single line to show the selected data on the main menu, so yes, you will never see the complete list of bundles if it is more than 65 or so characters long. 

There are no plans to change this in the near future.

All effort is focused on the graphical (GUI) installer for the desktop environment and rather than changes the visual aspects of the TUI.

**Comment by mdhorn** [comment]
@mvincerx Okay, I understand your concern now. The user selected bundles are in the list but added to the end so you do not see them on the single line. We can most the user selected to the front of the list so that those are more likely to be visible.

**Comment by mvincerx** [comment]
Yes, moving the user-selected bundles to the start of the list will provide confirmation to the user. Thank you. Thanks. This gives users confidence the installation incorporates the bundles that they selected. 

Also, my colleague just pointed out: From the Advanced Options>Bundle Selection (screenshot 2), the *bundles shown in the horizontal list* don't reflect the same bundles shown in the **Bundle Selection submenu**. For example, `openssh-server` appears in Advanced>Bundle Selection, but it doesn't appear in the Bundle Selection submenu. I think bundles shown in the Advanced>Bundle Selection should match those bundles shown in **Bundle Selection submenu**.  IMHO: If only the first 3-5 bundles fit in Advanced>Bundle Selection, that's OK.

**Comment by mvincerx** [comment]
+1 @intelkevinputnam

**Comment by mdhorn** [comment]
Fixed in 1.1.7

**Comment by mvincerx** [comment]
@mdhorn. Thanks for all your work on this. Do you know in which release this bundle feature will be evident?  I tested `clear-28100-live-desktop-beta` by selecting and confirming bundles. However, the same behavior occurs as before GH-248.

**Comment by mdhorn** [comment]
@mvincerx This first build tag using clr-installer 1.1.7 is 28200

**Comment by mvincerx** [comment]
@mdhorn. Thanks for the update.
