### ISSUE TITLE
Support the partition size defined as "rest" to use up the disk

### ISSUE THREAD

**Issue by qzheng527** [clearlinux/clr-installer#243]
**Is your feature request related to a problem? Please describe.**
On ister json file, we can define the partition size as "rest" to use up the disk.
But looks the clr-installer yaml couldn't support the "rest".
How can we use the yaml config file to install the clear to /dev/sda ?
 (using up the disk, not through the TUI)

**Describe the solution you'd like**
Support "rest" as partition size parameter.

**Describe alternatives you've considered**

**Additional context**

**Comment by mdhorn** [comment]
@qzheng527 Setting the size of the last partition to '0' in clr-installer YAML will cause the partitioner to use the rest of the remaining space. This is a recent feature add in clr-installer version 1.1.6 and available in Clear Linux OS as of release 28070.
