### ISSUE TITLE
installer image build failure

### ISSUE THREAD

**Issue by bdphipps** [clearlinux/clr-installer#249]
Installing the base system
ERROR: Installation has failed!
Please report this crash using GitHub Issues:
	https://github.com/clearlinux/clr-installer/issues

Include the following as attachments to enable diagnosis:
	/home/logs/clr-installer/pre-install-clr-installer.yaml
	/home/logs/clr-installer/clr-installer-28160-installer-1551819232.log

If the problem persists, enabling additional logging will be helpful in
diagnosing the issue. At the OS Boot screen, hit 'e' to edit the kernel
command line. Add the following to the end of the line:
	clri.loglevel=4

panic: exit status 127

Error Trace:
errors.Wrap()
     .gopath/src/github.com/clearlinux/errors.go:91
swupd.(*SoftwareUpdater).DisableUpdate()
     .gopath/src/github.com/clearlinux/swupd.go:204

goroutine 10 [running]:
main.fatal(0x92a040, 0xc0002f2280)
	/home/clrbuilder/projects/clr-installer/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:43 +0x56
main.main.func4(0xc0001630e0, 0xc000136600, 0xc000242020, 0x16, 0xc000345d45, 0xc000117b50, 0xc00002e150)
	/home/clrbuilder/projects/clr-installer/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:259 +0x3b6
created by main.main
	/home/clrbuilder/projects/clr-installer/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:237 +0x929

[clr-installer-28160-installer-1551819232.log](https://github.com/clearlinux/clr-installer/files/2933640/clr-installer-28160-installer-1551819232.log)
[pre-install-clr-installer.txt](https://github.com/clearlinux/clr-installer/files/2933641/pre-install-clr-installer.txt)

**Comment by gtkramer** [comment]
This issue only happens when the systemd on the host is a different version than the systemd on the target.

**Comment by mdhorn** [comment]
Fixed in 1.1.7
