### ISSUE TITLE
Clear Linux OS Installer 1.1.6 UI improvements

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/clr-installer#254]
**Is your feature request related to a problem? Please describe.**
Testing the ClearLinux installer 1.1.6 I notice some UI improvements potential

**Describe the solution you'd like**
-installer text fonts are really big => consequence all below buttons and/or options might not be seen on a small monitor (especially in virtual env like virtualbox, kvm.. where no fancy big monitor emulation available)
-keyboard navigation is not intuitive, eg: in "Select desired kernel" we can browse through choices, but we can not automatically confirm the current choice with "ENTER", we must cycle through the end of browse list, skip cancel and select confirm, which is boring
-page-up page-down *seems* to not work, eg: when selecting time zone:
the focus is on Confirm, so we cannot use page-up page-down right now,
we must first go up/down to loose Confirm focus to the list, then page-up page-down (and also up and down) work, but then we cannot validate with Enter ! (because now we must cycle again to Confirm which is tedious) 
-In the particular VirtualBox case, using the image "clear-XXX-live-desktop-beta.img", it seems like we cannot install using the Clear Linux Installer (1.1.6) because we have the message : "No Usable Media Detected",
but maybe it might be expected due to running an "already installed" image ?
In this case, it's too bad there is the installer icon in Favorite, plus the fact we cannot run the installer to personalize (finalize ?) installation by setting the hostname, proxy, etc...

**Describe alternatives you've considered**
-for the big font size => maybe a simple "text" installer option would be good, that would use the standard Terminal console font
-for the cycle-through-to-Confirm => it would be nice to make Confirm (and Cancel) have some sort of permanent pre-focus, which would allow one to select through the list and directly validate the current choice with enter
To navigate between the focus-keeping button list (Cancel, Confirm) and the selection list, one would use Tab/Shift-Tab
This way we can have several "focuses" at the same time (focus of the button list, focus within the selection list, etc...)

**Additional context**
Running this image :
https://download.clearlinux.org/image/clear-28100-live-desktop-beta.img.xz
Within VirtualBox in Windows

**Comment by puneetse** [comment]
Putting this reference here for association https://github.com/clearlinux/clr-installer/issues/218

**Comment by mdhorn** [comment]
Thank you for your feedback.

@nsauzede I believe we've addressed a lot of these issues, both in the older test-based installer but even more so in the new graphical installer. When you have a chance, you should give the new live desktop (or server) ISO image a test drive.
https://clearlinux.org/downloads

The new ISO images should also enable booting in VirtualBox, I boot them without issue under MacOS VirtualBox.
