### ISSUE TITLE
Chroot when disabling swupd autoupdate

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-installer#255]
**Describe the bug**
When the host OS has a different version of systemd than the installed OS of the image, swupd autoupdate does not disable successfully.  The command `systemctl --root` tries to resolve libsystemd on the host OS rather than in the installed OS.  The end result is `libsystemd-shared-241.so: cannot open shared object file: No such file or directory`.  The issue is a little more nuanced because chrooting the command in swupd/swupd.go in the DisableUpdate function returns an exit code of 1, even though the command executed as expected and did indeed disable swupd autoupdate.  This is because systemd isn't booted, but a check exists in systemctl for this.

**To Reproduce**
1. Have host OS of Clear Linux 28020 (systemd 239)
2. Attempt to create an image with an OS containing Clear Linux 28140 or later (systemd 241)
3. See the above message in the log.

**Expected behavior**
When host and installed OSes differ, this command should always work and swupd autoupdate should be disabled successfully.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28020
 - Installer Version: 1.1.6
 - Platform: Dell R640

**Additional context**
N/A

**Comment by mdhorn** [comment]
Fixed in 1.1.17
