### ISSUE TITLE
RFE: brief comments and observations on current 'massinstall' feature-set 

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/clr-installer#260]
Hi all!

having spending the weekend playing with `clr-installer`, here's a quick list of observations / suggestions:

On features: 
- when using `massinstall` mode there should be a way to set, or override whatever is set in the config file,  the ClearLinux `version` to be installed on the media from the cli, along to what `-b`/`--block-device` already does for the target media.
- actually it wouldn't hurt to refactor things so that it would be possible to generally pass/override arbitrary **_env:_** tuples from the cli (and turn into `block-device` and `clear-version` special cases of it) - say like `docker run` allows. 
- at least when generating file images copying whatever is the network config of the host generating the media seems sub-optimal at best. IMHO this should be a flagable feature (say `copyNetworkConfig)` that at the very least when the media is a file should be set to `false` by default.

On cosmetics/defaults:
- the `LegacyBios` option in the yaml should probably be, for consistency with everything else there, be called `legacyBios`
- the default user name `clrlinux` presented in the examples is IMHO too "cold". `clear` would be a more _bonding_ choice to the end-user. 
- currently the `pre-install` hooks are run before the target media is even created... shouldn't they be run after the media is created/formatted and fs done but before the actual OS installation starts, or at least  have a flag to allow that ? 

And that's it :-) 

Finally, **Congrats** for the **awesome** work! 

António

**Comment by mdhorn** [comment]
@AntonioMeireles Thank you for the feedback.

I agree with the environment variable suggestions. Personally, I always like to see in order of precedence:  First: built-in defaults, configuration file values, environment variables, command line arguments, and finally interactive user enter data.
We should look at all of the configuration file options and review which ones make sense to have command line overrides; and considers adding environment variable overrides.

The copying of network configurations by default is a newly introduced bug; see #261 
We will work on a fix for this asap.

Yes, `LegacyBios` should be changed to `legacyBios` for consistency, but since it was already in use we might have to support both moving forward but document the correct case.

We will have to think about the pre-install hook changes.
After the file systems are created, installing the OS on `/` is done with `swupd verify --fix` which would likely wipe out any changes done to `/`.

**Comment by mdhorn** [comment]
@AntonioMeireles BTW, other than the bug, the other items will likely get address, but the core installer team right now is focused on the creataiton of a graphical interface for the clr-installer. We maybe not start on this for a month or two.

But as this is open source, we welcome pull requests for such changes!

**Comment by mdhorn** [comment]
@AntonioMeireles Just verified the legacyBios is camelcase; maybe you saw a LegacyBios in one of the test JSON file which is for the old ister.py tool?

**Comment by AntonioMeireles** [comment]
> @AntonioMeireles Just verified the legacyBios is camelcase; maybe you saw a LegacyBios in one of the test JSON file which is for the old ister.py tool?

FWIW, @mdhorn hadn't tried to generate images with `legacyBios` yet with the new installer (only need those for some openstack loads and for that still relying in ister for now) nor had looked at the source... i've based my comments in what was stated in the official docs [here](https://github.com/clearlinux/clr-installer/blob/master/scripts/InstallerYAMLSyntax.md#installation-options) where it's referenced with capital `L` (so that page needs a one byte fix :-) ).

All the best!

**Comment by mdhorn** [comment]
> > @AntonioMeireles Just verified the legacyBios is camelcase; maybe you saw a LegacyBios in one of the test JSON file which is for the old ister.py tool?
> 
> FWIW, @mdhorn hadn't tried to generate images with `legacyBios` yet with the new installer (only need those for some openstack loads and for that still relying in ister for now) nor had looked at the source... i've based my comments in what was stated in the official docs [here](https://github.com/clearlinux/clr-installer/blob/master/scripts/InstallerYAMLSyntax.md#installation-options) where it's referenced with capital `L` (so that page needs a one byte fix :-) ).
> 
> All the best!

Okay yes, the documentation is incorrect. I'll get that fixed.  

Thank you!

**Comment by mdhorn** [comment]
A majority of these have been updated or implemented over the course of the last year.
Going to close this list of items for now.

If there are still important outstanding issues you think are missing, please open new GitHub Issues; preferable one item per Issue unless they are highly related/integrated.

Thanks for your feedback.
