### ISSUE TITLE
Running clr-installer on Fedora 29 produces 'panic: Invalid Language 'en_US.UTF-8''

### ISSUE THREAD

**Issue by gblewis1** [clearlinux/clr-installer#267]
Running clr-installer on Fedora 29 produces 'panic: Invalid Language 'en_US.UTF-8''

Rest of error message:
```goroutine 1 [running]:
main.fatal(0x79a660, 0xc4201fc2a0)
	[...]/packer-templates-clear/clr-installer/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:44 +0x56
main.main()
	[...]/packer-templates-clear/clr-installer/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:257 +0xdd7
```

**To Reproduce**
1. Clone clr-installer repo on a Fedora 29 install.
2. Run 'make'
3. Run sudo .gopath/bin/clr-installer

**Expected behavior**
No panic.  

**Environment (please complete the following information):**
 - OS Version: Fedora 29
 - Installer Version: Built from source, commit 786a1f
 - Platform: x86_64 Intel machine

**Additional context**
The context I'm using this in is building https://github.com/AntonioMeireles/ClearLinux-packer on a Fedora 29 machine.  ClearLinux-packer requires clr-installer to run and also produces the same panic.

**Comment by mdhorn** [comment]
@gblewis1 clr-installer will only run on Clear Linux OS.
The installation of Clear Linux requires several Clear Linux only applications, particularly our package installation tool swupd.

**Comment by AntonioMeireles** [comment]
@gblewis1 , 

FWIW i don't think that this is actually a `clr-installer` bug (it's ClearLinux specific and adheres to CL conventions). For a trouble free experience just use my [packer](
https://github.com/AntonioMeireles/ClearLinux-packer) over ClearLinux ... [here](
https://github.com/AntonioMeireles/ClearLinux-packer/blob/master/extras/libvirt.native/Vagrantfile) is a ready to work solution ;-) (that's what i use actually :-) )

**Comment by gblewis1** [comment]
@AntonioMeireles Ah, maybe I'm doing this incorrectly.  When I run 'make libvirt' from clearlinux-packer it tries to use clr-installer to make the image.  Is what you're suggesting to run packer from inside your clearlinux vagrant image?

**Comment by gblewis1** [comment]
(the reason I'm doing this is I want to make my own base image that has more things installed so my integration tests run faster; don't have to swupd all the bundles every time)

**Comment by AntonioMeireles** [comment]
> @AntonioMeireles Ah, maybe I'm doing this incorrectly. When I run 'make libvirt' from clearlinux-packer it tries to use clr-installer to make the image. Is what you're suggesting to run packer from inside your clearlinux vagrant image?

yes, that `Vagrantfile` would even install packer inside on 1st boot.
drawbacks - only works well - right now - with VMware and libvirt provisioners . i need to find a clean way to pkg Virtual Box guest additions in order to mount inside host folders ...

**Comment by AntonioMeireles** [comment]
@gblewis1 

join please [Clear's slack](clearlinux.slack.com) and bug me there - it's simpler. (i'm on `WET, +0000`/`Porto/Portugal`)

**Comment by mdhorn** [comment]
Looks like the conversation moved to slack.
Closing.
