### ISSUE TITLE
Update to Network Testing

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#27]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mdhorn](https://github.com/mdhorn)**
_Sunday Jul 08, 2018 at 01:09 GMT_

----

- Start test when entering Testing screen automatically
- Test --> ReTest
- If Network test passes, then remove the 'Cancel' button and default to selecting the 'Done' button.
- If any network changes are made to the configuration, unmark Testing as completed (remove the '+')
  - Change the selected network device
  - Change of Proxy URL
  - Change of the Swupd Mirror URL

**Comment by dorileo** [comment]
@mdhorn I think this issue is completed now with the #36 PR merged.

**Comment by mdhorn** [comment]
Closed by PR #36 and PR #42
