### ISSUE TITLE
Install kernel and boot-encrypted bundles before others

### ISSUE THREAD

**Issue by abecastillo** [clearlinux/clr-installer#284]
**Is your feature request related to a problem? Please describe.**
The installer currently installs boot-encrypted and kernel-native as the last bundles to install. Any interruption to the installation process would leave the system unstable/broken.

**Describe the solution you'd like**
bundles like boot-encrypted and kernel could be prioritized and installed early in the process to get some certainty that if there's any problem during installation, the system has the basic bundles to boot and continue the installation afterwards. This is specifically critical for live-desktop-beta image where the whole desktop is installed too. big bundles like desktop (or desktop-autostart) could be at the end of the installation queue

**Additional context**
Used clear-28740-live-desktop-beta.img

**Comment by mdhorn** [comment]
This is address in the 2.0.0 release as we now use a single swupd verify --install -B <all bundles> command for the installation. This also greatly shorted the installation time.
