### ISSUE TITLE
Allow use of WiFi for Installation

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#3]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mdhorn](https://github.com/mdhorn)**
_Wednesday Feb 21, 2018 at 00:59 GMT_

----

- Present the use with the list of discovered WiFi Network.
- Collect the necessary authentication type, [username], password
- Allow for manually enter a Hidden SSID
- All WiFi connection information should be saved as part of the standard data model configuration file

This is lower priority after the primary Installation flow which matches current Installation functionality has been completed.

**Estimated Effort: 1.5 man weeks**

**Comment by mdhorn** [comment]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdhorn](https://github.com/mdhorn)**
_Monday Apr 02, 2018 at 20:56 GMT_

----

After review, do not believe there is a need to save the WiFi connection information. The goal here is to enable the use of WiFi in a TUI environment. The GUI will have access to the network manager which is installed with the desktop environment. 

Should consider using the DBUS for network manager (explore https://github.com/godbus/dbus) instead of using exec calls.

**Comment by thatsamguy** [comment]
In case anyone needs wireless access during text installer before this get's merged, you can switch TTY, set up wireless with wpa_supplicant/networkd, then switch back to the installer TTY.

E.g.:
1. `CTRL + Alt + F2`
2. Login as root
3. Set as password when prompted
4. Set up networking (example below)
``` BASH
mkdir -vp /etc/wpa_supplicant/;
mkdir -vp /etc/systemd/network/;
wlan=$(networkctl list | grep wlan | awk '{print $2}');
echo "network={
    ssid=\"my-ssid\"
    psk=\"somePassphrase\"
    scan_ssid=0
    priority=1
}" > /etc/wpa_supplicant/wpa_supplicant-"$wlan".conf;

echo "[Match]
Name=wl*

[Network]
DHCP=yes" > /etc/systemd/network/81-wireless-dhcp.conf;

systemctl restart systemd-networkd;

systemctl start "wpa_supplicant@$wlan.service";
```
5. Switch back to installer `CTRL + ALT + F1`

**Comment by mdhorn** [comment]
This is now supported with release 2.0.0.
The graphical, desktop installer support WiFi (or wired) via the Gnome Network Manager.
The text-based, server installer ISO image now includes nmtui and nmcli for connecting to WiFi (or wired) network interfaces.
