### ISSUE TITLE
dmesg messages contaminating installer menu

### ISSUE THREAD

**Issue by dbkinder** [clearlinux/clr-installer#300]
**Describe the bug**
After booting to the installer, two "dmesg" messages are showing up and contaminating the installation menu screens. No obvious way to refresh the screen to clean it up.

I'm getting two messages:
````
DMAR: Allocating domain for idma64.1 failed
hdaudio hdaudioC0D2: Unable to bind the codec
````
as shown in the screenshot below

**To Reproduce**
1. Boot with installer image on USB stick
2. Select UEFI USB image to install
3. Wait a bit (20 sec) for the first message, 70 seconds for the second 

**Expected behavior**
dmesg messages should not contaminate installer menu screen

**Screenshots**
![ACRN-GSG Screenshot 2019-04-24 14-55-59](https://user-images.githubusercontent.com/11063618/56696591-20f1dc00-66a1-11e9-89d9-01004a537876.png)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28970, 28890, 28790, 28600
 - Installer Version 1.1.8
 - Platform: NUC6CAYH 

**Additional context**
I tried the current and then 3 earlier releases, with the same results.

**Comment by mdhorn** [comment]
We will have to see if "dmesg --console-off" works to resolve this.
If so, we can add this to the startup of the TUI installer.

**Comment by mdhorn** [comment]
@dbkinder Could I ask you to try running 
`dmesg --console-off`
on your system and see if that prevent message on the console?

If that resolves the issue, we can get that into the TUI release pretty soon.

I'm trying to find a way to test this better on my systems, but I'm not getting those console messages on any of my test systems.

**Comment by dbkinder** [comment]
if you unplug the USB drive while the installer menu is shown, you'll get LOTS of these dmesg messages written on the console :)

**Comment by mdhorn** [comment]
All of the dmesg messages are stopped by the change, but not the "DMAR: Allocating domain for idma64.1 failed".

**Comment by mdhorn** [comment]
Confirmed fixed. Will be in release 1.2.4 later today.
