### ISSUE TITLE
Image Generation Requirement

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#33]
Ensure the image generate tool is compatible will existing commands which currently use ister.py
- Example, mixer build image –native
This is just a wrapper around calling another command:
```
ister.py --template-file file:///home/loon_123/mixer/release-image-config.json 
--contenturl=file:///home/user/mixer/update/www 
--versionurl=file:///home/user/mixer/update/www 
--format=25
```

**Comment by dorileo** [comment]
How related is this issue with #59 ?

**Comment by mdhorn** [comment]
This is better tracked in #59 
Closing
