### ISSUE TITLE
Advanced Configuration fails with existing paritions

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#333]
**Describe the bug**
Using a disk with existing partitions can fail to install using Advanced Configuration

**To Reproduce**
1. Have a system with a disk with existing partitions
2. Launch TUI
3. Select Media Config
4. Select Advanced Config
5. Select the Auto Partition for the disk with existing partitions
6. Change one of the newly defined partitions
7. Complete the required install steps
8. Installation will fail

**Expected behavior**
Installation should create all of the newly selected partitions

**Environment (please complete the following information):**
 - Clear Linux OS Version: 
Installed version: 29040
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/

 - Installer Version 
clr-installer: 1.2.1

**Additional context**
The installer is not performing the mkpart mklabel gpt
It knows that the mklabel is required after the Auto Partition, but loose that information/flag after doing any manual updates.

**Comment by meiyeenng** [comment]
Is this reproducible at all times or intermittently?

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
