### ISSUE TITLE
Swap partition is allowed for size lesser than 256MB

### ISSUE THREAD

**Issue by ganweehuang** [clearlinux/clr-installer#349]
Description
Swap partition is allowed to confirm at size lesser than 256MB.

1.	During installation go to configure media
2.	Select add partition
3.	Select swap
4.	Enter partition size to 255MB.
5.	Press confirm
                                                  
Current result
Swap partition allow for the size lesser than 256MB (eg: 255MB) to be entered.

Expected behavior 
256MB should be the requirement size and the swap partition should not allow to confirm when the size is lesser than the requirement size.

**Comment by mdhorn** [comment]
I'm not sure where the documented requirement of 256MB swap came from; 256MB is the default the installer uses, but as @ahkok stated, that is not a requirement.
I do not see a bug here.

**Comment by mdhorn** [comment]
Please provide more information or review the test case with me.
