### ISSUE TITLE
Mouse navigation during the Clear Linux installation

### ISSUE THREAD

**Issue by izamuin** [clearlinux/clr-installer#350]
**Description**
During the installation of the Clear Linux, mouse is not showing any response while only keyboard is functioning. 
**To Reproduce**
1.	Install clear linux desktop beta image
2.	Click on the installation wizard
3.	A blue menu comes out and you can begin to configure the installation.
4.	Click and move around the options with mouse
Current behavior:
During the installation of the Clear Linux, only keyboard is functioning while mouse is not showing any response. Refer to Screenshot A below.

**Expected behavior:**
Mouse should be functional at the configuration page. You should be able to move into each option to set values of and select the configuration using mouse. 
**Environment:**
•	Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29160
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**Bundles:**
NetworkManager
acpica-unix2
alsa-utils
baobab
binutils
bison
bootloader
c-basic
cheese
cloud-api
cloud-control
clr-network-troubleshooter
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
dnf
dpdk
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
htop
iperf
iproute2
iptables
kbd
kernel-install
kernel-lts
kernel-lts2018
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
locales
make
man-pages
minicom
nasm
nautilus
net-tools
network-basic
openblas
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
package-utils
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python2-basic
python3-basic
seahorse
sqlite
strace
sudo
sysadmin-basic
syslinux
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
vim
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd

**Screenshots**
Screenshot A
 
![image](https://user-images.githubusercontent.com/50229294/57431867-bf1b9f80-7266-11e9-9d7b-1b18aad71c61.png)

**Comment by mdhorn** [comment]
Thank you for your feedback. 

The use of the Text-based installer was not planned to be used in a desktop environment. Its use is a stop-gap until the Graphical installer is completed.

The Graphical installer will have full mouse support when it releases.

**Comment by d2dyno** [comment]
With latest graphical installer, neither my keyboard nor mouse work.

**Comment by mdhorn** [comment]
@d2dyno This Issue was focused on the text-based installer and mouse support.
Can you provide more information about your issue?  Hardware type (laptop, desktop, model, etc), Mouse type and how it is connected, keyboard type and how it is connected, ...

The output of `dmesg` might help in diagnosing.

**Comment by d2dyno** [comment]
Sorry for lack of info:
AMD64-based desktop, booting into either UEFI or regular BIOS of the USB3 installation media. Mouse and keyboard are both USB (Logitech MX Master and Razer BlackWidow respectively). I could not get dmesg, as neither input was usable.

**Comment by mdhorn** [comment]
@d2dyno You said "With latest graphical installer", what was the previous version which worked? And what version started failing? It would be helpful to have the full names or links so we know which version and image type.

Can you provide the dmesg output from booting an older version? Or whichever previous linux configuration you had which was booting and had a functional keyboard

**Comment by d2dyno** [comment]
I will try to use an older release. Unfortunately, this was my very first chance to test installing Clear, so I have never had a 'working' build to go back to. I am also going to try a different mouse/keyboard on a different USB port to see if that matters at all.

**Comment by mdhorn** [comment]
@d2dyno Can you also let us know if you are using a directly connected USB keyboard, USB hub, or it is a wireless USB adaptor?

**Comment by bwarden** [comment]
From IRC, the keyboard/mouse are directly connected, and:
```
0603:00f2 Novatek Microelectronics Corp. Keyboard (Labtec Ultra Flat Keyboard
1532:0037 Razer USA, Ltd
```

**Comment by mdhorn** [comment]
Closing to due to lack of updates.

**Comment by benyben123** [comment]
just booted to CL on HP laptop (intel based). No mouse (touchpad that is). Keyboard works fine.
