### ISSUE TITLE
clr installer version 29350 crash when changing swupd mirror 

### ISSUE THREAD

**Issue by clefrks** [clearlinux/clr-installer#368]
**Describe the bug**
clr-installer will crash on install when pointing the swupd mirror url to my own local mixer url

**To Reproduce**
1. Go to 'Advanced options'
2. Scroll down to 'Swupd Mirror'
3. Enter own mixer swupd mirror url
4. Proceed to install + (including setting up required options)
5. Crash!
 

**Expected behavior**
On swupd mirror page, instead of crash when installing, should do checking for valid mixer url by doing swupd verify 

**Screenshots**
![Screenshot_20190510-105451_Gallery](https://user-images.githubusercontent.com/33859587/57499790-85ed3900-7313-11e9-9bf7-8b3ed2f85e63.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 29350
 - Installer Version: 2.0.3
 - Platform: KBL NUC

**Additional context**
Attached logs
[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3164712/clr-installer.log)
[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/3164713/pre-install-clr-installer.yaml.txt)

**Comment by mdhorn** [comment]
Please rerun your test and enable debugging.

Either add '-l 4' to the command line:
`sudo clr-installer -l 4 `
or add the following the kernel boot command as described in the error message in your image.

**Comment by mdhorn** [comment]
Without debugging enabled, I can only go off of the swupd client exit code of '4'
`SWUPD_COULDNT_LOAD_MOM,              /* 4 MoM cannot be loaded into memory (this could imply network issue`

**Comment by clefrks** [comment]
Attached is the latest log with debugging enabled. 

Assumption is due to mainline and my local mix is using different swupd_root.pem key. 
Maybe on the tui page for swupd mirror, it can do swupd verify to check whether the url is valid?

[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3165014/clr-installer.log)

**Comment by mdhorn** [comment]
There seems to either be a problem with your mix or with the swupd-client:

```
2019/05/10 05:00:52 [DBG] swupd verify --url=http://koji-lts.png.intel.com/L1/update/ --path=/tmp/install-005942821 --statedir=/tmp/install-005942821/var/lib/swupd --install -m latest --force --no-scripts -B os-core-update,openssh-server,NetworkManager,telemetrics,kernel-native
2019/05/10 05:00:52 [DBG] /tmp/install-005942821//usr/share/clear/versionstamp does not exist!
2019/05/10 05:00:52 [DBG] Verifying version 10
2019/05/10 05:00:52 [DBG] Certificate verification error: self signed certificate
2019/05/10 05:00:52 [DBG] [Previous line repeated 1 time]
2019/05/10 05:00:52 [DBG] Signature check failed!
2019/05/10 05:00:52 [DBG] 139647516977088:error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:crypto/pkcs7/pk7_smime.c:285:Verify error:self signed certificate
2019/05/10 05:00:52 [DBG] Warning: Removing corrupt Manifest.MoM artifacts and re-downloading...
2019/05/10 05:00:52 [DBG] Certificate verification error: self signed certificate
2019/05/10 05:00:52 [DBG] [Previous line repeated 1 time]
2019/05/10 05:00:52 [DBG] Signature check failed!
2019/05/10 05:00:52 [DBG] 139647516977088:error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:crypto/pkcs7/pk7_smime.c:285:Verify error:self signed certificate
2019/05/10 05:00:52 [DBG] WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 10
2019/05/10 05:00:52 [DBG] Unable to download/verify 10 Manifest.MoM
2019/05/10 05:00:52 [DBG] Error: Fix did not fully succeed

```
@castulo @otaviobp Can we get some swupd eyes on this?

**Comment by mdhorn** [comment]
@castulo @otaviobp Can we get some swupd eyes on this?

**Comment by otaviobp** [comment]
> 2019/05/10 05:00:52 [DBG] WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 10

This error happened because the public certificate used for swupd doesn't match the private certificate used to generate the content. If you change the mirror URL to any other mix that wasn't published by ClearLinux installation should fail.

To test that with the installer you need to generate a mixer image based on your mix (afaik "mixer build image" does that, but not sure). Or use a hack to run swupd with --no-sigcheck.

But anyway, the installer should print an error instead of crashing.

**Comment by mdhorn** [comment]
We do not currently support installing from mixes. We are tracking the requirement to update mixer in #59 
Closing this bug, but we are now tracking an enhancement request to support the certificate flag to help enable mixes. #389
