### ISSUE TITLE
clear-29350-live-server is missing the MOTD that shows how to start clr-installer

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#371]
**Describe the bug**
clear-29350-live-server is missing the MOTD that shows how to start clr-installer

**Comment by mdhorn** [comment]
This requires a fix in DevOps, not directly in the installer.
The fix is submitted and should be in the 29380 (or higher) release.

**Comment by mdhorn** [comment]
Fixed in 29380
