### ISSUE TITLE
installer should run swupd verify with scripts

### ISSUE THREAD

**Issue by busykai** [clearlinux/clr-installer#380]
**Describe the bug**
clr-installer does not run update scripts (runs `swupd verify` with `--no-scripts` option). migration to NetworkManager relies on the installer running one-shot-updates install time. this results in behavior such as clearlinux/distribution#735

**Expected behavior**
Update scripts are run.

**Comment by otaviobp** [comment]
I don't agree installer should run any script after installation (besides configuring the bootloader), so running swupd with --no-scripts looks correct to me.

In my understanding If there is any post-update script that creates any file in the system that is required to have NetworkManager working this violates the stateless concept we have on Clear. If the user removes all files that aren't tracked by Clear Manifests (like /etc/, /var/lib/swupd/) and reboots the machine we are suppose to bring up a completely functional system.

**Comment by busykai** [comment]
actually, the post-update hooks do a lot of things that help configure the system for the first boot. so yes, they should be run.

> If the user removes all files that aren't tracked by Clear Manifests (like /etc/, /var/lib/swupd/) and reboots the machine we are suppose to bring up a completely functional system.
this will be true, so it does not violate anything. we do not ship a broken system.

**Comment by mdhorn** [comment]
Fixed in 2.0.5 release which should be in a Clear Linux* OS build in the morning.

**Comment by mdhorn** [comment]
Now available on the downloads page
https://clearlinux.org/downloads
