### ISSUE TITLE
Add kernel command line modification to GUI installer

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clr-installer#384]
**Is your feature request related to a problem? Please describe.**
The TUI (installer has a section under Advanced Options to modify kernel cmdline boot parameters. It would be nice for the GUI installer to have this for feature parity. 

**Describe the solution you'd like**
Add kernel command line modification to GUI installer as an advanced option

**Additional context**
This is useful for blacklisting modules known to give issues on first boot.

**Comment by mdhorn** [comment]
@puneetse Thank you. Yes, one of the short list of Advance Options which we have in the text-based installer that need forward porting to the graphical.

**Comment by mdhorn** [comment]
Fixed in version 2.1.0 which should land in a new release of Clear Linux* OS in the next 2-3 days.
