### ISSUE TITLE
No `extlinux.conf`?

### ISSUE THREAD

**Issue by ahkok** [clearlinux/clr-installer#386]
A user installed on a system with legacy-only BIOS. The user ended up on a system without properly installed legacy BIOS bootloader:

- extlinux.conf was missing
- UEFI files were present
- `mbr.bin` was not written to the MBR

Seems like half of this should have been fixed by `clr-boot-manager` too

**Comment by ahkok** [comment]
https://pastebin.com/cY7Fi0tM

**Comment by mdhorn** [comment]
@ahkok When did we start supporting Legacy-only BIOS?
In the latest release we just added a check that if you do not have UEFI enabled, it will not install.
Is there some disconnect on my part?

@evil-brain

**Comment by ahkok** [comment]
Why are we making ISO images if we don't support BIOS?

**Comment by mdhorn** [comment]
The ISO will boot in BIOS, but if you do not have UEFI support enabled, we will not install -- otherwise, the newly installed system will not boot.

**Comment by ahkok** [comment]
ahhhhhhhhhh

**Comment by ahkok** [comment]
FYI I'm working on making CBM support both FAT+syslinux and EXT3+extlinux, which also solves this problem. At some point we'll be able to boot both UEFI and legacy, then.
