### ISSUE TITLE
Logger does not handle '%' in messages

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#388]
**Describe the bug**
The logger system is confused with '%' in the message content and contaminates the log file.

**To Reproduce**
1. Create a log state where the final text should contain a percent sign.

**Expected behavior**
The message is formatted correctly.

**Screenshots**
2019/05/16 16:16:03 [DBG] 34086 blocks (5.00%**!!(MISSING))(MISSING)** reserved for the super user

**Comment by jwakre** [comment]
This is caused by incorrect usage of type specifiers in the logging functions. For instance, using the `%d` specifier with a string will lead to these errors.

**Comment by mdhorn** [comment]
Fixed by https://github.com/clearlinux/clr-installer/pull/689
