### ISSUE TITLE
Installer "stalls" after selecting language choice

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#391]
**Describe the bug**
When using the graphical Clear Linux* OS Installer from the live-desktop image, the system "stalls" for a few seconds before moving to the next screen.

**To Reproduce**
1. Book the live desktop
2. Click the Installer icon
3. Select a language

**Expected behavior**
The installer should immediately move the next screen, or provide feedback on the reason for the delay.

**Additional context**
This is generally a result of having multiple media attached to the system as all devices need to be probe and partitions and content review for usable media during the installation.
The same "stall" occurs when selecting the "Rescan Media" button on the media selection screen.

**Comment by reaganlo** [comment]
Merged to upstream.
