### ISSUE TITLE
Improve password checking

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#398]
**Is your feature request related to a problem? Please describe.**
Currently, the installer only does minimal checking on the user entered passwords; minimum, maximums, and valid character set.

**Describe the solution you'd like**
Suggest adding basic sanity checks like:
- disallow common words (or full dictionary if available)
- disallow repeated characters

The goal is to match as closely as possible the current password restrictions in Clear Linux OS (passwd).

**Additional context**
These checks should apply to both user passwords for accounts as well as for the choice of the encryption password.

**Comment by karthikprabhuvinod** [comment]
@mdhorn I somehow think this repeated characters although possible to implement, is too restrictive. I realized that while I was trying it out, it was extremely painful to come up with a password which had no repeating characters. IMO, This can be especially more painful for desktop users. I have known a lot of systems which have too restrictive password policies and are discouraging for users.

That being said, Those were just my two cents, this decision is not for me to make ;).

**Followup:** Also will these password policies be enforced once a user starts using the system and tries to change it?

**Comment by mdhorn** [comment]
@karthikprabhuvinod The goal is to match as closely as possible the existing password rules implemented in Clear Linux OS.
These existing rules can be seen in the manual page for PAM Cracklib.
`man pam_cracklib`

**Comment by mdhorn** [comment]
Ran across this project, it might be useful too
https://github.com/go-passwd/validator

Or possibly just calling `cracklib-check`

**Comment by karthikprabhuvinod** [comment]
so I checked with author of PAM go wrapper github.com/msteinert/pam and his reply was consistent with what i found

> Hi Karthik,
> 
> PAM provides an abstraction over various authentication methods, e.g. UNIX password, LDAP, etc. The underlying authentication method is determined by how your system is configured. PAM doesn't provide any APIs for managing users (creating/deleting/updating).
> 
> The username/password must exist in order for the authentication to succeed. Maybe you need to rethink your design?

Looks like PAM integration although perfect will not be possible as PAM verification requires the user to pre-exist.

**Comment by karthikprabhuvinod** [comment]
So the password has to pass the following baptims of fire:
a.) min of 8 char
b.) max of 255 charcacters
c.) Unfamiliar to username OR login (The password should not more 35 percent similiar to either of those)
c.) Atleast one special character
d.) Atleast one number
e) Pass through shell based cracklib-check

**Comment by mdhorn** [comment]
Released in [2.4.3](https://github.com/clearlinux/clr-installer/releases/tag/2.4.3) in Clear Linux OS 32750 or higher.
