### ISSUE TITLE
gnome center does not load 29470

### ISSUE THREAD

**Issue by LibbyCruz** [clearlinux/clr-installer#402]
**Describe the bug**
When testing 29470 the gnome software center takes for ever to load categories and the list of installed/available bundles and flatpack packages.

**To Reproduce**
1. Downloaded clear-29470-live-desktop.iso.xz
2. created a bootable USB
3. Configured within the desktop right hand upper corner the enabled the Autoproxy URL
4. followed the gui installer wizard for basic installation path only entered the required information leaving default info as is.
5. after installation is complete I rebooted
6. after reboot I enabled and configured again the autoproxy url.
7. Open the Gnome software center

**Expected behavior**
I expected the gnome software center to open and list all the bundles and categories and packages. 

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS Version: Installed version 29470
 - Platform: Dell XPS 13

**Additional context**
also the gdm generated a core dump I have send that to Josue

**Comment by LibbyCruz** [comment]
ups I always forget to describe this step.....the installer installed 29460 since that is the latest version so after step 6 I swupd to staging then continue to try and open gnome software

**Comment by mdhorn** [comment]
This probably belongs in clearlinux/distribution instead of the installer.
The installer and the software store are two different applications.
@mrkz

**Comment by LibbyCruz** [comment]
ahhh yes, sorry I had the clr-installer Issue page opened. did not take the time to verify where I was opening this issue....

**Comment by LibbyCruz** [comment]
es la costumbre, also I should be opening this with my intel account, dont know why I am logged in with my personal accoutn.

**Comment by mdhorn** [comment]
Closing this issue which should be in Distribution. 
If the problem still exists, please re-open in https://github.com/clearlinux/distribution/issues
