### ISSUE TITLE
Make clickable area for media selection

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#404]
**Is your feature request related to a problem? Please describe.**
Selecting the media installation type is difficult.

**Describe the solution you'd like**
The Select Installation Media screen, I want to be able to click "Safe Installation" or "Destructive Installation" text instead of having to click specifically on the small radio button widget.

**Additional context**
This should work the same as the Bundle selection where I can click on the icon, description, whichever and it selects the bundle.

**Comment by reaganlo** [comment]
Fixed and merged to master.

**Comment by mdhorn** [comment]
Fixed in release 2.1.1  which should land in Clear Linux* OS release > 30610
