### ISSUE TITLE
Allow alternate kernel selection in Advanced Options in GUI

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#406]
**Is your feature request related to a problem? Please describe.**
As a user installing Clear Linux* OS, I would like to be able to select an alternative kernel from the mainline, lastest native kernel.

**Describe the solution you'd like**
Provide an option to select an alternative kernel under the Advanced Options the same as the text-based installer.

**Describe alternatives you've considered**
Run the Text-based installer from the Desktop in a terminal
`sudo clr-installer-tui`
OR
Post installation, add the desired kernel bundle

**Comment by evil-brain** [comment]
This work is also related to #384 - these options will both be on the same advanced page, one that covers kernel configuration.

**Comment by mdhorn** [comment]
Fixed in version 2.1.0 which should land in a new release of Clear Linux* OS in the next 2-3 days.
