### ISSUE TITLE
Add swupd mirror to the Advanced Options in GUI

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#407]
**Is your feature request related to a problem? Please describe.**
As a Clear Linux* OS installer I would like the option of specifying an alternative mirror from where to download via swupd.

**Describe the solution you'd like**
Add an advanced option to enter the Swupd Mirror URL the same as the Text-based installer.

**Describe alternatives you've considered**
Run the TUI from the Desktop in a terminal:
`sudo clr-installer-tui`
OR
Launch the GUI from a terminal and specify the mirror URL:
`sudo clr-installer-gui --swupd-mirror <URL>`

**Comment by mdhorn** [comment]
Consider implementing on the same Advance Options screen as #228

**Comment by reaganlo** [comment]
Done and merged to upstream.

**Comment by mdhorn** [comment]
Fixed in version 2.1.0 which should land in a new release of Clear Linux* OS in the next 2-3 days.
