### ISSUE TITLE
Enable Advance Configuration for media

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#410]
**Describe the solution you'd like**
Provide an option under Select Installation Media for Advanced Configuration the same as the Text-based UI.

**Describe alternatives you've considered**
Using the text-based installer from the desktop.

**Additional context**
All for selecting existing partitions for re-use or installation.

**Comment by mdhorn** [comment]
### Workaround
Run the TUI from the Desktop in a terminal:

- Open a Gnome terminal
- `sudo clr-installer-tui`

**Comment by mdhorn** [comment]
### Planned Changes

- Use an external tool for partitioning (`cgdisk` for text, `gparted` for graphical)
  - Note: cgdisk only manipulates partitions, does not create file systems. 
- We use Partition Labels (aka partition Name in gparted) to tag and convey which partitions should be used for advanced installation.
  - CLR_BOOT = The /boot partition; must be vfat (fat32)
  - CLR_SWAP = A swap partition to use; can be more than one
  - CLR_ROOT = The / root partition; must be ext[234] or xfs due to clr-boot-manager
  - CLR_MNT_<mount poing> = Any additional partitions that should be included in the install like /srv, /home, ...
  - Appending "_E" to the label marks it for encryption; not valid for CLR_BOOT
- If a file system exists on the partition, the clr-installer will use without changes
- If no file system exists, clr-installer will default to vfat (fat32) for /boot, ext4 for all others

**Comment by nazar2sfive** [comment]
what i do in other linux distro
1. i custom partition my harddisk 
2. use my single /dev/sda5 (50GB) as / root
3. rest of my partition are all ntfs for windows use. no /boot /swap /home etc. everything inside /sda5
4. i use other partition and make my default home folder by modifying `~/.config/user-dirs.dirs
`

i hope i will soon be able to install clear linux and try them .

**Comment by mdhorn** [comment]
@nazar2sfive Clear Linux* OS does have a requirement of having a /boot for EFI which is formatted VFAT which needs to be at least 64MB. So to install Clear Linux OS you'll need at least `/boot` and `/`.

**Comment by nazar2sfive** [comment]
@mdhorn what is the progress? Waiting eagerly.

**Comment by szollin** [comment]
Can you provide an update to this? This issue affects the completion of bug #439

**Comment by mdhorn** [comment]
@szollin We've been internally beta testing this for a week and are implementing some minor changes based on feedback.  It looks very likely we will be able to start an external release around September 11th-12th.

**Comment by dedguy21** [comment]
So is this something that will be available on the ClearLinux iso's by September 12th? 

And if not, how can an end-user test the installer?

**Comment by jwakre** [comment]
> So is this something that will be available on the ClearLinux iso's by September 12th?
> And if not, how can an end-user test the installer?

If you are interested in testing the advanced disk partitioning changes to provide early feedback you could checkout #493, build the installer yourself, and generate your own installer image. When building the installer image, you would need to use one of the example config files with the "devel-" prefix to install your custom installer into the image. Below is an example of building an installer image for testing purposes:

sudo .gopath/bin/clr-installer --config scripts/developer-live-desktop.yaml

**Comment by mdhorn** [comment]
Released in clr-installer version 2.2.0 in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads

**Comment by nazar2sfive** [comment]
![Screenshot from 2019-09-17 03-43-55](https://user-images.githubusercontent.com/12841320/65009962-2db3ec80-d92e-11e9-856e-e7d598973c9e.png)

So its finally here, jumping between gparted and installer seems huh.. but works... Thanks.

**Comment by simonbcn** [comment]
Please reopen this issue.
The text version allows to install without SWAP partition (_nowadays it is unnecessary if the RAM capacity is high_) but the graphic version does not.
