### ISSUE TITLE
Catch Fails and display to user in GUI

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#417]
**Describe the solution you'd like**
Catch errors and display the reason allow with helpful information for opening an issue similar to what the TUI does on fails.

**Comment by reaganlo** [comment]
@mdhorn What should be the title and msg body of the popup?

Should the msg body be this:
	fmt.Println("Please report this crash using GitHub Issues:")
	fmt.Println("\thttps://github.com/clearlinux/clr-installer/issues")

	fmt.Println("")

	fmt.Println("Include the following as attachments to enable diagnosis:")
	fmt.Printf("\t%s\n", preConfName)
	fmt.Printf("\t%s\n", logFileName)

	fmt.Println("")

	fmt.Println("If the problem persists, enabling additional logging will be helpful in")
	fmt.Println("diagnosing the issue. At the OS Boot screen, hit 'e' to edit the kernel")
	fmt.Println("command line. Add the following to the end of the line:")
	fmt.Println("\tclri.loglevel=4")

**Comment by mdhorn** [comment]
Fixed in version 2.1.0 which should land in a new release of Clear Linux* OS in the next 2-3 days.
