### ISSUE TITLE
Compile clr-installer error

### ISSUE THREAD

**Issue by chiachuanwu** [clearlinux/clr-installer#419]
**Describe the bug**
Not able to compile clr-installer

**To Reproduce**
1. git clone https://github.com/clearlinux/clr-installer.git
2. cd clr-installer && make
```
[chiachua@chiachua-MOBL3 clr-installer]$ git remote -v
origin  https://github.com/clearlinux/clr-installer.git (fetch)
origin  https://github.com/clearlinux/clr-installer.git (push)
[chiachua@chiachua-MOBL3 clr-installer]$ make
```

**Expected behavior**
Able to compile/make clr-installer w/o error.

**Screenshots**
![image](https://user-images.githubusercontent.com/48268589/58392421-789eb100-806c-11e9-8f7d-0140106b807f.png)

**Environment (please complete the following information):**
 - Fedora build machine
 - Clr-installer repo commit :654c87359b2ee39f13
 - Platform: Intel NUC

**Comment by chiachuanwu** [comment]
After install several packages on the build machine, now able to make clr-installer successful. 
sudo dnf install golang cairo-gobject-devel  gtk3  gtk3-devel-3.24.1-1.fc29.x86_64  glib2-devel-2.58.1-1.fc29.x86_64

**Comment by mdhorn** [comment]
@chiachuanwu Glad you could build the clr-installer, but keep in mind Fedora is probably missing several key items needed to actually perform the install.
The required items are in the [clr-installer-gui bundle](https://github.com/clearlinux/clr-bundles/blob/master/bundles/clr-installer-gui).
The biggest hurdle will likely be that swupd-client is missing; this is how we install the Clear Linux OS content.

We've only tested building and using the installer with Clear Linux OS itself.
Downloading images with the installer are here:
https://clearlinux.org/downloads
