### ISSUE TITLE
"root" partition fails to be created using "Advanced Configuration" 

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#423]
**Describe the bug**
I used the "Advanced Configuration" tool to manually create partitions, but this particular set of steps failed to create the "root" partition.  

**To Reproduce**
1. Boot up the `live-server.iso`
2. Start `clr-installer`
3. Select `Configure Installation Media`
4. Select `Destructive Installation`
5. Tab to `Advanced Configuration` and select it
6. Select the media.  It should look like IMG_2579.jpg.
7. Select `sda1 / vfat`, set its `Mount Point:` to `/boot`, and select `Confirm`.  Now it should look like IMG_2580.jpg.
8. Select `sda3 / ext4`, set its `Mount Point:` to `/`, set `Size:` to `20G`, and select `Confirm`.  See IMG_2581.jpg.
9. At this point, I was expecting to see the `sda3 / ext4`, but it's not there.  See IMG_2582.jpg.

**Screenshots**
see attachments.  

![IMG_2582](https://user-images.githubusercontent.com/29260389/58663427-56fa2f80-82e1-11e9-9bb0-1edc41f0f492.jpg)
![IMG_2581](https://user-images.githubusercontent.com/29260389/58663429-56fa2f80-82e1-11e9-87e6-806f38e35515.jpg)
![IMG_2580](https://user-images.githubusercontent.com/29260389/58663430-56fa2f80-82e1-11e9-8cea-637518019a03.jpg)
![IMG_2579](https://user-images.githubusercontent.com/29260389/58663431-5792c600-82e1-11e9-8b25-f4ed79ab7b80.jpg)

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
