### ISSUE TITLE
Can't resize above a previously-created partition even though there's disk space available

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#424]
***Describe the bug***
Can't resize above a previously-created partition even though there's disk space available

***To Reproduce***

1. Boot up the `live-server.iso`
2. Start `clr-installer`
3. Select `Configure Installation Media`
4. Select `Destructive Installation`
5. Tab to `Advanced Configuration` and select it
6. Select the media. It should look like IMG_2579.jpg.
7. Select `sda3 / ext4`, set its `Mount Point:` to `/`, set `Size:` to `20G`, and select `Confirm`. See IMG_2581.
8. At this point, it looks like IMG_2584.jpg.
9. Now, I want to increase the size of `sda3 / ext4` from 20G to 25G.  Select `sda3 / ext4` and set the size to 25G, but it will report `Size too large`.  I should be able to increase the size beyond what I first set its size to.  I know there's additional free space available.  See IMG_2585.jpg.

![IMG_2579](https://user-images.githubusercontent.com/29260389/58665940-d1797e00-82e6-11e9-8f9f-e9545caf28e8.jpg)
![IMG_2581](https://user-images.githubusercontent.com/29260389/58665945-d6d6c880-82e6-11e9-91c0-c00bc4865e16.jpg)
![IMG_2584](https://user-images.githubusercontent.com/29260389/58665954-dccca980-82e6-11e9-8d22-ce1e725fef5f.jpg)
![IMG_2585](https://user-images.githubusercontent.com/29260389/58665955-dfc79a00-82e6-11e9-8e6e-381ec621a16f.jpg)

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
