### ISSUE TITLE
Reducing size of a previously-created partitions results in 2 "Free Space"s

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#425]
**Describe the bug**
Reducing size of a previously-created partitions results in 2 "Free Space"s.

**To Reproduce**
1. Boot up the `live-server.iso`
2. Start `clr-installer`
3. Select `Configure Installation Media`
4. Select `Destructive Installation`
5. Tab to `Advanced Configuration` and select it
6. Select the media. It should look like IMG_2579.jpg.
7. Select `sda3 / ext4`, set its `Mount Point:` to `/`, set `Size:` to `20G`, and select `Confirm`. See IMG_2581.
8. At this point, it looks like IMG_2584.jpg.
9. Now, I want to decrease the size of `sda3 / ext4` from 20G to 18G.  Select `sda3 / ext4` and set the size to 18G.  Select `Confirm`.  This will result in 2 instances of "Free Space"s. See IMG_2586.jpg.

**Screenshots**
See attachments.  

![IMG_2579](https://user-images.githubusercontent.com/29260389/58666626-b90a6300-82e8-11e9-89dd-95d874964287.jpg)
![IMG_2581](https://user-images.githubusercontent.com/29260389/58666643-bf004400-82e8-11e9-9093-56cef34e3ddb.jpg)
![IMG_2584](https://user-images.githubusercontent.com/29260389/58666650-c889ac00-82e8-11e9-9b07-957eb373b61a.jpg)
![IMG_2586](https://user-images.githubusercontent.com/29260389/58666785-30d88d80-82e9-11e9-9c15-d14ad4fe7e33.jpg)

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
