### ISSUE TITLE
Manually-deleted partition shouldn't exist as a "Free Space" partition

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#427]
**Describe the bug**
A manually-deleted partition shouldn't still exist as a partition and labeled "Free Space".  Instead, the freed space would be merged into a single "Free Space" partition.  There shouldn't be multiple "Free Space" partitions if I deleted multiple partitions.  

**To Reproduce**
1. Boot up the `live-server.iso`
2. Start `clr-installer`
3. Select `Configure Installation Media`
4. Select `Destructive Installation`
5. Tab to `Advanced Configuration` and select it
6. Select the media. It should look like IMG_2579.jpg.
7. Select `sda1 / vfat`, select `Delete`, and select `Confirm`.
8. Select `sda2 / swap`, select `Delete`, and select `Confirm`.
9. Select `sda3 / ext4`, select `Delete`, and select `Confirm`.  Note, that `sda3 / ext4` still shows up as `sda3 / ext4` instead of "Free Space" which is also inconsistent.  
10. See IMG_2588.jpg for what appears after steps 7-9.  

My expectation is that after steps 7-9, there should only be a single "Free Space" partition.  

![IMG_2579](https://user-images.githubusercontent.com/29260389/58723899-13aaca00-8390-11e9-8846-9e81fca1835e.jpg)
![IMG_2588](https://user-images.githubusercontent.com/29260389/58723908-173e5100-8390-11e9-8b18-d415c4b12c37.jpg)

**Comment by mdhorn** [comment]
@bktan8 Thanks for the details on the issue.
If you run into more problems with the manual partitioning, let's wrap them all in a single GitHub Issues are most of these are interrelated and will likely be fixed together.

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
