### ISSUE TITLE
Improve i915 support for installer ISO initrd

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#428]
We may need to add an additional initrd with i915 firmware support to the ISO image generation.

**Comment by evil-brain** [comment]
Is this about dmc and guc firmware?
If so, I'd suggest we add the bundle that contains those to the yaml files.

Bundle linux-firmware (248 MB to install)
        /usr/lib/firmware/i915/skl_guc_ver9_33.bin
        /usr/lib/firmware/i915/skl_guc_ver6_1.bin
        /usr/lib/firmware/i915/skl_guc_ver6.bin
        /usr/lib/firmware/i915/skl_guc_ver4.bin
        /usr/lib/firmware/i915/skl_guc_ver1.bin
        /usr/lib/firmware/i915/kbl_guc_ver9_39.bin
        /usr/lib/firmware/i915/kbl_guc_ver9_14.bin
        /usr/lib/firmware/i915/bxt_guc_ver9_29.bin
        /usr/lib/firmware/i915/bxt_guc_ver8_7.bin

**Comment by mdhorn** [comment]
Closing as has not reappeared as a complaint.
