### ISSUE TITLE
Allow dot '.' and upper case letters in login

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#432]
**Is your feature request related to a problem? Please describe.**
There is a pending change to the Clear Linux OS useradd program to allow both dot '.' and upper case letters in the login name.

**Describe the solution you'd like**
Update the Clear Linux OS Installer to allow both '.' and upper case letters
Revert 3b284e0865850c0ed37c26a9476166ea09a06783

**Comment by mdhorn** [comment]
This change is linked to the possible implementation of
https://github.com/clearlinux/distribution/issues/829

**Comment by ahkok** [comment]
`shadow` changes are pending release now.
