### ISSUE TITLE
Can't reach installer buttons on small screen

### ISSUE THREAD

**Issue by tmlbl** [clearlinux/clr-installer#434]
**Describe the bug**
On a small netbook (Thomson NEO10) the installer window is so large that the "confirm" button on the bottom is off-screen. There is no obvious way to move or resize the installer window.

**To Reproduce**
1. Attempt to move or resize the installer window

**Expected behavior**
You can move it or make it smaller like a normal window

**Screenshots**
![IMG_20190606_104455](https://user-images.githubusercontent.com/6007526/59054309-3e8d9600-8848-11e9-8527-b6c24435fb6d.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28790
 - Installer Version 2.0.6
 - Platform: Thomson NEO10 Netbook

**Comment by mdhorn** [comment]
@tmlbl  What is the resolution of your display?

The graphical installer is intentionally made to not resize for several reasons.

### Workaround
Run the TUI from the Desktop in a terminal:

**Open a Gnome terminal**
`sudo clr-installer-tui`

**Comment by tmlbl** [comment]
@mdhorn I did figure out how to run the terminal installer, so I'm not unable to install. If this is a "won't fix" feel free to close it.

The display is quite small - 1024x600

**Comment by mdhorn** [comment]
@tmlbl  I'm tring to see if we established a minimum display resolution or not for Clear Linux* OS. Once I know I'll close this.
We saw similar issues running in virtualization with small resolutions.

**Comment by mdhorn** [comment]
When bandwidth is available, we will consider making the window movable, but not resizable.

**Comment by mdhorn** [comment]
Fixed by https://github.com/clearlinux/clr-installer/pull/555

**Comment by mdhorn** [comment]
Fixed in clr-installer release [2.3.1](https://github.com/clearlinux/clr-installer/releases/tag/2.3.1) in Clear Linux OS release 31270 or later.
