### ISSUE TITLE
clr-installer-gui(29800) crash with output to terminal

### ISSUE THREAD

**Issue by ckrzen** [clearlinux/clr-installer#435]
Installing to a Lenovo ThinkPad X240 with the clear-29800-live-desktop.iso on USB 3.0 drive:

Here are the errors:

`fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0xb7c9a4, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:374 +0x4a9

goroutine 37 [syscall, 8 minutes]:
runtime.cgocall(0x9e9270, 0xc0000e3ad8, 0xc0002bb9e0)
	/usr/lib/golang/src/runtime/cgocall.go:128 +0x5b fp=0xc0000e3aa8 sp=0xc0000e3a70 pc=0x46defb
github.com/clearlinux/clr-installer/vendor/github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:13652 +0x41 fp=0xc0000e3ad8 sp=0xc0000e3aa8 pc=0x7cd161
github.com/clearlinux/clr-installer/vendor/github.com/gotk3/gotk3/gtk.Main(...)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/vendor/github.com/gotk3/gotk3/gtk/gtk.go:943
github.com/clearlinux/clr-installer/gui.(*Gui).Run(0xc000146340, 0xc0000d81e0, 0xc000186020, 0x16, 0x100, 0xc000090de0, 0x17, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/gui/gui.go:97 +0x2b5 fp=0xc0000e3c78 sp=0xc0000e3ad8 pc=0x981025
main.main.func5(0xc0000c5900, 0xc0000d81e0, 0xc000186020, 0x16, 0xc000284830, 0xc000140610, 0xc000172070)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:317 +0x18d fp=0xc0000e3fa8 sp=0xc0000e3c78 pc=0x9e139d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000e3fb0 sp=0xc0000e3fa8 pc=0x4c3381
created by main.main
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:311 +0xdb0

goroutine 1 [chan receive, 8 minutes]:
main.main()
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:352 +0xe09

goroutine 19 [syscall, 8 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 38 [chan receive, 8 minutes]:
main.main.func6(0xc0001210e0, 0xc0000d81e0, 0xc000172070)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:344 +0x52
created by main.main
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:343 +0xdef

goroutine 44 [runnable]:
bufio.ScanLines(0xc0003c326c, 0x7c, 0xd94, 0xd00, 0x7c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/scan.go:345 +0x19b
bufio.(*Scanner).Scan(0xc0001bef18, 0xc00008cc80)
	/usr/lib/golang/src/bufio/scan.go:145 +0x580
github.com/clearlinux/clr-installer/cmd.RunAndProcessOutput(0xc17b40, 0xc000094180, 0xc0002c4120, 0xb, 0x12, 0xc0002c4120, 0x9)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/cmd/cmd.go:160 +0x29f
github.com/clearlinux/clr-installer/swupd.(*SoftwareUpdater).VerifyWithBundles(0xc0000a4070, 0xb6a016, 0x6, 0x0, 0x0, 0xc0000b60e0, 0xd, 0xe, 0x0, 0x0)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/swupd/swupd.go:309 +0x56c
github.com/clearlinux/clr-installer/controller.contentInstall(0xc000186020, 0x16, 0xb6a016, 0x6, 0xc0000d81e0, 0x100, 0xc000090de0, 0x17, 0x0, 0x0, ...)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/controller/controller.go:486 +0x2ae
github.com/clearlinux/clr-installer/controller.Install(0xc000186020, 0x16, 0xc0000d81e0, 0x100, 0xc000090de0, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/controller/controller.go:357 +0x1cc7
github.com/clearlinux/clr-installer/gui/pages.(*InstallPage).ResetChanges.func1(0xc0001d4dc0)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/gui/pages/install.go:175 +0x14a
created by github.com/clearlinux/clr-installer/gui/pages.(*InstallPage).ResetChanges
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/gui/pages/install.go:165 +0xf5
`

**Comment by ckrzen** [comment]
[clr-installer-29800-crash-full.out.txt](https://github.com/clearlinux/clr-installer/files/3263637/clr-installer-29800-crash-full.out.txt)

**Comment by dch** [comment]
me also, I ran clr-installer successfully via terminal with sudo. This is a really serious issue as the installer leaves the disk partly partitioned and largely empty of data depending on  it actually crashes.

**Comment by mdhorn** [comment]
I've move these comments to #381 which is this a duplicate

**Comment by mdhorn** [comment]
Dup (same data collection for) of #381
