### ISSUE TITLE
Manually Creating Partitions Locks Disks on Second Partition Creation

### ISSUE THREAD

**Issue by manowared** [clearlinux/clr-installer#439]
**Describe the bug**
After successfully creating the first partition, when trying to add the second partition, the installer locks the disks. The only option on there is revert, which puts us in an endless loop of recreating the partitions and reverting again.

**To Reproduce**
1. Go to advanced in the disk selection menu
2. Create the first partition
3. Create the second partition

**Expected behavior**
More than one partition should be created and not lock me out

**Screenshots**
![Clr-Installer01](https://user-images.githubusercontent.com/45432265/59474637-825e3d80-8dfc-11e9-97b6-88aacdbff163.jpg)
![Clr-installer02](https://user-images.githubusercontent.com/45432265/59474664-999d2b00-8dfc-11e9-95cb-b3a0390de4d6.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS Version: [29870]
 - Installer Version [clr-installer -v 2.0.6]
 - Platform: [Dell PowerEdge R640]

**Comment by szollin** [comment]
I was able to replicate the issue. I also checked to see if the partitions could be created prior and then mapped. After 2 changes, the disk gets locked with the same warning. I also tried to delete. That also locks me after 2 changes. This looks to be something with a value of 2 causing the disk to get locked.

**Comment by mdhorn** [comment]
This will be addressed by the changes to Advanced Configuration in #410

**Comment by dedguy21** [comment]
Just curious to an ETA for this issue. Having the same issue with intall

**Comment by mdhorn** [comment]
Starting validation this week for the text-based installer. 
Could be released as early as the end of this week, but more likely mid-next week.

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
