### ISSUE TITLE
Update Graphical Telemetry Screen to match Text Telemetry

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#442]
**Describe the solution you'd like**
The text-based installer Telemetry screen has two specific buttons for "No, opt-out" and "Yes, opt-in" which makes it clear to the user the selection they are making. We would prefer this same choice presented in the graphical installer versus the checkbox approach.

**Additional context**
Having the user choose the clearly labeled button will help ensure they understand their choice.

**Comment by reaganlo** [comment]
Merged to master.
