### ISSUE TITLE
Ensure all installation step failures show up as incomplete

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/clr-installer#447]
**Describe the bug**
When certain steps in the installation page fails, the image next to it shows up as complete (ticked). Instead, it should show up as incomplete and probably in a different color.

**Expected behavior**
When certain steps in the installation page failure, the image next to it shows up as complete (ticked). Instead it should show up as incomplete and probably in a different color.

**Comment by mdhorn** [comment]
Fixed in release [2.4.0](https://github.com/clearlinux/clr-installer/releases/tag/2.4.0)

**Comment by mdhorn** [comment]
Released in Clear Linux OS 32380
