### ISSUE TITLE
do not allow btrfs for / (root) as it is not support by clr-boot-manager 

### ISSUE THREAD

**Issue by seanvk** [clearlinux/clr-installer#448]
Repeatable

Used clr-installer

Advanced partitioning

[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3308684/clr-installer.log)

**Comment by seanvk** [comment]
clrlinux@clr-live~ $ sudo clr-installer
Please report this crash using GitHub Issues:
	https://github.com/clearlinux/clr-installer/issues

Include the following as attachments to enable diagnosis:
	/root/pre-install-clr-installer.yaml
	/root/clr-installer.log

If the problem persists, enabling additional logging will be helpful in
diagnosing the issue. At the OS Boot screen, hit 'e' to edit the kernel
command line. Add the following to the end of the line:
	clri.loglevel=4

panic: exit status 1

Error Trace:
errors.Wrap()
     errors/errors.go:91
controller.contentInstall()
     controller/controller.go:516


goroutine 52 [running]:
main.fatal(0x8dd580, 0xc00017a080)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:54 +0x166
main.main.func5(0xc0000c9900, 0xc000172000, 0xc000168020, 0x16, 0xc0002d0768, 0xc00013e600, 0xc00006a0e0)
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:333 +0x41f
created by main.main
	/builddir/build/BUILD/clr-installer-2.0.6/.gopath/src/github.com/clearlinux/clr-installer/clr-installer/main.go:311 +0xd6e

**Comment by seanvk** [comment]
Using btrfs for root partition.  As I mentioned on IRC, I believe you need to remove btrfs as an option for selection/format until clr-boot-manager supports btrfs.

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
