### ISSUE TITLE
Choose filesystem for installation

### ISSUE THREAD

**Issue by jbrepogmailcom** [clearlinux/clr-installer#452]
The installer always destroys partition for installation and formats it as ext4. It does not install into preprepared partition scheme nor it allows to install with other filesystem. I wish to use xfs or btrfs. Other distros allow user to choose the FS.

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/60144268-72bdfc00-97e1-11e9-977d-37aaf002ad74.png)
i need them . else its no clear linux for me on my laptop.
btw clear linux is GREAT!

**Comment by mdhorn** [comment]
Currently, the installer is working as designed. 

We are already tracking adding advanced media configuration in #410 

This is one of the next items we are working on for the Installer and should be addressed in the coming weeks.

Closing this item as duplicate.
