### ISSUE TITLE
Is there any way to run clr-installer with few custom-rpms (locally generated)?

### ISSUE THREAD

**Issue by bmodem** [clearlinux/clr-installer#461]
Hi All,

I have made a few changes in CL kernel & some other packages and generated rpms. Now I would like to generate a custom image using clr-installer with my locally generated rpms & rest of the bundles are from upstream.

Is there any way to do that? Can someone please help me to unblock this?

**Comment by mdhorn** [comment]
The right way to do this is use `mixer` to create your own custom of mix of Clear Linux* OS plus your local RPMs.
See https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer

Once you have a mix, you can build an installer image using your own mix.

**Comment by bmodem** [comment]
Thanks for the info Mark Horn,

Is this approach addresses my query?
- Create an image using clr-installer
- Mount using the loop devices (losetup)
- Install locally generated rpms on image rootfs. (extract rpm & copy to <mount location>/usr)
- Unmount

**Comment by mdhorn** [comment]
> Thanks for the info Mark Horn,
> 
> Is this approach addresses my query?
> 
> * Create an image using clr-installer
> * Mount using the loop devices (losetup)
> * Install locally generated rpms on image rootfs. (extract rpm & copy to /usr)
> * Unmount

The sustainable approach is what I previously mentioned.

The software updater (swupd) may overwrite any files it does not know about. By default, it ignores files in  /usr/lib/kernel, /usr/lib/modules, /usr/src and /usr/local, but anything outside of that could be overwritten or removed by an update.

So if you one-off RPMs install into one of the unmanaged directories you may be okay with your model. But then you need to think about how to update those one-off RPMs moving forward.
