### ISSUE TITLE
Clean lock file when external processes exit with non-zero status

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-installer#463]
**Describe the bug**
When clr-installer is calling out to external processes, be it post install scripts, swupd, telem-record-gen, etc, if one of these processes exits with a non-zero status, the .lock file that the clr-installer creates lingers around and is not removed.  This should be removed since the clr-installer has a chance to clean this up.

**To Reproduce**
1. Create an image with a disk size that is too small to trigger swupd to run out of disk space
2. See that the clr-installer exits and leaves around it's corresponding .lock file.

**Expected behavior**
The clr-installer should remove the .lock file when once of its external processes exits with a non-zero status.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS Version: N/A
 - Installer Version: 2.0.8
 - Platform: N/A

**Additional context**
N/A

**Comment by mdhorn** [comment]
Fixed in version 2.1.0 which should land in a new release of Clear Linux* OS in the next 2-3 days.
