### ISSUE TITLE
Support installing on 'Connected' block devices

### ISSUE THREAD

**Issue by grothja** [clearlinux/clr-installer#468]
**Is your feature request related to a problem? Please describe.**
I was attempting to build an image for AWS (`clr-installer -c scripts/aws.yaml`) on a EBS-backed EC2 instance and it errored out with the following:

```
panic: Unrecognized block device state: Connected
```

Sure enough, after running `lsblk -O` I could see that the root disk device shows as `Connected`, which is expected, given that it is an EBS volume.

**Describe the solution you'd like**
I will submit a PR to support `Connected` block devices.  I imagine this will support other SAN-attached block devices in addition to AWS/EBS.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by mdhorn** [comment]
@grothja Thank you for this report.

We have not run the installer under AWS as the usage had been either [downloading and using our latest AWS specific image]( https://clearlinux.org/downloads ) or using the [AWS image of Clear Linux* OS which is published in AWS](https://clearlinux.org/documentation/clear-linux/tutorials/aws-web).   

We are definitely missing `Connected` as a device status.

**Comment by grothja** [comment]
Thanks everyone, the installer works as expected in `2.1.0`, building images on EBS volumes/connected devices.

**Comment by mdhorn** [comment]
@grothja Thanks again for your contribution.
