### ISSUE TITLE
scroll menu with mouse

### ISSUE THREAD

**Issue by dorileo** [clearlinux/clr-installer#47]
**Describe the bug**
Should it be possible to move the scrollable frame via the scrollbar with the mouse? Only tabbing/arrows seem to work.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by dorileo** [comment]
frame scrolling with menu should be supported on clui.

**Comment by mdhorn** [comment]
Closing as won't fix as we have decided we will not support mouse options (many of them may work) in the text-based user interface, only the graphical interface.
