### ISSUE TITLE
Change "Test Network Settings" in the Advanced Options screen to "Verify Connection to Clear Linux OS Update Server"

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#471]
I think "Test Network Settings" maybe misleading because it's specifically testing for connection to the update server.  In clr-installer, the user tries "Test Network Settings" and it might fail because the update server isn't available for whatever reason.  The user can verify their "network settings" work because they can curl some website or download stuff at the command line, but it still fails in clr-installer.  This might be confusing to the user 
and point fingers at clr-installer being problematic.

I suggest being more exact by changing it to "Verify Connection to Clear Linux OS Update Server."

This should also be applied to the live-desktop installer as well.  The failure message in live-desktop is "Installation failed: Network is not working" which is not accurate.

**Comment by chuckn408** [comment]
This issue appears to be fixed.

**Comment by mdhorn** [comment]
This is no longer an issue with the support for offline installations in #504
