### ISSUE TITLE
clr-installer fails to boot on Advanced Partitioning

### ISSUE THREAD

**Issue by seanvk** [clearlinux/clr-installer#480]
**Describe the bug**
Using command line clr-installer with advanced filesystem partitioning, setup /boot (vfat), small swap, and / (xfs).  Device failed to boot.
**To Reproduce**
1. clr-installer (CLI version)
2. Advanced partitioning (/boot (vfat), small swap, / (xfs))
3. Reboot
4. UEFI fails to find an OS on the disk, searches for network

**Expected behavior**
Boots into clear

**Environment (please complete the following information):**
 - Clear Linux OS Version: [30450]
 - NUC Skylake

**Comment by mdhorn** [comment]
Can you share the YAML file `/root/pre-install-clr-installer.yaml` and the log file `/root/clr-installer.log` from the install?

Also, a screenshot (picture) or more description of why it is failing to boot.

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads
