### ISSUE TITLE
Installer fails on "panic: Invalid Time Zone 'UTC'"

### ISSUE THREAD

**Issue by ryaniskira** [clearlinux/clr-installer#482]
Title, the installer will absolutely refuse to start and instead will produce that error no matter what. Exporting a TZ variable (in my case America/New_York) nor using tzselect will work, it will continue to fail on that error. This is on the most recent image as of 2019-07-26 at 00:32.

**Comment by reaganlo** [comment]
This could happen if `gparted` is running on the system. This is an issue in the clearlinux distribution https://github.com/clearlinux/distribution/issues/943. You may please retry the installation without `gparted` running on the system.

**Comment by ryaniskira** [comment]
I just rebooted and did not open gparted that time and it worked.

**Comment by mdhorn** [comment]
@ryaniskira Good to hear that worked.
We are still trying to get the problem with Gparted blocking systemd services fixed. That is tracked in the distro github issue. https://github.com/clearlinux/distribution/issues/943
