### ISSUE TITLE
Fix Chinese translation for letter

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#488]
**Describe the bug**
The Chinese translation for the word letter is using `letter` like mail, instead of the intended `letter` from the alphabet.

**To Reproduce**
1. Launch the graphical installer
2. Select Chinese as the language
3. Select the User Manager screen
4. See incorrect translation noted in the image below.

**Expected behavior**

English | Current Chinese PRC | Suggested Chinese PRC
-- | -- | --
Must start with letter. | 必须以一封信开头。 | 必须以字母开头。

**Screenshots**
![Chinese_User_translate](https://user-images.githubusercontent.com/12535259/62325069-b5699880-b45f-11e9-9fbe-35f40a56257e.png)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 
Installed version: 30620
 - Installer Version:
clr-installer: 2.1.1

**Comment by reaganlo** [comment]
Currently 

- `Must start with letter.` is `必须以字母开头。`
- `Must begin with a letter.` is `必须以一封信开头。`

Which one is incorrect? Or are they both incorrect?

**Comment by mdhorn** [comment]
@mvincerx FYI

**Comment by lebensterben** [comment]
>Currently  ...

@reaganlo the first one is correct.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reaganlo** [comment]
Fixed and merged to master.
