### ISSUE TITLE
No EFI entry is created!

### ISSUE THREAD

**Issue by Luraktinus** [clearlinux/clr-installer#491]
**Describe the bug**
The installer does not create an efi entry so the system fails to boot.

**To Reproduce**
1. Install Clear Linux
2. run efibootmgr -v 
3. ???

**Expected behavior**
Clear Linux Installer creates an EFI entry so my system does not fail to boot

**Additional context**
I have an ASUS motherboard
https://github.com/clearlinux/distribution/issues/808
https://community.clearlinux.org/t/no-uefi-entry-after-install-what-am-i-doing-wrong/494

![8ck2hcf](https://user-images.githubusercontent.com/33608674/62638633-261c2380-b93e-11e9-80a1-60b7274c59ee.jpg)

**Comment by mrkz** [comment]
From @Luraktinus pc

![lsboot](https://user-images.githubusercontent.com/978752/62638448-1a5f3b80-b903-11e9-9983-f210d56d7257.jpg)

**Comment by bwarden** [comment]
Issue was resolved with a motherboard firmware update.

**Comment by Luraktinus** [comment]
yep
