### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#5]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mdhorn](https://github.com/mdhorn)**
_Wednesday Feb 21, 2018 at 01:37 GMT_

----

Implementation of the User Interface using a Graphical library.

The GUI and the planned TUI should allow of the collect of the exact same set of data items. 
When possible in the design, the GUI and TUI should attempt to implement the same or similar screen types for data collection and follow a comparable workflow. 

All public data from the Data Model (#4) should be settable in the GUI; though many items might only be accessible via an Advanced settings screen/menu. Several of the data items may be set by the Automatic Detection of Installation Environment (#5) in which case the use will not be prompted.

**Estimated Effort: 8-10 person weeks**

**Comment by mdhorn** [comment]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdhorn](https://github.com/mdhorn)**
_Wednesday Feb 21, 2018 at 02:35 GMT_

----

Enable Internationalization for the GUI.

**Comment by mdhorn** [comment]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdhorn](https://github.com/mdhorn)**
_Friday Mar 02, 2018 at 21:29 GMT_

----

Consulting with UX team.
See https://drive.google.com/drive/folders/1WE9Y8E0JcoCyV8OJRmFtzzdDsKZYqF8e?usp=sharing

**Comment by mdhorn** [comment]
<a href="https://github.com/mdhorn"><img src="https://avatars.githubusercontent.com/mdhorn" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdhorn](https://github.com/mdhorn)**
_Friday Apr 06, 2018 at 00:31 GMT_

----

Check if the system has a graphics card:
`if [ -c /dev/dri/card0 ]; then echo GIU ; fi
`
if so, launch GUI, else fall back to launching TUI

**Comment by mdhorn** [comment]
Best binding to use?
https://github.com/gotk3/gotk3

**Comment by ikeyd** [comment]
Using gotk3 in my local experiments. As we're launching the installer from *within* a desktop we can trivially rely on `gtk_init_check` (`gtk.InitCheck`) in `MustRun` with the GUI set before the TUI in our cascade, and this will take care of appropriately using the GUI when a desktop environment is available (or rather, display server)

**Comment by mdhorn** [comment]
Release 2.0.0
