### ISSUE TITLE
Mouse click processed in wrong Tab

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#50]
**Describe the bug**
When clicking with the mouse on a menu button in the Advanced Tab, it runs the menu button in the same location on the Required Tab.

**To Reproduce**
1. Start Installer
2. Type 'A' to switch to the Advanced Tab
3. With the Mouse, click on "Assign Hostname"
4. Instead of the Hostname dialogue, you will see the Enable Telemetry from the Required Tab

**Expected behavior**
The dialogue for the clicked Menu button is started

**Environment (please complete the following information):**
 - Clear Linux OS Version: [
```
Installed version: 24710
Version URL:       https://download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
```
 - Installer Version [clr-installer -v]
`clr-installer: 0.8.0
`

**Comment by dorileo** [comment]
done
