### ISSUE TITLE
When producing an image from a custom mix, "version: 0" wrongly points to upstream's latest _version

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#502]
When producing an image from a custom mix, "version: 0" wrongly points to upstream's latest version instead of my custom mix's latest version number.  I have to specifically edit the YAML file each time the version is updated.  

Please change clr-installer to point </path/to/my_mix/update/www/version/latest_version>.

**Comment by mdhorn** [comment]
Fixed in clr-installer release [2.3.1](https://github.com/clearlinux/clr-installer/releases/tag/2.3.1) in Clear Linux OS release 31270 or later.
