### ISSUE TITLE
How to recover/boot to my clear linux?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/clr-installer#511]
what i did to create as seen my partition

- prev i had MBR and multiple windows partition. I used Clear linux OS boot usb and did a destructive install on my 500 Gb harddisk.
- It initially created **3**, linux swap, and /
- i booted ubuntu usb iso , used gparted to create space from /
- i shrinked the / to **1**(which i planned for /root) and **2**(which i planned for /home)
- i booted windows 10 install and did a windows install after shrinking some space from my planned /home
- now there is no more clear linux in boot for me to choose to boot.

summary:
- i have my clear linux install at partition "**1**"
- how to boot back to clear linux ? How to create a dual boot option at boot for clear linux and windows 10.
(now typing from windows 10)

![image](https://user-images.githubusercontent.com/12841320/64748685-b4358c00-d532-11e9-8bc7-7452f0642a95.png)

**Comment by mdhorn** [comment]
@bktan8  Do you have any advice for this user?

**Comment by bktan8** [comment]
@nazar2sfive - If you don't mind starting over again, the following approach is simpler:

1. Install Windows and reserve at least 20GB for Clear Linux
2. Shutdown Windows
3. Boot up the Clear Linux installer
4. Select “Select Installation Media” and select “Safe Installation”
5. Go through remaining steps to install Clear Linux
6. Reboot
7. During the BIOS POST stage, press the proper F-key for your system to bring up the “Boot Menu”
8. Now, select the Windows partition (“Windows Boot Manager”) to boot Windows or select the other one to boot Clear Linux

If you really want to correct your current setup, I would need to replicate how you did it and provide you the exact steps to fix it.

**Comment by nazar2sfive** [comment]
@bktan8 i did "destructive install" as "safe installation" didnot detected a ext4 partition which i had reserved for it.

even now when i reboot to clear linux via usb boot. it says no media found. 
![Screenshot from 2019-09-12 03-42-35](https://user-images.githubusercontent.com/12841320/64752723-50b25b00-d540-11e9-8514-b927671647c1.png)


if i had grub boot loader after windows + ubuntu. i used to create a backup bootloader in a pendrive and used to work around that to load the system.

all the clear linux system has been installed to "1"
is there no way to recover it?

(suppose a user did a fresh windows 10 install on his existing clear linux, then the dual boot option would vanish)

**Comment by nazar2sfive** [comment]
i successfully booted to my existing clear linux install.
![image](https://user-images.githubusercontent.com/12841320/64753419-e222cc80-d542-11e9-8600-0baa15494ef6.png)

I never knew how uefi works i suppose.
i was used to legacy boot where i had option to choose between the os to boot.

here in my case - if i allow the laptop to run on its own on boot - it loads windows 10.
![image](https://user-images.githubusercontent.com/12841320/64753483-27df9500-d543-11e9-822d-fcd1f0b560e3.png)

but if my press F12(for me) and select option "1"- it boots to clear linux. and if i choose option "2" , it boots to windows 10.

**Comment by nazar2sfive** [comment]
So i just learned that clear linux doesnot use grub. 

Why is clear linux not detecting my "2" ext4 of 100GB for safe install?? 

Suppose my clear linux severely crash and i have to re-install clear linux. "safe install" wont detect my "2" partition and i will have to start with "destructive install" once again. 

also waiting eagerly for #410 to solve.

**Comment by mdhorn** [comment]
This should be resolved using the latest Advanced Disk configuration option enabled the latest release clr-installer version 2.2.0   in [Clear Linux* OS release 31030](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz).
Latest release images are available here: https://clearlinux.org/downloads

**Comment by nazar2sfive** [comment]
@mdhorn yes now it would solve my problem

why is releases available in .xz and not directly as .iso
we have to install 7z , extract image, and use it against rufus (from windows user side) to use it.

**Comment by mdhorn** [comment]
@nazar2sfive The installer only generates an ISO, our DevOps is the team creating the xz version.

**Comment by bktan8** [comment]
@nazar2sfive:

1) The reason we compress the ISO is to save space on our server and save you download time and bandwidth.  You can see here:

```
bktan8$ ls -alh clear-31030-live-desktop.iso.xz 
-rw-r--r--@ 1 bktan8  staff   2.4G Sep 17 10:36 clear-31030-live-desktop.iso.xz
bktan8$ gunzip clear-31030-live-desktop.iso.xz 
bktan8$ ls -alh clear-31030-live-desktop.iso
-rw-r--r--  1 bktan8  staff   2.5G Sep 17 10:36 clear-31030-live-desktop.iso
```

2) It's not necessary for you to uncompress the .xz prior to using Rufus to burn the image onto a thumb drive.  Rufus uncompresses and burns automatically.  You just point it the downloaded file. 

Let us know if we can be of more help to you.
