### ISSUE TITLE
Provide more user feedback during installation

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#516]
**Is your feature request related to a problem? Please describe.**
Several of the installations steps do not report progress but jump for 0 to 100.

**Describe the solution you'd like**
Ensure each installation step starts to be presenting the work to be done, and then an updated progress bar.

**Additional context**
The steps of concern are from the Clear Linux* OS package manager (swupd) which is the tool used for installing the content. 
Need to open bugs and cross-reference them here as swupd needs the updates first.

**Comment by mdhorn** [comment]
Dup of https://github.com/clearlinux/clr-installer/issues/396

**Comment by mdhorn** [comment]
Based on the requirement given to the swupd team, the changes for this can be started.
When the first entry is a '-1' in the json for the stepCompletion the installer should use an indeterminate spinner or progress bar; otherwise create a deterministic progress bar. Both cases will end with '100' for the stepCompletion.
@otaviobp We should make sure we agree on this.

**Comment by jwakre** [comment]
Currently, swupd doesn't provide enough progress updates for all of the install stages. The swupd team is working on solving this, but until then the installer is blocked.

**Comment by jwakre** [comment]
Swupd team created a PR for the progress bar updates, unblocking. clearlinux/swupd-client#1142

**Comment by mdhorn** [comment]
Fixed in https://github.com/clearlinux/clr-installer/releases/tag/2.3.2

**Comment by mdhorn** [comment]
Available in Clear Linux OS release 31380 and higher.
https://clearlinux.org/downloads
