### ISSUE TITLE
Installer enhancement to support clr-boot-manager updates

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#517]
**Is your feature request related to a problem? Please describe.**
clr-boot-manager will be making updates to better support booting non-UEFI systems.
Once these changes are released in c-b-m, the installer will need to be updated to take advantage of them.

**Describe the solution you'd like**
- Remove the hard requirement for UEFI to be enabled on the system (#666)
- Ensure the updates are made for the image creator (massinstaller), the UI, and as part of the Advanced Disk configuration

**Additional context**
- Ensure the clr-installer documents and tutorials are updated

**Comment by dorileo** [comment]
c-b-m 3.2 does support the following:
+ "partitionless" /boot - we'll know how to update kernels on systems where /boot hasn't a dedicated partition;
+ /boot may be vfat or ext[2-4] formatted
+ non-EFI systems bootloaders

With the clr-installer commit eb898789bf02825b71197b23fe90c78e888181f5 we already support creating images - with massinstaller - with either vfat or ext[2-4] /boot partition.

All the remaining integrations still need to be implemented.

**Comment by mdhorn** [comment]
Released in [2.4.3](https://github.com/clearlinux/clr-installer/releases/tag/2.4.3) in Clear Linux OS 32750 or higher.
