### ISSUE TITLE
clr-installer --config to support HTTP (like kickstart)

### ISSUE THREAD

**Issue by seanhig** [clearlinux/clr-installer#524]
**Is your feature request related to a problem? Please describe.**

Attempting to use clear linux in Packer where I would normally use CentOS or RHEL.

**Describe the solution you'd like**

Have the clr-installer support passing an HTTP url to the --config parameter such that the same mechanism used by RHEL kickstart can be used with Packer (where the live-server.yaml configuration can be delivered over HTTP to the bootstrap).  This simplifies the installation process and enables existing Packer tooling to be used to create clear linux system images.

Eg.

clr-installer --config http://packerhost:8000/live-server.yaml

**Describe alternatives you've considered**

N/A

**Comment by mdhorn** [comment]
@seanhig Thanks for your request.
This should not be too difficult as we already support using a URL for the configuration file when supplied as a kernel boot argument.

**Comment by mdhorn** [comment]
Fixed in clr-installer release [2.3.1](https://github.com/clearlinux/clr-installer/releases/tag/2.3.1) in Clear Linux OS release 31270 or later.

**Comment by seanhig** [comment]
Fantastic everyone, thank you so much.  I will test this ASAP.
