### ISSUE TITLE
Failed to install from USB stick

### ISSUE THREAD

**Issue by olivierchatry** [clearlinux/clr-installer#525]
**Describe the bug**
* Downloaded latest version ( 31030 ) desktop ISO. 
* Used a Fedora Media Writer to write it on 32gigs usb stick.
* Laptop Dell XPS 9560 ( 4k screen, 16gigs of memory, 1to SSD 960 Evo )
* Boot goes fine
* Launch installer, goes through different steps, everything goes smoothly
* Install fails
* Logs says that it there was "no space left on device" for each files installer tries to download.
  
**Expected behavior**
Install goes fine

**Comment by mdhorn** [comment]
@olivierchatry Thanks for the report.
Can you please attach the following files:
/root/pre-install-clr-installer.yaml
/root/clr-installer.log

These would be in the live image's /root directory.
You may wish to review the contents to ensure you there is not personal data you do not wish to share (like username or serial numbers of media).

Without some details and/or log, we can't really respond to this issue.

**Comment by olivierchatry** [comment]
Seems like it cames from my partionning. Used the whole disk ( destructive
option ), and everything went ok.

I cannot get the log anymore. But I had a window partition, and a fedora
partion. The clr Linux one was right in the middle if that helps. Sorry to
not be able to give a log.

**Comment by mdhorn** [comment]
@olivierchatry The install for a desktop we should be requiring about 20GB for the root '/' partition to ensure there is enough space for the OS, /home, /var/ ...

I know in this latest release we are verifying the minimum size for Safe and Destructive partitions; did you use Advanced?

**Comment by olivierchatry** [comment]
Nope and I had 128 gigs free. Side note : would be good to display na big
warning when using destructive mode. Did not check, and whole partitions
are gone. Not a problems for me, but I'm sure someone will lose data at
some point.

**Comment by mdhorn** [comment]
@olivierchatry Okay, thanks for the feedback.
Sounds like you were able to get installed. Without some logs or a config, sadly we won't be able to do much about determining what went wrong before.

When you do a destructive installation, you should have seen a confirmation box like this before starting the install:

![warning](https://user-images.githubusercontent.com/12535259/65083056-610d7000-d95c-11e9-9324-4b11033d85b2.png)


We are open to additional feedback on how to better convey the risk if you have suggestions.
