### ISSUE TITLE
Replace gometalinter with golangci-lint

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#527]
**Is your feature request related to a problem? Please describe.**
Go meta linter has been deprecated and needs to be replaced.

**Describe the solution you'd like**
Replace
https://github.com/alecthomas/gometalinter/
with
https://github.com/golangci/golangci-lint

For reference, review what was done for mixer-tools
https://github.com/clearlinux/mixer-tools/pull/610

**Comment by jwakre** [comment]
gometalinter is not responsible for the large number of false-positive errors when running the linter. I created #539 to document this problem.

**Comment by mdhorn** [comment]
Fixed in clr-installer release [2.3.1](https://github.com/clearlinux/clr-installer/releases/tag/2.3.1) in Clear Linux OS release 31270 or later.
