### ISSUE TITLE
Refactor storage code to support additional features 

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#530]
The code for storage has become overly complex and needs to refactored to more easily enable additional features like LVM and support encryption on multiple file systems.

**Describe the solution you'd like**
The modules need to be more logically structured and remove the parallel structures like blockdevice and targetmedia.

This should be done before the other storage-related backlog items.

**Comment by karthikprabhuvinod** [comment]
**Some notes:**

1.) In the storage.go I see two structs i.e: BlockDevice and BlockDeviceYaml. Can we merge them?

[https://github.com/clearlinux/clr-installer/blob/master/storage/storage.go#L37-L82](url)

2.) Looks like an good idea to keep PartitionPartition a field of Blockdevice as it natural to think of a blockdevice to keep track of its parts

**Comment by mdhorn** [comment]
> https://github.com/clearlinux/clr-installer/blob/master/storage/storage.go#L37-L82

Very like that the required YAML tag could be added to the other struct.

**Comment by mdhorn** [comment]
Fixed in clr-installer 2.6.1, Clear Linux OS 33300 or higher.
