### ISSUE TITLE
clr-installer should support a hook for post-processing the image file

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#531]
It would be nice for clr-installer to produce these types of images instead of having devops run a separate script to produce them.  

* cloud
* cloudguest-native
* cloudguest
* pxe
* azure
* hyperv
* vmware

**Comment by mdhorn** [comment]
@bktan8 The clr-installer is used by DevOps to make those images.
The YAML files and install hooks are published for use.

I'm not sure what the ask is here?

**Comment by bktan8** [comment]
clr-installer produces the raw image, but devops has to run another script to convert it to another format, say a hyperv (vhdx) image.

**Comment by mdhorn** [comment]
The DevOps should be publishing the required scripts along with the other post install scripts.

**Comment by mdhorn** [comment]
What we should add is a post-install hook that allows a script to be run against the final image file. That is a more generic solution to handle whatever future format come along.

**Comment by mdhorn** [comment]
### Requirement
Add `post-image` hook to the YAML file which is passed the location of the final image file for any further changes that are needed.

The DevOps (or any user) can add a post-processing script to the configuration file.

**Comment by mdhorn** [comment]
post-image hook is available in clr-installer 2.4.1 starting with Clear Linux OS release 32510 or higher.
