### ISSUE TITLE
Kernel panic not syncing vfs

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/clr-installer#534]
![image](https://user-images.githubusercontent.com/12841320/65339725-6da7f780-dbec-11e9-9203-95997d123dba.png)
![image](https://user-images.githubusercontent.com/12841320/65339737-70a2e800-dbec-11e9-8c71-727bce5f32c9.png)
![image](https://user-images.githubusercontent.com/12841320/65339746-74366f00-dbec-11e9-9413-155279bc71c4.png)

i used to run deepin on my system. then i installed clear linux using “safe installation mode” after alocating around 25GB unallocated space. 

after successful install, on boot it failed.

actually on boot it loads to the grub loader (probably residue of deepin) 

and 

when i press F12 and load clear linux by selecting “linux bootloader” , it leads to kernel panic

**Comment by mdhorn** [comment]
@nazar2sfive In cases where the installation worked, but it fails to boot the first thing to check is if you have the latest firmware (BIOS/UEFI )from your motherboard manufacturer. We've seen numerous cases where booting issues are resolved by updating to the most recent firmware.

if it still persists, we have to see if we can find a kernel or clear-boot-manager expertise to assist.

**Comment by nazar2sfive** [comment]
i have dell inspiron 3421.
driver update check shows it has all updates installed.

and i think it was 3 years back when i had updated my BIOS/UEFI firmware.
![image](https://user-images.githubusercontent.com/12841320/65366633-50a01280-dc46-11e9-9b0b-cf125bd8465b.png)

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/65366640-70cfd180-dc46-11e9-8132-bde87d096be6.png)


this i had already installed

**Comment by nazar2sfive** [comment]
version : clear-31080-live-desktop.iso

failed again 

![DSC_0190](https://user-images.githubusercontent.com/12841320/65511497-11e4b380-def7-11e9-95f1-4b473df01935.JPG)

**Comment by mdhorn** [comment]
@nazar2sfive What is the make and model of the hard drive?  How is it attached to the motherboard?

@miguelinux Have any idea what this kernel panic is?

**Comment by nazar2sfive** [comment]
harddrive model = WDC WD5000LPVX-75V0TT0

**Comment by nazar2sfive** [comment]
version : clear-31090-live-desktop.iso

![DSC_0196](https://user-images.githubusercontent.com/12841320/65832916-59e64a80-e2ea-11e9-900d-42d7fcd228fe.JPG)

![image](https://user-images.githubusercontent.com/12841320/65832937-74b8bf00-e2ea-11e9-93ee-bed81840df4f.png)

![image](https://user-images.githubusercontent.com/12841320/65832945-87cb8f00-e2ea-11e9-8b1e-376a4936d926.png)

![image](https://user-images.githubusercontent.com/12841320/65832963-b34e7980-e2ea-11e9-92a3-920dd0d0f5f4.png)

after downloading 2.1Gb of data and installing the system with "installation successful" .

it failed again .

kernel panic.

**Comment by mdhorn** [comment]
@nazar2sfive Can you boot from the ISO, mount the root partition and extract the installation files?
/root/clr-installer.log and /root/clr-installer.yaml
That might provide some useful information for the kernel folks at to why this might not be booting.

Also, if you have the means to make a video of the failing boot sequence, removing 'quiet' from the kernel arguments might help too.

**Comment by nazar2sfive** [comment]
@mdhorn 
how to remove "quiet" from kernel arguments?

**Comment by mdhorn** [comment]
During the boot sequence:
![Screen Shot 2019-10-01 at 4 24 44 PM](https://user-images.githubusercontent.com/12535259/66007697-4660ee00-e468-11e9-848a-1db7c5814b98.png)

Hit 'e' when Clear Linux OS is highlighted. Then arrow to the right to find the 'quiet' option from the boot command and remove it:
![Screen Shot 2019-10-01 at 4 25 23 PM](https://user-images.githubusercontent.com/12535259/66007750-6e505180-e468-11e9-8c1e-17a09210de56.png)

**Comment by nazar2sfive** [comment]
@mdhorn i had to choose clear linux by choosing boot menu by hitting F12. when i choose clear linux option and hit e- it doesnot lead to such option.

![image](https://user-images.githubusercontent.com/12841320/66050373-d5473680-e54c-11e9-8cbb-cf7366c1c444.png)

if i dont choose via F12, it directly leads to grubloader (of my prev ubuntu install)

**Comment by nazar2sfive** [comment]
version : clear-31140-live-desktop

i tried "safe installation", "advanced installation" method... both failed.

in past i used to have such problem if my ubuntu install couldnot find the proper install partitition. 

i don't want to go 'destructive install'

**Comment by mdhorn** [comment]
@nazar2sfive You would first select "Linux bootloader" from the boot menu, then follow the steps for the clear-boot-manager I noted.

**Comment by mdhorn** [comment]
> version : clear-31140-live-desktop
> 
> i tried "safe installation", "advanced installation" method... both failed.
>
When you mean they both fail, you mean the install worked, but they failed to boot?

 
> in past i used to have such problem if my ubuntu install couldnot find the proper install partitition.
> 
> i don't want to go 'destructive install'
> 
> @mdhorn is there any way to change that parameter from the install location itself.
> i could open the install drive using iso usb boot and "root" edit the required file.

You could mount the /boot partitions while booted from the ISO and modfity the boot config.
mkdir /mnt/boot
mount <boot part> /mnt/boot
cd /mnt/boot/loader/entries
vi Clear-linux-native-<YOUR_KERNEL>.conf
On the "options" line, remove the work 'quiet'

**Comment by nazar2sfive** [comment]
```
lrlinux@clr-live/run/media/clrlinux/root $ fdisk -l
fdisk: cannot open /dev/loop0: Permission denied
fdisk: cannot open /dev/sda: Permission denied
fdisk: cannot open /dev/sdb: Permission denied
clrlinux@clr-live/run/media/clrlinux/root $ fdisk -l /dev/sda
fdisk: cannot open /dev/sda: Permission denied
clrlinux@clr-live/run/media/clrlinux/root $ sudo fdisk -l /dev/sda
Disk /dev/sda: 465.8 GiB, 500107862016 bytes, 976773168 sectors
Disk model: WDC WD5000LPVX-7
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 1048576 bytes
Disklabel type: gpt
Disk identifier: B398B6E5-070F-4A00-82D4-1CCF2C657AA2

Device         Start       End   Sectors   Size Type
/dev/sda1       2048    292863    290816   142M EFI System
/dev/sda2     292864    600063    307200   150M EFI System
/dev/sda3     600064   1648639   1048576   512M Linux swap
/dev/sda4   48240640 227287039 179046400  85.4G Linux filesystem
/dev/sda5    1648640  48240639  46592000  22.2G Linux root (x86-64)
/dev/sda6  229462016 229494783     32768    16M Microsoft reserved
/dev/sda7  229494784 395141119 165646336    79G Microsoft basic data
/dev/sda8  395141120 976773119 581632000 277.4G Microsoft basic data

Partition table entries are not in disk order.
clrlinux@clr-live/run/media/clrlinux/root $ sudo mount /dev/sda2 /mnt/boot
clrlinux@clr-live/run/media/clrlinux/root $ cd /mnt/boot
clrlinux@clr-live/mnt/boot $ ls
EFI  loader
clrlinux@clr-live/mnt/boot $ cd loader
clrlinux@clr-live/mnt/boot/loader $ ls
entries  loader.conf
clrlinux@clr-live/mnt/boot/loader $ cd entries
clrlinux@clr-live/mnt/boot/loader/entries $ ls
Clear-linux-native-5.3.1-843.conf
clrlinux@clr-live/mnt/boot/loader/entries $ 


clrlinux@clr-live/mnt/boot/loader/entries $ cat Clear-linux-native-5.3.1-843.conf 
title Clear Linux OS
linux /EFI/org.clearlinux/kernel-org.clearlinux.native.5.3.1-843
initrd /EFI/org.clearlinux/freestanding-00-intel-ucode.cpio
initrd /EFI/org.clearlinux/freestanding-i915-firmware.cpio.xz
options root=PARTUUID=ce0d75d7-0e95-4bf6-86b1-45e16fd08850 console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcu_nocbs=0-64 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs tsc=reliable rw 
clrlinux@clr-live/mnt/boot/loader/entries $ 


```
i removed the "quiet" entry but no luck. there is no extra information shown on boot and same panic.

**Comment by nazar2sfive** [comment]
@mdhorn just a request: i think we need failsafe boot (on next boot) if such panic occurs

**Comment by nazar2sfive** [comment]
```
root@clr-live/home/clrlinux # blkid
/dev/loop0: TYPE="squashfs"
/dev/sda1: LABEL_FATBOOT="boot" LABEL="boot" UUID="8F21-68B9" TYPE="vfat" PARTLABEL="EFI" PARTUUID="8256fc5b-83eb-4869-86be-7af77866ac6b"
/dev/sda2: LABEL_FATBOOT="BOOT" LABEL="BOOT" UUID="0EB6-9DD0" TYPE="vfat" PARTLABEL="CLR_BOOT" PARTUUID="904e1bc1-c148-4c38-8b32-f5846d93055c"
/dev/sda3: LABEL="swap" UUID="df219c27-3037-4cdd-b1b9-c38111b74835" TYPE="swap" PARTLABEL="CLR_SWAP" PARTUUID="4f455966-85c0-4cdd-8e92-c8775bcbbeae"
/dev/sda4: UUID="1c3d5fdd-60e7-420c-8078-4215984438d7" TYPE="ext4" PARTUUID="6e674c2c-1285-4186-b6b5-c0591a4f0423"
/dev/sda5: LABEL="root" UUID="90e589c4-7b97-4e93-823b-9e11a396ad2f" TYPE="ext4" PARTLABEL="CLR_ROOT" PARTUUID="ce0d75d7-0e95-4bf6-86b1-45e16fd08850"
/dev/sda6: UUID="c6e6283e-d0a4-4bea-816f-48c9e4aa78ca" TYPE="ext4" PARTLABEL="Microsoft reserved partition" PARTUUID="eb073250-8706-42f0-af54-0e61710bf8a9"
/dev/sda7: UUID="267408017407D28B" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="48f93059-69cb-4ff1-abbe-c964d39d2378"
/dev/sda8: LABEL="New Volume" UUID="4416017316016770" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="70a12d5f-f0ed-4025-87f2-3a592843c30c"
/dev/sdb1: UUID="2019-10-01-09-03-16-00" LABEL="CLR_ISO" TYPE="iso9660" PTUUID="10c7dec4" PTTYPE="dos" PARTUUID="10c7dec4-01"
/dev/sdb2: SEC_TYPE="msdos" LABEL_FATBOOT="\"CLEAR_EFI\"" LABEL="\"CLEAR_EFI\"" UUID="6544-C11D" TYPE="vfat" PARTUUID="10c7dec4-02"
root@clr-live/home/clrlinux # 



```

**Comment by nazar2sfive** [comment]
![DSC_0197](https://user-images.githubusercontent.com/12841320/66097519-660a2a80-e5be-11e9-9e89-9aac5a6e1350.JPG)

**Comment by nazar2sfive** [comment]
@mdhorn i found that EFI entry was pointing to godknows-what partition UUID. i changed the UUID manually. finally got a boot to clear linux but nonfunctional. 

Both mousepad and keyboard of my system is not working. 
i comes to the login screen and boom - nothing. INPUTS not working.

![DSC_0198](https://user-images.githubusercontent.com/12841320/66097588-aec1e380-e5be-11e9-8f21-000efc8428c7.JPG)

**Comment by nazar2sfive** [comment]
@mdhorn 
problem solved.

problem was : UUID that clear linux installer denoted to my partition were wrong.

solved by manual editing of the UUID.

suggestion
1. clear linux needs a failsafe boot option on bootmenu.
2. clear linux will create a seperate EFI boot partition rather than utilizing the one created by windows 10. thus creating multiple EFI entry and probably confusing UUID. i want clr-installer to identify  EFI created by windows 10 and append on that rather than creating new partition. Both safe and advanced parition option force us to use new EFI boot partition.

**Comment by mdhorn** [comment]
@nazar2sfive  Regarding re-using Windows EFI partition, that is currently possible using Advanced Installation;  you add the partition name CLR_BOOT to the existing Windows EFI.

Until clr-boot-manager has a few more additions, the Safe Installer will remain as-is.
There are several changes coming to support new clr-boot-manager features which you can follow here;
https://github.com/clearlinux/clr-installer/issues/517
