### ISSUE TITLE
installation doesnot resume after net disconnection.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/clr-installer#536]
version : clear-31070-live-desktop.iso

i have yet not been able to make my broadcom 34142 to work in clear linux system. so i rely on usb teether to install clear linux.

now the problem with clear linux install is it double downloads the same file during installation process due to lack of offline install.

also the clear linux server is slow at my area. i have 50Mbps speed of internet but bandwithmeter shows only 200-300 Kb/s download ... Sometimes my internet gets interupted due my loose USB cable which i have. It happened to me toady. i had already downloaded 1.43 GB of data . USB got loose on my android phone, net was disconnected. when i reconnected the usb teether the download didn't resume. so i had to restart my pc and start the process again.

conclusion :
clear linux installation fails if net gets dissconnected by some means. it won't resume from the last lost signal to continue with install.

![Screenshot from 2019-09-23 06-11-07](https://user-images.githubusercontent.com/12841320/65405007-a5848a00-ddfa-11e9-88c1-8125a9eb0d95.png)

(here after successful restablishment of the internet, it fails to pull the remaining data it needs.)

**Comment by jwakre** [comment]
At this point swupd is running, so this is an issue with swupd and unstable internet connections. The offline installer will avoid this problem for installs that do not use any additional bundles. Additional bundles will not exist in the ISO and still need to be downloaded over the network

@mdhorn - Move to swupd for unable to download with unstable network connection?

**Comment by mdhorn** [comment]
There appear to be three issues here:
1. Unabled network interface -- this belongs back in the Distribution to determine if we will support and what changes (kernel) are needed.
2. Request for offline installation support -- this is already addressed by #504 and will be released this week
3. Request swupd to be able to continue from network loss and recovery; that belongs in swupd

@miguelinux Do we know anything about support for the network interfaced noted?
@otaviobp I don't see any existing issue for network recovery; is this something we could add to the swupd-client backlog?

**Comment by mdhorn** [comment]
@otaviobp Is recovering from a network connect change something that swupd would even consider? Or re-using partially downloaded content?  If so, then I might transfer this to swupd for long-term consideration; otherwise this will likely just get closed.

@miguelinux Should we ask the user to open a new issue in https://github.com/clearlinux/distribution for support of the broadcom 34142 network interface?

**Comment by nazar2sfive** [comment]
@mdhorn 
waiting for offline install to work. then swupd resume won't matter

@mdhorn 
https://community.clearlinux.org/t/how-to-install-driver-for-broadcom-43142/1614/28

**Comment by mdhorn** [comment]
As of version 31230 the live desktop and server installer images have support for offline installs. Installer images can be downloaded at https://clearlinux.org/downloads
