### ISSUE TITLE
Text-base UI should ensure root account is secured for the install target

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#544]
Currently, when you install the server version, root's password is left unset through these scenarios:
1) If you just fulfill the "Required" settings, root is left unset and no user is added
2) If you add a user in the "Advanced" tab, unless the user is specifically set as administrator, the root password is left unset.

Scenario #2 is the one I'm more concerned about because you added a user, but you may forget to set a password for root.  Albeit a low probability, someone can connect to the system and hijack the root account.  

My proposal is to move the "add user a new user" screen to the "Required" tab (like the Desktop installer) and require that a user is added and the "Administrator" checkbox is set by default.  Secure the root account by default.  Don't leave it open.

**Comment by mdhorn** [comment]
@bktan8 Historically, the text-based UI is for server installs which generally do not have user accounts.

The requirement should be:
- Set the root password
OR
- Create a user account with Administrator privileges

Yes, as a requirement it would move to the required screen.

**Comment by jwakre** [comment]
The installer will require that a user account with admin privileges is created, but support will not be added to create a root user at install time.

**Comment by mdhorn** [comment]
Fixed in https://github.com/clearlinux/clr-installer/releases/tag/2.3.2

**Comment by mdhorn** [comment]
Available in Clear Linux OS release 31380 and higher.
https://clearlinux.org/downloads
