### ISSUE TITLE
Error running clr-installer 

### ISSUE THREAD

**Issue by thbui** [clearlinux/clr-installer#549]
Hi,
I'm following the tutorial to install ACRN VM and got error in the clr-installer
The tutorial can be found here: https://projectacrn.github.io/latest/getting-started/acrn_ootb.html

Attached are the error log and clr-installer.log and the pre-install-clr-installer.yaml file.

Thanks,
Tuan Bui

[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3660072/clr-installer.log)
[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/3660079/pre-install-clr-installer.yaml.txt)
[error.log](https://github.com/clearlinux/clr-installer/files/3660081/error.log)

**Comment by jwakre** [comment]
From the attached log:

` 2019/09/26 14:47:24 [DBG] chrootDir=/tmp/install-929566183: ./service-os-post.sh: Permission denied`

@thbui What are the permissions for `service-os-post.sh`? Is it executable?

**Comment by thbui** [comment]
Thank you John,
That solved my problem.
Tuan Bui
