### ISSUE TITLE
Allow users to specify the format for the latest version

### ISSUE THREAD

**Issue by jwakre** [clearlinux/clr-installer#559]
**Is your feature request related to a problem? Please describe.**
When generating images or installing the latest version (version 0), the latest version in the host system's format will be selected. This behavior is not always desirable, especially for downstream mixes which can have format numbers that are not in sync with the host system. To better support downstream mixes, the format number used to specify the latest version should be configurable.

**Describe the solution you'd like**
The format value passed to swupd should be configurable on the command line and config file.

**Describe alternatives you've considered**
In the future, it would be nice for swupd/mixer synchronize their compatibility with a manifest version instead of a format number.

**Comment by mdhorn** [comment]
Fixed in clr-installer release [2.3.1](https://github.com/clearlinux/clr-installer/releases/tag/2.3.1) in Clear Linux OS release 31270 or later.
