### ISSUE TITLE
Support creating image with dnf

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#56]
Support adding RPMs via dnf after initial os-core install via swupd.

This is primarily for testing and validation use scenario where newly created version of RPMs need to be tested, but the image is only around for testing and won't be updated.

**Comment by bryteise** [comment]
The feature should be installing via dnf instead of swupd as there would be no available os-core in this case.

**Comment by dorileo** [comment]
The only user for this feature would be the pre release tests performed by devops (BAT or BBT tests) however George told me we have such use case anymore, the new strategy involves creating an empty image and the content is installed with mixer. For that I introduce the feature with the commit in the PR #113 . I'm closing this issue, please open if you understand we still need the feature.
