### ISSUE TITLE
Give us option to install "extras" like media codec, driver(eg my broadcom 43142 wifi card)

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/clr-installer#560]
![image](https://user-images.githubusercontent.com/12841320/66116906-43463900-e5f3-11e9-9697-cc937087479b.png)

i wish clear linux to give us option to install following during install like UBUNTU does.
- media codes 
- driver for nvidia, broadcom (all proprietary drivers)..

**Comment by mdhorn** [comment]
@nazar2sfive We will need to investigate, but currently we do not ship anything that is not 100% open source.
@ahkok Is this something we should consider? Or is it out of scope for Clear Linux in the near term?

**Comment by ahkok** [comment]
This already has been discussed in the main issue tracker.
