### ISSUE TITLE
option to choose DE?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/clr-installer#563]
i am loving using kde in clear linux.

![image](https://user-images.githubusercontent.com/12841320/66196644-9fbf5c00-e6b8-11e9-9773-b244f3468d51.png)

![image](https://user-images.githubusercontent.com/12841320/66196708-b9f93a00-e6b8-11e9-992b-216623949e7d.png)
requesting for option to choose the desktop environmnent during install.

**Comment by mdhorn** [comment]
@nazar2sfive Thank for the request.

Clear is currently focused on and investing validation efforts in Gnome desktop environment.

We could consider adding KDE desktop to the Advance bundle selection, but that would not be apart of the pre-cached content for installing without network -- aka it would require a network connection for selecting KDE.

One immediate concern I have is in my quick testing of KDE, is that I can not unlock the desktop once switching to KDE. That is just the first bug I found, so I'm not sure it is validated enough to allow this as an option yet -- at least at install time.

**Comment by nazar2sfive** [comment]
@mdhorn 

> One immediate concern I have is in my quick testing of KDE, is that I can not unlock the desktop once switching to KDE

wow, exactly i have been facing the same problem. so i had removed the whole password.
