### ISSUE TITLE
Fix gocyclo linter errors for main.go

### ISSUE THREAD

**Issue by jwakre** [clearlinux/clr-installer#568]
**Is your feature request related to a problem? Please describe.**
The main.go file was disabled for the gocyclo linter when switching to golangci-lint.

**Describe the solution you'd like**
The main.go file is enabled for the gocyclo-linter and passing.

**Comment by mdhorn** [comment]
Fixed in installer release [2.5.0](https://github.com/clearlinux/clr-installer/releases/tag/2.5.0) found in Clear Linux OS release 32980 or greater.
