### ISSUE TITLE
Variable expansion in installer YAML files only expands first variable

### ISSUE THREAD

**Issue by tomlanyon** [clearlinux/clr-installer#579]
**Describe the bug**
Expanding variables in YAML config files (e.g. in post-install or pre-install hooks) only expands the first variable it encounters.

**To Reproduce**
1. Run a YAML config with multiple valid variables in a post-install cmd, e.g.
   post-install:
     - cmd: "[[ ${chrooted} -eq 0 ]] && chroot ${chrootDir} ...."

**Expected behavior**
Both vars should be expanded to their coutnerpart values.

**Environment (please complete the following information):**
 - Clear Linux OS Version: n/a
 - Installer Version [clr-installer -v]: HEAD
 - Platform: [hardware infomation]: n/a

**Additional context**
utils.ExpandVariables returns early

**Comment by mdhorn** [comment]
https://github.com/clearlinux/clr-installer/releases/tag/2.3.2

**Comment by mdhorn** [comment]
Available in Clear Linux OS release 31380 and higher.
https://clearlinux.org/downloads
