### ISSUE TITLE
"Warning: CLR_SWAP must be linux-swap" prevents from installing Clear Linux OS Server

### ISSUE THREAD

**Issue by jcnils** [clearlinux/clr-installer#589]
**Describe the bug**
I am not able to install Clear Linux OS Server using live USB using the Advanced Installation options on Installation Media.

I am using this tutorial: https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html

**To Reproduce**
1. Create Live USB
2. On BIOS bot the USB using UEFI
3. Configure Everything
4. Select Installation Media Option
5. Select Advanced Installation
6. Create partitions following the tutorial steps
![image](https://user-images.githubusercontent.com/961151/67043670-d6996700-f0e7-11e9-9481-08071dbee69a.png)
7. Write and Close
8. The message "Warning: CLR_SWAP must be linux-swap" will appear and the button to start the installation will disappear.
![image](https://user-images.githubusercontent.com/961151/67043629-be294c80-f0e7-11e9-98bd-0f7641e28e26.png)

**Expected behavior**
Be able to install using the configuration suggested from the website.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31310
 - Installer Version 2.3.1
 - Platform: 
[hardware.txt](https://github.com/clearlinux/clr-installer/files/3741228/hardware.txt)

**Additional context**
I tried to install using the destructive method as well, but I got some errors that might me unrelated.
[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3741236/clr-installer.log)

[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/3741239/pre-install-clr-installer.yaml.txt)

**Comment by mdhorn** [comment]
@jcnils Thank for you report.

There is currently an undetermined issue with NVME drives in the latest builds, see:
https://github.com/clearlinux/clr-installer/issues/588

Could you retry this installation with 
https://download.clearlinux.org/releases/31290/clear/clear-31290-live-desktop.iso

**Comment by jcnils** [comment]
@mdhorn Sorry for the delay.
I tried both live desktop and server 31290 and they worked fine.
Thank you very much.

Please let me know if I can help with any tests or information.

**Comment by mdhorn** [comment]
@jcnils Thank you for verifying this.
We could the problem in https://github.com/clearlinux/clr-installer/issues/588 and it is resolved.
All releases from 31370 forward are now verified to work.
