### ISSUE TITLE
Enable Mixer Integration

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#59]
Currently, mixer uses an ister JSON template as part of the build process.
See https://github.com/clearlinux/mixer-tools/pull/427

Need to also support clr-installer YAML files.

At least two weeks before enabling this change in Mixer, coordinate with the contact leads for the business units and COEs to ensure they know that this change is coming.
Stanley Phoong is a good first contact. @leopck

**Comment by dorileo** [comment]
Do you mean implement what is specified on #33 ?

**Comment by mdhorn** [comment]
This might be more of a reminder to update Mixer to use our new YAML files so that it can take either ister JSON or clr-install YAML

**Comment by dorileo** [comment]
[This](https://github.com/clearlinux/mixer-tools/blob/1f7b1d052068c86acb3c4fa0409143857ee6bd3e/builder/builder.go#L1734) is the mixer relevant code

**Comment by mdhorn** [comment]
https://github.com/clearlinux/clr-installer/issues/193 should be completed first.

**Comment by reaganlo** [comment]
@mdhorn Currently **mixer** uses **ister** to build images. i.e **mixer** has wrapper code around **ister** to build images. I believe this enhancement request is to replace **ister** with **clr-installer** in **mixer**. 
If yes, the user would be required to use the clr-installer YAML file just like how they used the ister JSON file. I don't think #193 is a prerequisite for this enhancement. Thoughts?

**Comment by mdhorn** [comment]
@reaganlo Several customers are already using mixer with JSON files to build their images. The request is to have a migration process to the customers can transition from JSON (for ister) to YAML (for clr-installer) with minimum impact to the users.
So we probably need to have mixer support both JSON and YAML for an amount of overlap time. If you provide JSON, run ister, if YAML, run clr-installer.

**Comment by mdhorn** [comment]
After discussion with the Mixer team, it was decided that they prefer depreciating the current build command in mixer instead of switch from ister to clr-installer.
The will be updating mixer to direct the user to running clr-installer manually to generate an image.

**Comment by leopck** [comment]
@mdhorn So no more `mixer build image`? If I understand correctly?

**Comment by mdhorn** [comment]
@leopck That is the current plan. Most likely 'mixer build image' will start providing a warning with instructions on using clr-installer to generate the image.
clr-installer will already consume most existing ister.py JSON files and provide the equivalent [clr-installer YAML file](https://github.com/clearlinux/clr-installer/blob/master/scripts/InstallerYAMLSyntax.md) for later reuse.

**Comment by mdhorn** [comment]
The decission was made to keep the build command in mixer.
clr-installer replaced ister with PR
https://github.com/clearlinux/mixer-tools/pull/649
First mixer release: v6.1.0
First Clear Linux OS release: 31730
