### ISSUE TITLE
Enable retries to download installation configuration file via kernel params

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#591]
In some cases, we're seeing that attempt to download the installation template file fails.  My guess is that it's due to the network being slow to come up and thus an IP address is not available.  I would like to propose that we do 5 retries before failing the installation.

**Comment by mdhorn** [comment]
@bktan8 This change needs to be made in the clr-installer as it is the application downloading the YAML configuration file.

**Comment by mdhorn** [comment]
First released in 2.3.3, in Clear Linux OS 31530

**Comment by bktan8** [comment]
Awesome work @mdhorn!  Thanks for reporting release version.
