### ISSUE TITLE
Create an image generation config for OSVs

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/clr-installer#600]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
For OSVs who generate images, clr-installer should not be more than a thin wrapper around swupd that also happens to call additional post-install configuration scripts.  This would result in images that are generated exclusively by content swupd owns containing changes from this that are explicitly made by scripts.  A config option in the YAML file would be nice, named something like 'propagateHostSettings: false', so that the CLI remains clean and we change this behavior on a per-image basis.  A subcommand is probably not the right approach because it would have the CLI devolve into something similar to the mixer CLI.

**Describe alternatives you've considered**
N/A

**Additional context**
In the case an OSV is using Clear Linux as the host OS to generate images, any configurations on the host should not propagate to the images that get generated.  If the OSV wants to change the swupd mirror on the host OS, they should be able to without any consequences to the images that are generated.  The host OS configuration should remain isolated/independent from the image generation process.  In the case of proxies, the clr-installer process should be able to use the ones defined from the environment, but whether configurations in /etc regarding proxies (or environment variables in general) get propagated would be toggled by the config option.

**Comment by mdhorn** [comment]
We will implement a mode that prevents copying any host configurations, but the installer will always be dependent upon the host OS for completing the installation for networking tools, disk tools, etc.

**Comment by mdhorn** [comment]
Fixed in Clear Installer release [2.3.7](https://github.com/clearlinux/clr-installer/releases/tag/2.3.7)
Available in Clear Linux OS 31930 or later
https://clearlinux.org/downloads
