### ISSUE TITLE
Installer froze, then closed

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/clr-installer#612]
**Describe the bug**
The (text) installer froze after selecting the keyboard layout functionality, then closed on its own.

**To Reproduce**
1. Launch clr-installer
2. Select the keyboard map option (it was showing "us") and press Enter

**Expected behavior**
A list of keyboard layout options is shown, where I can select one.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31700
 - Installer Version 2.3.4
 - Platform: Coffee Lake NUC

**Additional context**
[clr-installer.log](https://github.com/clearlinux/clr-installer/files/3893451/clr-installer.log) attached

**Comment by mdhorn** [comment]
@thiagomacieira Can you also attached the /root/pre-install-clr-installer.yaml as well?

**Comment by mdhorn** [comment]
@thiagomacieira I've not been able to reproduce this using the clear-31700-live-server.iso in a VM on or on hardware.
The command that failed was `localectl set-keymap us` with a `Failed to set keymap: Connection timed out` which is quite odd.
Is this a repeatable failure? If so, I can stop by to investigate.

**Comment by thiagomacieira** [comment]
> @thiagomacieira Can you also attached the /root/pre-install-clr-installer.yaml as well?

There's no such file.

> Is this a repeatable failure? If so, I can stop by to investigate.

I don't know, clr-installer won't start again.
```
# clr-installer
Invalid Time Zone 'UTC'
# echo $?
1
# cat clr-installer.log
2019/11/26 19:06:38 [DBG] Log Level set to LogLevelDebug (4)
2019/11/26 19:06:38 [INF] clr-installer: 2.3.4, built on 2019-11-21_01:11:17_UTC
2019/11/26 19:06:38 [DBG] Loading config file: /usr/share/defaults/clr-installer/clr-installer.yaml
2019/11/26 19:06:38 [INF] Querying Clear Linux version
2019/11/26 19:06:38 [DBG] PrivateIP: Found IP: 10.54.69.24, Private IP?: true
2019/11/26 19:06:38 [INF] NOTICE: Enabling Telemetry preferred by default on internal networks.
2019/11/26 19:06:38 [DBG] localectl list-keymaps --no-pager
2019/11/26 19:06:38 [DBG] Using default shellProxy.DefaultGetProxyValue
2019/11/26 19:06:38 [DBG] [Previous line repeated 4 times]
2019/11/26 19:06:38 [DBG] cmd.Env: []
2019/11/26 19:06:38 [DBG] timedatectl list-timezones
2019/11/26 19:06:38 [DBG] Using default shellProxy.DefaultGetProxyValue
2019/11/26 19:06:38 [DBG] [Previous line repeated 4 times]
2019/11/26 19:06:38 [DBG] cmd.Env: []
2019/11/26 19:07:03 [ERR] Invalid Time Zone 'UTC'
```

**Comment by thiagomacieira** [comment]
Ok, I'm seeing weird things in the terminal now (sorry, copy & paste impossible):
```
[913.4520233] systemd[1]: Failed to start Time & Date Service.
[1427.824476] systemd-coredump[880]: Failed to get COMM: No such process
[1462.502990] systemd[1]: failed to start Journal Service
```
and more other, weird errors.

Let me wait for swupd to finish installing python-extras on the USB stick to see if things come back to normal.

**Comment by thiagomacieira** [comment]
Looks like the issue is that D-Bus was timing out, because I was running "swupd bundle-add" in another terminal. The USB stick is **SLOOOOOW**.
