### ISSUE TITLE
Hard Drive encryption changes the selected drive

### ISSUE THREAD

**Issue by maljaroudi** [clearlinux/clr-installer#614]
**Describe the bug**
The hard drive encryption option changes the desired hard drive back to the first one on the list. Forgot to double check the first time and ended up wiping my secondary drive with personal files instead. 

**To Reproduce**
1. Go to 'Select Installation Media'
2. Choose 'Destructive Installation ' and select the second drive if you have two
3. Check "Enable Encryption"
4. Enter a passphrase and confirm
5. The drive selected will be switched back to the first on the list/ default

**Expected behavior**
The installer should never change the selected drive after the encryption is checked. Users might forget to double check that it changed back and end up losing their data.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31700
 - Installer Version : Latest ISO for version 31700
 - Platform: 2 Samsung SSDs. 1Tb, 256Gb.

**Comment by mdhorn** [comment]
@maljaroudi Are you using the live-server or live-desktop? Was the problem seen in the text-based installer or the graphical version?

**Comment by maljaroudi** [comment]
> @maljaroudi Are you using the live-server or live-desktop? Was the problem seen in the text-based installer or the graphical version?

Sorry i didn't include that in the report. 
live-desktop graphical version is what i used.

**Comment by mdhorn** [comment]
@maljaroudi Thank you for the bug report. I was able to reproduce this.

**Comment by mdhorn** [comment]
Fixed in Clear Installer release 2.3.7
Available in Clear Linux OS 31930 or later
https://clearlinux.org/downloads
