### ISSUE TITLE
clr-installer is stuck with lvm group existing on system

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/clr-installer#623]
Hi Clear Linux team,

I tried to do a new installation of the CL operating system.
But we have an older operating system on disk with lvm.
I chose a destructive installation.
But this does not work.
By simple debugging, the lvm group is still active in CL.
Can this problem be repaired?
Maybe the lvm group should be stopped and removed by clr-installer.

Thank you CL team.

[clr-installer.log](https://github.com/clearlinux/distribution/files/3936612/clr-installer.log)

[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/distribution/files/3936613/pre-install-clr-installer.yaml.txt)

**Comment by ionutnechita** [comment]
Hi @mdhorn,

I tried to install CL, but the error still appears.
Use for installation Clear Linux 31890.
I will make a new ticket, also with this problem.

**Comment by mdhorn** [comment]
@ionutnechita  Sorry for the confusion, but this is not released yet. It is merge into master, but we have not completed a new release of the installer yet.  The Kanban board automatically is closing issues when they are merged.

The next release is planned for December 16 or 17.  Once the release is completed, it will take 1-3 business days before it is in the Clear Linux OS and used for the latest installer images.

Once it is released, we update the Issue with the Installer release version and which version of Clear Linux OS.

**Comment by mdhorn** [comment]
Fixed in Clear Installer release [2.3.7](https://github.com/clearlinux/clr-installer/releases/tag/2.3.7)
Available in Clear Linux OS 31930 or later
https://clearlinux.org/downloads

**Comment by ionutnechita** [comment]
Hi @mdhorn,
I installed CL 31980 and it works correctly now.
Thanks much.
