### ISSUE TITLE
Allow advanced partition configuration via server yaml to use pre-existing partitions

### ISSUE THREAD

**Issue by tjad** [clearlinux/clr-installer#628]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my disk's partitions are created from scratch during install with server yaml configuration. ( clr-installer -c my_server.yaml )

**Describe the solution you'd like**
I would like my pre-existing partition table to be fully preserved (the installer should do absolutely no partitioning). I should be able to point to my pre-existing partitions by device label/index, and upon installation those partition structures are preserved and used for the respective CLR_ROOT, CLR_SWAP, CLR_BOOT.

**Describe alternatives you've considered**
AFAIK, no alternatives are available. I've not seen documentation regarding this. 

**Additional context**
This is for an iPXE boot. I can't use the GUI.
Ideally I use a pre-install script to partition the disk before the installer runs.

**Comment by tjad** [comment]
As a suggestion, I'd change functionality such that when omitting the "size" of a specific media target child, the installer knows not to repartition. (this is implicit and may not always be clear, but does make a sensible default).

Alternatively, a "preserve_parts" option could be added to the targetMedia.

**Comment by mdhorn** [comment]
@tjad Thanks for your request.

Very likely the implementation would be to use the existing [Advanced Configuration partition labels](https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html#advanced-installation) by using the CLR_* labels on partitions in the command line installer like the interactive installer.

We do have quite a backlog of feature requests to implement. To help prioritize this request, can you provide some impact information for us:
- about how many servers are you planning to deploy with this PXE feature?
- Is this a one-time use, or needed as part of a continuous deployment process?
- what is your timeline for these deployments?

Also, please keep in mind that this is an Open Source project, and we will always make time to review any submitted pull requests if you wish to pursue the implementation yourself.

**Comment by mdhorn** [comment]
> @tjad Thanks for your request.
> 
> Very likely the implementation would be to use the existing [Advanced Configuration partition labels](https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html#advanced-installation) by using the CLR_* labels on partitions in the command line installer like the interactive installer.
> 
> We do have quite a backlog of feature requests to implement. To help prioritize this request, can you provide some impact information for us:
> 
> * about how many servers are you planning to deploy with this PXE feature?
> * Is this a one-time use, or needed as part of a continuous deployment process?
> * what is your timeline for these deployments?
> 
> Also, please keep in mind that this is an Open Source project, and we will always make time to review any submitted pull requests if you wish to pursue the implementation yourself.

@tjad Can you provide feedback to gauge the scope and impact of this request?
thanks.

**Comment by tjad** [comment]
Hi Mark

Thanks for getting back on this. (started writing a couple weeks ago, got
caught up in team discussion re above, apologies for the delay).

In the short term (6m - 1y) we foresee a few deployments only(5-10).  In
the long term, well, we've been testing out Clear Linux as our new distro
of choice. It's very performant and we're keen on it thus far.
For scalability we are trying to completely automate our deployment process
which consists of custom raid partitioning, so we have a preinstall script
for this. We're going to be offering SaaS (potentially PaaS), We don't
particularly want to man any part of the server setup.

Right now we're just running a bunch of tests on a temporary server until
the end of the month (including this IPXE installation) to see how our
potential software stack works.
We thought for configuration flexibility it would be easiest to do our own
Raid setup and tell the OS installer where to install. We were set on
partitioning a portion of 1 of the 2TB drives for OS (+- 500GB) and the
remainder would contribute toward a Raid partition.

Yes, that makes sense regarding the advanced configuration partition
tables.

I'm getting a better idea of clear (and the architecture/project structure
now).  Thanks for your help.

**Comment by mdhorn** [comment]
@tjad Thanks for the feedback. 
This looks doable using the existing labels, just not sure how quickly it will move to the top of the list.

**Comment by tjad** [comment]
Thanks a lot!

**Comment by mdhorn** [comment]
@tjad It is merged into master, but we have two other changes I want to add to master before we cut a release. Hopefully this week.

**Comment by mdhorn** [comment]
Released in [2.4.3](https://github.com/clearlinux/clr-installer/releases/tag/2.4.3) in Clear Linux OS 32750 or higher.
