### ISSUE TITLE
Support btrfs on root in installer advanced options

### ISSUE THREAD

**Issue by kmatt** [clearlinux/clr-installer#629]
**Is your feature request related to a problem? Please describe.**

#448 suggests that btrfs on root was to be supported in release 31030. 

Using 31980 iso image, advanced option allows CLR_ROOT to be formatted as btrfs, but installer will only proceed with ext* or xfs.

**Describe the solution you'd like**

Install root on btrfs, mainly to support compression on space limited VMs.

**Comment by mdhorn** [comment]
@kmatt We do not allow BTRFS for the root file systems as the clr-boot-manager does not support that file system. Issue #448 was to remove BTRFS as an option for the root file system, not to enable it.

Until the [clr-boot-manager](https://github.com/clearlinux/clr-boot-manager) can support the root file system being formatted btrfs, the installer can not allow it.

**Comment by jennydaman** [comment]
@mdhorn I believe [clr-boot-manager](https://github.com/clearlinux/clr-boot-manager) now supports BTRFS

https://github.com/clearlinux/clr-boot-manager/pull/238

**Comment by victorstewart** [comment]
@jennydaman can you confirm you tried this and it works? btrfs is now allowed for the root filesystem?

**Comment by jennydaman** [comment]
Sorry @victorstewart i am not using clear linux anymore.
