### ISSUE TITLE
Graphical Installer fails if Destructive Installation is chosen but an exiting Docker LVM partition exists

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/clr-installer#633]
**Describe the bug**
If I use the Desktop installer and already have an existing Clear Installation setup with CLR_SWAP, CLR_BOOT and CLR_ROOT  partitioned with an lvm2 pv file system at the end setup by Docker and then try to install over it chosing "Destructive Installation" the install fails. The installer also loses all its settings already entered like the user, telemetry, etc.. forcing you to start over. The only way past this is to manually remove all the partitions.

This is occurring with the Clear Linux 32050 installer image and can be reproduced installing over an existing 32050 installation.

**To Reproduce**
1. Install Clear Linux and leave 50gb to 100gb unpartitioned at the end. Size shouldn't matter.
2. Install the `storage-utils` bundle if not already installed and then `sudo systemctl enable --now  lvm2-lvmetad.socket`
3. Use `sudo cfdisk /dev/sda` and add a "Linux Filesystem" partition at the end
4. Follow the [CONFIGURE DIRECT-LVM MODE MANUALLY](https://docs.docker.com/storage/storagedriver/device-mapper-driver/) guide to setup this partition.
5. Boot into the installer and choose "Destructive Installation"  The installer will fail.

**Expected behavior**
The installer should repartition the device and install onto the new partitions.

**Screenshots**
![IMG_20200109_162753](https://user-images.githubusercontent.com/25207372/72115912-7b010300-32fd-11ea-810a-ef9681c21069.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 32050
 - Installer Version: 2.3.7
 - Platform: Skull Canyon NUC with Intel i7-6770HQ CPU

**LOGS**
[partedoutput.txt](https://github.com/clearlinux/clr-installer/files/4043324/partedoutput.txt)
[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/4043337/pre-install-clr-installer.yaml.txt)
[fdiskoutput.txt](https://github.com/clearlinux/clr-installer/files/4043326/fdiskoutput.txt)
[clr-installer.log](https://github.com/clearlinux/clr-installer/files/4043328/clr-installer.log)

**Comment by mdhorn** [comment]
@eadamsintel This is a known issue with media that already contains LVM information.
I thought we had a separate issue for this problem, but instead, it is referenced in here
_Originally posted by @mdhorn in https://github.com/clearlinux/clr-installer/issues/8#issuecomment-493602572_

We will keep this open as we might fix this before implementing native LVM support.

**Comment by karthikprabhuvinod** [comment]
@mdhorn  I am wondering, For this specific case, I wonder why your change did not take effect :  https://github.com/clearlinux/clr-installer/pull/624

Your changes were in the 2.3.7 as well.

**Comment by mdhorn** [comment]
> @mdhorn I am wondering, For this specific case, I wonder why your change did not take effect : #624
> 
> Your changes were in the 2.3.7 as well.

There must be something different about the Docker LVM.
You'll have to set up a test case that matches the Docker LVM and debug why the previous fix didn't work -- likely levels (and lack of recursion).

**Comment by karthikprabhuvinod** [comment]
@mdhorn Looks in this case, blocks devices structures themselves as LV(metadata LV) which have LV as its children (data). This happens the LVs are converted into a thinpool . In this case, deleting only the data LV deletes even the metadata which is its parent.

**Comment by mdhorn** [comment]
Ready for next release

**Comment by mdhorn** [comment]
Fixed in clr-installer 2.6.1, Clear Linux OS 33300 or higher.
