### ISSUE TITLE
Resizing partitions in the installer

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/clr-installer#640]
`- clear linux os installer (1.2.5) -`

`clear linux 29200`

I tried this and did not go where I needed:

first try:
select destructive installation -> 
select disk 100G -> 
select Advanced Configuration Disk -> 
select disk 100G -> 
select auto partition -> 
select ext4 partition for resize -> 
change value for partition ( - 4G )  -> 
enter -> 
the partition lost the information about type, mount point and value

second try:
select destructive installation -> 
select  loop device-> 
select Advanced Configuration Disk -> 
select disk 100G -> 
select auto partition -> 
select ext4 partition for resize -> 
change value for partition ( - 4G ) -> 
enter -> 
the partition lost the information about type, mount point and value

the partition has no information, and I can not edit it anymore.

older clear linux installer, resizing worked.
please help me with a new installer update.

**Comment by mdhorn** [comment]
@ionutnechita Advanced partitioning has completely changed from the version referenced.
`gparted` is used in the graphical installer and `cgdisk` is now used for the text-based installer.

I'm going to close this issue. But if you still encounter an issue with the installer please open a new GitHub Issue in this repo.

thanks.
