### ISSUE TITLE
Cannot start live environment from USB

### ISSUE THREAD

**Issue by jhthenerd** [clearlinux/clr-installer#641]
I am unable to load any GUI when booting on real hardware. The ISO works in virtual machines, but freezes at `Found installer media, continuing boot... ` with no other information. All other TTYs are blank. This is on a ThinkPad T470 i5, with UEFI boot enabled. Let me know if any other information would be useful. 
![15578611156787004315963010639419](https://user-images.githubusercontent.com/11780062/57725254-b4904a00-765a-11e9-89c8-5b2610ef7464.jpg)

**Comment by mdhorn** [comment]
There seem to be two different booting issues discussed here.
The TPM one seems to have a workaround.

The other appears to be the NVME detection issue which was fixed in the default native kernel back in November. See https://github.com/clearlinux/distribution/issues/392
