### ISSUE TITLE
Some "reinstall" feature to reinstall a live / partition safely from ssh

### ISSUE THREAD

**Issue by Zhuul** [clearlinux/clr-installer#648]
**Is your feature request related to a problem? Please describe.**

I am using some Clearlinux box for testing. I may need some way to reinstall this host and restore it to "default install state" from a live system using ssh. 

Many other Linux distributions offer already such convenient feature (also Windows 10)  but it's missing as far as I know on Clearlinux.

**Describe the solution you'd like**

- Using "clr-install" or "swupd" something like "clr-install reinstall-base-system" (would reinstall Clearlinux to "default installation")  and/or "swupd reinstall-system" (would reinstall Clearlinux to default and reinstall automaticaly already installed bundles using their default configurations).
- If possible it would check and preserve ssh connection like Ubuntu does while upgrading from ssh. 
- Eventually this feature would also offer an easy way to backup to some /safebackup selected directories/files allowing a safe reinstall from ssh with  a simple unique command like "clr-install reinstall-base-system --backup /etc/,/home,/git,/motd.txt /safebackup".

**Describe alternatives you've considered**

"swupd repair --picky"

**Additional context**

Clearlinux is really convinient but some Linux system might sometimes get out of hands thus the need maybe of such convinient "reinstall" feature to be used from a live Clearlinux system to quickly backup and reinstall from a remote ssh connection a semi broken host , a hacked host,  a testing host, a dev host, etc.

**Comment by mdhorn** [comment]
@Zhuul What is the problem with `swupd repair --force --picky`?  That I believe is part of the intent.

Clear Linux is also Stateless so you can reset the system:
https://docs.01.org/clearlinux/latest/guides/clear/stateless.html?highlight=stateless#system-reset

This request seems out of scope for the installer, but if there is some specific shortcoming, maybe something can be added to swupd.

**Comment by Zhuul** [comment]
@mdhorn Thanks to remind me about Clearlinux being  "stateless", I'd just heard of it but wasn't 100% sure this worked. 

About  `swupd repair --force --picky` I'm not sure yet it worked for me, I've  had some weird issue with docker not creating some local-link for my docker0 ipv6  which is always down  /destination unreachable and ipv6 bridges not creating "as they should".
It's a host used for testing, it could be be "broken" thus my need to "completely reset" this host.

So to reset / reinstall a Clearlinux host I need to :

- remove extra bundles / mimic bundle list to make it like default Clearlinux (server) installation
- `sudo rm -rf /etc`
- `sudo rm -rf /var`
- `swupd repair --force --picky`
- `reboot`

In that order ?  Is this method (ssh) safe and effective to "reset" the host to default "post install state" ? 

Please if possible confirm me this… so I can process safely. Sory if I look picky but I haven't found any post or reference about this.

Maybe then my feature request is not revelant and can be forgotten. 

Still in my case I could't find the list of default bundles for "Clearlinux server" anywhere (I should have noted them first or save the install a file from clr-installer maybe)

I've had to reinstall a VM with a new Clearlinux to check it out... I needed to make some Clearlinux VM anyways... but still a "one command" reinstall feature offering "safety" for a remote ssh administrator and such would be I think welcomed by many who might be in similar situations as mine.

**Comment by mdhorn** [comment]
Those steps should work just fine to my knowledge.

But, If you really running in Docker, I would think you'd be better off using native Docker commands to save and restore the image.  https://docs.docker.com/engine/reference/commandline/cli/

**Comment by Zhuul** [comment]
Ok thanks, I'm going to apply these then, hopefully it should solve my issue. I don't need to backup any containers on this host so far thanks. I'm closing this ticket.

**Comment by mdhorn** [comment]
@Zhuul Tne one item to keep in mind is that if you created any customer networking or user, and you clear /etc that will remove those settings. So you might review the content of /etc before restoring to clearing all states.

**Comment by Zhuul** [comment]
@mdhorn If I delete /etc  (and /var) then do `swupd repair --force --picky` then only edit /etc/ssh/sshd_config to add "PermitRootLogin yes" will I be able to reboot and my host to find his IP using dhcp like he did on first install (what I'm expecting) ?

**Comment by mdhorn** [comment]
swupd does touch /etc or /var
Yes, NetworkManager defaults to using DHCP

**Comment by Zhuul** [comment]
Sorry if it's a weird question but how /etc and /var are supposed to "regenerate" if I delete them ?

Maybe for my current Docker problem I 'll just retry only 'swupd repair --force --picky' now that removed all unnecessary bundles and simply keep /etc and /var "as they are" and check how it goes when reinstalling Docker... and if necessary compare things with my Clearlinux VM (I'm using  qemu in host mode so network should behave about the same/ it should help). 

Still  thinking about it... a feature to reapply this "cool" YAML file from the initial installation toward an existing Clearlinux host in order to restore it "safely" to some "initial state" from the command line would be usefull maybe.  

I might be user responsability to make backups and to know which extra bundle is installed on his host before "reinitialise it" but having some easy restore or rather reinstall feature could help in many situations I think.

**Comment by Zhuul** [comment]
Well at least now I know where my problem is coming from : I retried to install  Docker and apparenty docker0 ipv6 is not working neither after an install on a default Clearlinux (unlike on Ubuntu, Centos etc). I am not sure where to report this and quite suprised no one reported this before.

**Comment by mdhorn** [comment]
Hope you get the Docker issue figured out.

As for this feature in the installer, it is something we'd ever want to support. swupd repair was created exactly for this reason.
