### ISSUE TITLE
Installation Failed and Crash during starting of the process

### ISSUE THREAD

**Issue by arfamtb96** [clearlinux/clr-installer#651]
Hi, I'm trying to clone my current ClearLinux OS to another machine using clr-installer.yaml file. So I try to follow this steps (https://docs.01.org/clearlinux/latest/get-started/install-configfile.html) example 2. It crashes right after I run the installation command. The error are as below and it mention to up an issue here. So my question is, how can I clone my current ClearLinuxOS  to another machine using clr-installer and a configuration file method.

![WhatsApp Image 2020-02-05 at 5 02 38 PM](https://user-images.githubusercontent.com/60690372/73827220-1cff0700-483a-11ea-80cd-66dd14c2cb19.jpeg)

Below is the attached document as requested in the above error.

[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/4158466/pre-install-clr-installer.yaml.txt)

[clr-installer.log](https://github.com/clearlinux/clr-installer/files/4158451/clr-installer.log)

**Comment by mdhorn** [comment]
The error message you are getting:
`2020/02/05 06:51:18 [DBG] Error: The location 256060M is outside of the device /dev/nvme0n1.
`
implies to me that the drive in the target system for cloning is not the same size as the original source of the clone.

Check both the source and the target sizes and ensure they are the same.
`lsblk /dev/nvme0n1`

Based on the error, I would assume the target is smaller than the source.

**Comment by mdhorn** [comment]
@arfamtb96 If the drive isn't exactly the same, the best thing to do is remove the size line from the top-level drive definition, and then change the size of the root '/' partition to '0' which will have it use the remained of the disk size.

```
$ diff -uNar from.yaml to.yaml
--- from.yaml	2020-02-05 18:27:41.000000000 -0800
+++ to.yaml	2020-02-05 18:28:01.000000000 -0800
@@ -6,7 +6,6 @@
   model: ADATA SX6000PNP
   majMin: "259:0"
   serial: 2J3120014709
-  size: "256060514304"
   ro: "false"
   rm: "false"
   type: disk
@@ -34,7 +33,7 @@
     uuid: cf1fcfdf-341a-4018-8f72-cf8e82feffbe
     mountpoint: /
     label: root
-    size: "255654514304"
+    size: "0"
     ro: "false"
     rm: "false"
     type: part
```

**Comment by arfamtb96** [comment]
@mdhorn I will try it next week since I am currently working on other project. I'll update back once I have tried as your comment. Thank you

**Comment by mdhorn** [comment]
@arfamtb96 Any update?
If we do not hear back, I'll close this as resolved next week.

**Comment by mdhorn** [comment]
Close as we have not had a response.
Hopefully the suggestion helped.
