### ISSUE TITLE
Correct URL for swupd in live-server, under Automatic OS Updates

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/clr-installer#667]
**Describe the bug**
Old/Incorrect URL exists in Clear Linux OS Installer [live-server] -> Automatic OS Updates [menu]. 
Update the URL
from: https://clearlinux.org/documentation/clear-linux/concepts/swupd-about
to: https://docs.01.org/clearlinux/latest/guides/clear/swupd.html

**Comment by mdhorn** [comment]
What happen to the redirect? 👎 

This will impact the text-based UI and the graphical UI as they share the same code base.

**Comment by mvincerx** [comment]
We're cleaning up what appear to be redirects that were flushed/overwritten in the build process. You know which team did this, and it was beyond our control. I filed an issue internally, and I separately requested our TCS team to re-apply the redirects that we previously implemented in Q3 of 2019.

**Comment by mdhorn** [comment]
fixed in clr-installer 2.4.1 starting with Clear Linux OS release 32510 or higher.
