### ISSUE TITLE
F2FS error

### ISSUE THREAD

**Issue by jckenny** [clearlinux/clr-installer#681]
**Describe the bug**
When using the f2fs filesystem with clr-installer, the program fails when formatting the f2fs partition. It appears that there is a syntax error with the mkfs.f2fs command. It is using an uppercase -L when it should be a lowercase -l for the volume label.

**To Reproduce**
1. Using attached clr-installer.yaml on live desktop iso version 32570.
2. Run 'sudo clr-installer -c clr-installer.yaml'
3. Error when formatting sda3 partition.

**Expected behavior**
clr-installer should format the partition without error and continue with the remaining installation steps.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 32570
 - Installer Version 2.4.1
 - Platform: lshw output attached as hwinfo.txt

**Additional context**
Log and config files attached.
[clr-installer.log.txt](https://github.com/clearlinux/clr-installer/files/4322145/clr-installer.log.txt)
[clr-installer.yaml.txt](https://github.com/clearlinux/clr-installer/files/4322146/clr-installer.yaml.txt)
[hwinfo.txt](https://github.com/clearlinux/clr-installer/files/4322147/hwinfo.txt)

**Comment by mdhorn** [comment]
@jckenny Thanks for the bug report.
Previously we only supported `ext` and `XFS` file system with encryption; `f2fs` was recently added to the installer. 
As you pointed out when referencing a partition by label `f2fs` uses `-l` instead of `-L` like `ext` and `XFS`.
We fix this in the next release.

**Comment by mdhorn** [comment]
Note this bug only occurs when combining encryption with f2fs.

**Comment by mdhorn** [comment]
Fixed in clr-installer 2.4.2 first released in Clear Linux OS 32600
