### ISSUE TITLE
BAT based Testing framework to exercise Clear installer args

### ISSUE THREAD

**Issue by karthikprabhuvinod** [clearlinux/clr-installer#710]
**Is your feature request related to a problem? Please describe.**
Currently we dont have a way to blackbox test out the command line args in installer. As a result, we need to rely on extremely careful review of PRs with possibility of missing out on something.

**Describe the solution you'd like**
1.) It would be good to introduce a BAT based testing framework which performs functional testing of   different combinations of args & then the outputs of that command. 
2.) Add a make bats target in Makefile & ensure to add it to travis as well

As ongoing tasks, add more tests, categories of tests, organized into meaningful sub-test like config-file, skip-validation,  etc

**Describe alternatives you've considered**
None. Careful evaluation of PRs

**Comment by karthikprabhuvinod** [comment]
@mdhorn I updated the scope now it seems it can be closed

**Comment by mdhorn** [comment]
Fixed in clr-installer 2.6.1, Clear Linux OS 33300 or higher.
