### ISSUE TITLE
proposal: switch to github.com/gdamore/tcell from termbox-go

### ISSUE THREAD

**Issue by milrope** [clearlinux/clr-installer#741]
as the author of [termbox-go](https://github.com/nsf/termbox-go) mentioned that it isn't maintained any more. and he suggest to use https://github.com/gdamore/tcell

**Comment by mdhorn** [comment]
Thank you for the suggestion.

We do not use termbox-go directly, but rather built text-based UI with https://github.com/VladimirMarkelov/clui which using termbox-go.

We would likely wait for CLUI to make the change first, or consider a new UI library.

**Comment by milrope** [comment]
i am a stupid person
