### ISSUE TITLE
Allow instalation without swap in the installer (as an option)

### ISSUE THREAD

**Issue by romulasry** [clearlinux/clr-installer#748]
**Is your feature request related to a problem? Please describe.**
I want to be able to install without a swap automaticly as an option

**Describe the solution you'd like**
An install but without a swap as an easy option

**Describe alternatives you've considered**
Manual partition but it isn't as easy as other distros

**Additional context**
N/A

**Comment by mdhorn** [comment]
@romulasry The Clear Linux OS architecture team determined that having a small amount of swap is a requirement for the OS, and hence the required default with the interactive installer. The default is now to create a small swap file for interactive installation (as of 2.5.0 release); which can then be easily deleted if not desired.

Non-interactive installations with a configuration file do not require a swap file; for example, if you are generating a VM image or a PXE install.
