### ISSUE TITLE
Installation from Live Media fails (Legacy BIOS mode): Cannot initialise bootloader syslinux

### ISSUE THREAD

**Issue by heis2201** [clearlinux/clr-installer#751]
**Describe the bug**
Tried to install ClrLnx from Live media in a VM using GUI installer. At the very end of the install process, a message appers: "Install failed. Please check logs..."

**To Reproduce**
Steps to reproduce the behavior/**not sure reproducable - this is what I did**
1. Download iso
2. Create VM in Virtualbox on Win10 (VM is emulating a Legacy BIOS firmware, not EFI)
3. Install using automatic partitioning scheme (Encrypt=1)
4. `[ERROR] cbm (../src/bootloaders/syslinux-common.c:L288): No boot partition found, you need to mark the boot partition with "legacy_boot" flag.`
`[DBG] [FATAL] cbm (../src/bootman/bootman.c:L163): Cannot initialise bootloader syslinux`

**Expected behavior**
Installer to install boot loader, not to fail.

**Log file**
```
[DEBUG] cbm (../src/cli/cli.c:L142): No such file: /tmp/install-717382988//etc/kernel/update_efi_vars
[INFO] cbm (../src/bootman/bootman.c:L744): Current running kernel: 5.7.13-975.native
[DEBUG] cbm (../src/lib/probe.c:L271): Root device exists on device-mapper configuration
[DEBUG] cbm (../src/bootman/bootman.c:L140): shim-systemd caps: 0x26, wanted: 0x0c
[DEBUG] cbm (../src/bootloaders/grub2.c:L563): grub2 not found at /tmp/install-717382988/usr/sbin/grub-mkconfig
[DEBUG] cbm (../src/bootman/bootman.c:L140): grub2 caps: 0x00, wanted: 0x0c
[DEBUG] cbm (../src/bootman/bootman.c:L140): syslinux caps: 0x2c, wanted: 0x0c
[DEBUG] cbm (../src/bootman/bootman.c:L157): Legacy boot now selected (syslinux)
[ERROR] cbm (../src/bootloaders/syslinux-common.c:L288): No boot partition found, you need to mark the boot partition with "legacy_boot" flag.
[FATAL] cbm (../src/bootman/bootman.c:L163): Cannot initialise bootloader syslinux
```

Full log file available at: https://paste.opensuse.org/37735465

**Environment:**
 - Clear Linux OS Version: clear-33590-live-desktop.iso
 - Installer Version clear-33590-live-desktop.iso
 - Platform: 64 bit VM in VirtualBox, on Win10 host

**Comment by mdhorn** [comment]
@heis2201 please try again using EFI as shown in this documentation:
https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/virtualbox-cl-installer.html

**Comment by heis2201** [comment]
Installing in EFI mode works. Is this a bug? Is Legacy BIOS mode not supported in Clear?

**Comment by mdhorn** [comment]
@heis2201 Clear Linux boot manager only supported EFI boot for most of its history. Only a few months ago it was updated to support legacy bios mode for bare metal. VirtualBox support for Legacy was never in scope or tested, and unlikely to get implemented in the near term.

**Comment by heis2201** [comment]
Ok, thank you for the information!
