### ISSUE TITLE
No media found for installation

### ISSUE THREAD

**Issue by heis2201** [clearlinux/clr-installer#752]
**bug description**
The installer does not recognize a virtual harddrive as install target.

I tried both BIOS/EFI firmware for the VM, I tried connecting the VM HDD using IDE as SATA (AHCI), no luck.  However, **Gnome Disks** recognizes the drive and even let's me format and mount it.

**To Reproduce**
1. Boot live media in VirtualBox
2. Run instaler
3. Select Installation media
4. **No media found for installation**

**Screenshots**
![installer](https://user-images.githubusercontent.com/17801574/89881848-4ff9cd00-dbc6-11ea-9fd2-27fd1a535a0b.JPG)
![disks](https://user-images.githubusercontent.com/17801574/89881855-525c2700-dbc6-11ea-8faa-e9089961dbfd.JPG)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 33590
 - Installer Version 2.7.0
 - Platform: 64 bit VM using VirtualBOx on Win10 host. (other GNU Linux VMs run smootly)

**Comment by mdhorn** [comment]
@heis2201 The minimum size for installing the Desktop distribution is 20GB. The installer will filter media which is not large enough to complete the installation.

19GB is probably "large enough", but by default, it requires 20GB.
You can override this limitation by adding the command line argument --skip-validation-size. You could also change this in the system configuration file for the installer by adding skipValidationSize: true to /usr/share/defaults/clr-installer/clr-installer.yaml

**Comment by heis2201** [comment]
Ok, thanks!
