### ISSUE TITLE
you must have been drunk when you chose  yaml as the config file format

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/clr-installer#774]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS Version: [swupd info]
 - Installer Version [clr-installer -v]
 - Platform: [hardware infomation]

**Additional context**

**Comment by mdhorn** [comment]
Thank you for your useless and unhelpful comments.
