### ISSUE TITLE
"Linkname can't be converted" warning during bare-metal install

### ISSUE THREAD

**Issue by dbkinder** [clearlinux/clr-installer#98]
Getting these warnings during a bare-metal install of CL 25410:

```
.
.
.
Extracting network-basic pack for version 25360

Extracting openssh-server pack for version 25110

Extracting os-core pack for version 25410
Warning: Linkname can't be converted from UTF-8 to current locale.
Warning: Linkname can't be converted from UTF-8 to current locale.
Warning: Linkname can't be converted from UTF-8 to current locale.

Extracting os-core-update pack for version 25370
.
.
.
```

**To Reproduce**
Burned clear-25410-installer.img to a USB stick and booted on a NUC.  Selected US keyboard, configured proxy during setup, did a "manual" (rather than automatic) install, specified a different hostname (dbkinder-desk1), and added all the optional additional packages listed. Did not see any other errors/warnings (but I can't scroll the screen to see) -- that's a different problem.

**Comment by otaviobp** [comment]
This is a problem in swupd. We have an issue opened for this and I recommend you to follow that for updates: https://github.com/clearlinux/swupd-client/issues/445

**Comment by dbkinder** [comment]
OK, thanks.

**Comment by dorileo** [comment]
This bug should had been reported to ister instead clr-installer (we don't have a release yet). Also this bug is a swupd issue - with that in mind, I'm closing this issue. Please reopen if you do think so.

Thanks...
